// ─── EMBEDDED DATA — GitHub Pages uyumlu, fetch gerektirmez ───

const DATA_A1_WORDS = [
  {id:"a1_001",word:"bonjour",translation_tr:"merhaba",translation_en:"hello",phonetic:"bɔ̃.ʒuʁ",category:"greetings",level:"A1",pexels_query:"greeting wave hello",emoji:"👋"},
  {id:"a1_002",word:"merci",translation_tr:"teşekkür ederim",translation_en:"thank you",phonetic:"mɛʁ.si",category:"greetings",level:"A1",pexels_query:"thank you gratitude",emoji:"🙏"},
  {id:"a1_003",word:"oui",translation_tr:"evet",translation_en:"yes",phonetic:"wi",category:"basics",level:"A1",pexels_query:"yes thumbs up",emoji:"✅"},
  {id:"a1_004",word:"non",translation_tr:"hayır",translation_en:"no",phonetic:"nɔ̃",category:"basics",level:"A1",pexels_query:"no rejection",emoji:"❌"},
  {id:"a1_005",word:"maison",translation_tr:"ev",translation_en:"house",phonetic:"mɛ.zɔ̃",category:"home",level:"A1",pexels_query:"house home building",emoji:"🏠"},
  {id:"a1_006",word:"eau",translation_tr:"su",translation_en:"water",phonetic:"o",category:"food",level:"A1",pexels_query:"water glass drink",emoji:"💧"},
  {id:"a1_007",word:"pain",translation_tr:"ekmek",translation_en:"bread",phonetic:"pɛ̃",category:"food",level:"A1",pexels_query:"bread bakery fresh",emoji:"🍞"},
  {id:"a1_008",word:"livre",translation_tr:"kitap",translation_en:"book",phonetic:"livʁ",category:"objects",level:"A1",pexels_query:"book reading library",emoji:"📚"},
  {id:"a1_009",word:"chat",translation_tr:"kedi",translation_en:"cat",phonetic:"ʃa",category:"animals",level:"A1",pexels_query:"cat kitten cute",emoji:"🐱"},
  {id:"a1_010",word:"chien",translation_tr:"köpek",translation_en:"dog",phonetic:"ʃjɛ̃",category:"animals",level:"A1",pexels_query:"dog puppy cute",emoji:"🐶"},
  {id:"a1_011",word:"voiture",translation_tr:"araba",translation_en:"car",phonetic:"vwa.tyʁ",category:"transport",level:"A1",pexels_query:"car automobile road",emoji:"🚗"},
  {id:"a1_012",word:"école",translation_tr:"okul",translation_en:"school",phonetic:"e.kɔl",category:"places",level:"A1",pexels_query:"school classroom building",emoji:"🏫"},
  {id:"a1_013",word:"ami",translation_tr:"arkadaş",translation_en:"friend",phonetic:"a.mi",category:"people",level:"A1",pexels_query:"friends friendship together",emoji:"👫"},
  {id:"a1_014",word:"famille",translation_tr:"aile",translation_en:"family",phonetic:"fa.mij",category:"people",level:"A1",pexels_query:"family together happy",emoji:"👨‍👩‍👧"},
  {id:"a1_015",word:"enfant",translation_tr:"çocuk",translation_en:"child",phonetic:"ɑ̃.fɑ̃",category:"people",level:"A1",pexels_query:"child kid playing",emoji:"👶"},
  {id:"a1_016",word:"soleil",translation_tr:"güneş",translation_en:"sun",phonetic:"sɔ.lɛj",category:"nature",level:"A1",pexels_query:"sun sunshine sky bright",emoji:"☀️"},
  {id:"a1_017",word:"fleur",translation_tr:"çiçek",translation_en:"flower",phonetic:"flœʁ",category:"nature",level:"A1",pexels_query:"flower bloom garden",emoji:"🌸"},
  {id:"a1_018",word:"pomme",translation_tr:"elma",translation_en:"apple",phonetic:"pɔm",category:"food",level:"A1",pexels_query:"apple fruit red",emoji:"🍎"},
  {id:"a1_019",word:"lait",translation_tr:"süt",translation_en:"milk",phonetic:"lɛ",category:"food",level:"A1",pexels_query:"milk glass white",emoji:"🥛"},
  {id:"a1_020",word:"table",translation_tr:"masa",translation_en:"table",phonetic:"tabl",category:"home",level:"A1",pexels_query:"table furniture wooden",emoji:"🪑"},
  {id:"a1_021",word:"chaise",translation_tr:"sandalye",translation_en:"chair",phonetic:"ʃɛz",category:"home",level:"A1",pexels_query:"chair furniture",emoji:"🪑"},
  {id:"a1_022",word:"fenêtre",translation_tr:"pencere",translation_en:"window",phonetic:"fə.nɛtʁ",category:"home",level:"A1",pexels_query:"window light room",emoji:"🪟"},
  {id:"a1_023",word:"porte",translation_tr:"kapı",translation_en:"door",phonetic:"pɔʁt",category:"home",level:"A1",pexels_query:"door entrance wooden",emoji:"🚪"},
  {id:"a1_024",word:"rue",translation_tr:"sokak",translation_en:"street",phonetic:"ʁy",category:"places",level:"A1",pexels_query:"street urban city road",emoji:"🛣️"},
  {id:"a1_025",word:"ville",translation_tr:"şehir",translation_en:"city",phonetic:"vil",category:"places",level:"A1",pexels_query:"city urban buildings",emoji:"🏙️"},
  {id:"a1_026",word:"pays",translation_tr:"ülke",translation_en:"country",phonetic:"pe.i",category:"places",level:"A1",pexels_query:"country landscape nature",emoji:"🗺️"},
  {id:"a1_027",word:"homme",translation_tr:"adam / erkek",translation_en:"man",phonetic:"ɔm",category:"people",level:"A1",pexels_query:"man adult male",emoji:"👨"},
  {id:"a1_028",word:"femme",translation_tr:"kadın",translation_en:"woman",phonetic:"fam",category:"people",level:"A1",pexels_query:"woman adult female",emoji:"👩"},
  {id:"a1_029",word:"garçon",translation_tr:"oğlan / erkek çocuk",translation_en:"boy",phonetic:"ɡaʁ.sɔ̃",category:"people",level:"A1",pexels_query:"boy child young",emoji:"👦"},
  {id:"a1_030",word:"fille",translation_tr:"kız çocuğu",translation_en:"girl",phonetic:"fij",category:"people",level:"A1",pexels_query:"girl child young",emoji:"👧"},
  {id:"a1_031",word:"mère",translation_tr:"anne",translation_en:"mother",phonetic:"mɛʁ",category:"people",level:"A1",pexels_query:"mother mom family",emoji:"👩"},
  {id:"a1_032",word:"père",translation_tr:"baba",translation_en:"father",phonetic:"pɛʁ",category:"people",level:"A1",pexels_query:"father dad family",emoji:"👨"},
  {id:"a1_033",word:"frère",translation_tr:"erkek kardeş",translation_en:"brother",phonetic:"fʁɛʁ",category:"people",level:"A1",pexels_query:"brother siblings",emoji:"👦"},
  {id:"a1_034",word:"sœur",translation_tr:"kız kardeş",translation_en:"sister",phonetic:"sœʁ",category:"people",level:"A1",pexels_query:"sister siblings girls",emoji:"👧"},
  {id:"a1_035",word:"heure",translation_tr:"saat",translation_en:"hour/time",phonetic:"œʁ",category:"time",level:"A1",pexels_query:"clock time hour",emoji:"🕐"},
  {id:"a1_036",word:"jour",translation_tr:"gün",translation_en:"day",phonetic:"ʒuʁ",category:"time",level:"A1",pexels_query:"day daylight sunrise",emoji:"📅"},
  {id:"a1_037",word:"nuit",translation_tr:"gece",translation_en:"night",phonetic:"nɥi",category:"time",level:"A1",pexels_query:"night sky dark stars",emoji:"🌙"},
  {id:"a1_038",word:"matin",translation_tr:"sabah",translation_en:"morning",phonetic:"ma.tɛ̃",category:"time",level:"A1",pexels_query:"morning sunrise coffee",emoji:"🌅"},
  {id:"a1_039",word:"soir",translation_tr:"akşam",translation_en:"evening",phonetic:"swaʁ",category:"time",level:"A1",pexels_query:"evening sunset dusk",emoji:"🌆"},
  {id:"a1_040",word:"semaine",translation_tr:"hafta",translation_en:"week",phonetic:"sə.mɛn",category:"time",level:"A1",pexels_query:"calendar week planner",emoji:"🗓️"},
  {id:"a1_041",word:"café",translation_tr:"kahve / kafe",translation_en:"coffee / café",phonetic:"ka.fe",category:"food",level:"A1",pexels_query:"coffee cafe cup",emoji:"☕"},
  {id:"a1_042",word:"restaurant",translation_tr:"restoran",translation_en:"restaurant",phonetic:"ʁɛs.tɔ.ʁɑ̃",category:"places",level:"A1",pexels_query:"restaurant dining food",emoji:"🍽️"},
  {id:"a1_043",word:"supermarché",translation_tr:"süpermarket",translation_en:"supermarket",phonetic:"sy.pɛʁ.maʁ.ʃe",category:"places",level:"A1",pexels_query:"supermarket grocery store",emoji:"🛒"},
  {id:"a1_044",word:"hôpital",translation_tr:"hastane",translation_en:"hospital",phonetic:"o.pi.tal",category:"places",level:"A1",pexels_query:"hospital medical building",emoji:"🏥"},
  {id:"a1_045",word:"pharmacie",translation_tr:"eczane",translation_en:"pharmacy",phonetic:"faʁ.ma.si",category:"places",level:"A1",pexels_query:"pharmacy medicine store",emoji:"💊"},
  {id:"a1_046",word:"banque",translation_tr:"banka",translation_en:"bank",phonetic:"bɑ̃k",category:"places",level:"A1",pexels_query:"bank finance building",emoji:"🏦"},
  {id:"a1_047",word:"train",translation_tr:"tren",translation_en:"train",phonetic:"tʁɛ̃",category:"transport",level:"A1",pexels_query:"train railway station",emoji:"🚂"},
  {id:"a1_048",word:"bus",translation_tr:"otobüs",translation_en:"bus",phonetic:"bys",category:"transport",level:"A1",pexels_query:"bus public transport",emoji:"🚌"},
  {id:"a1_049",word:"avion",translation_tr:"uçak",translation_en:"airplane",phonetic:"a.vjɔ̃",category:"transport",level:"A1",pexels_query:"airplane sky flight",emoji:"✈️"},
  {id:"a1_050",word:"vélo",translation_tr:"bisiklet",translation_en:"bicycle",phonetic:"ve.lo",category:"transport",level:"A1",pexels_query:"bicycle bike ride",emoji:"🚲"}
];

const DATA_A2_WORDS = [
  {id:"a2_001",word:"travail",translation_tr:"iş",translation_en:"work",phonetic:"tʁa.vaj",category:"work",level:"A2",pexels_query:"work office desk",emoji:"💼"},
  {id:"a2_002",word:"réunion",translation_tr:"toplantı",translation_en:"meeting",phonetic:"ʁe.y.njɔ̃",category:"work",level:"A2",pexels_query:"meeting conference business",emoji:"🤝"},
  {id:"a2_003",word:"appartement",translation_tr:"daire",translation_en:"apartment",phonetic:"a.paʁ.tə.mɑ̃",category:"home",level:"A2",pexels_query:"apartment interior living",emoji:"🏢"},
  {id:"a2_004",word:"cuisine",translation_tr:"mutfak",translation_en:"kitchen",phonetic:"kɥi.zin",category:"home",level:"A2",pexels_query:"kitchen cooking home",emoji:"👨‍🍳"},
  {id:"a2_005",word:"chambre",translation_tr:"yatak odası",translation_en:"bedroom",phonetic:"ʃɑ̃bʁ",category:"home",level:"A2",pexels_query:"bedroom bed room",emoji:"🛏️"},
  {id:"a2_006",word:"vacances",translation_tr:"tatil",translation_en:"vacation",phonetic:"va.kɑ̃s",category:"leisure",level:"A2",pexels_query:"vacation holiday travel beach",emoji:"🏖️"},
  {id:"a2_007",word:"voyage",translation_tr:"seyahat",translation_en:"trip/travel",phonetic:"vwa.jaʒ",category:"leisure",level:"A2",pexels_query:"travel journey adventure",emoji:"🧳"},
  {id:"a2_008",word:"sport",translation_tr:"spor",translation_en:"sport",phonetic:"spɔʁ",category:"leisure",level:"A2",pexels_query:"sport exercise fitness",emoji:"⚽"},
  {id:"a2_009",word:"musique",translation_tr:"müzik",translation_en:"music",phonetic:"my.zik",category:"leisure",level:"A2",pexels_query:"music concert headphones",emoji:"🎵"},
  {id:"a2_010",word:"cinéma",translation_tr:"sinema",translation_en:"cinema",phonetic:"si.ne.ma",category:"leisure",level:"A2",pexels_query:"cinema movie theater",emoji:"🎬"},
  {id:"a2_011",word:"magasin",translation_tr:"mağaza / dükkan",translation_en:"store/shop",phonetic:"ma.ɡa.zɛ̃",category:"places",level:"A2",pexels_query:"store shop retail",emoji:"🏪"},
  {id:"a2_012",word:"marché",translation_tr:"pazar",translation_en:"market",phonetic:"maʁ.ʃe",category:"places",level:"A2",pexels_query:"market outdoor food stalls",emoji:"🛍️"},
  {id:"a2_013",word:"météo",translation_tr:"hava durumu",translation_en:"weather",phonetic:"me.te.o",category:"nature",level:"A2",pexels_query:"weather forecast sky clouds",emoji:"⛅"},
  {id:"a2_014",word:"pluie",translation_tr:"yağmur",translation_en:"rain",phonetic:"plɥi",category:"nature",level:"A2",pexels_query:"rain rainy weather",emoji:"🌧️"},
  {id:"a2_015",word:"neige",translation_tr:"kar",translation_en:"snow",phonetic:"nɛʒ",category:"nature",level:"A2",pexels_query:"snow winter cold",emoji:"❄️"},
  {id:"a2_016",word:"rendez-vous",translation_tr:"randevu",translation_en:"appointment",phonetic:"ʁɑ̃.de.vu",category:"social",level:"A2",pexels_query:"appointment calendar meeting",emoji:"📅"},
  {id:"a2_017",word:"invitation",translation_tr:"davet",translation_en:"invitation",phonetic:"ɛ̃.vi.ta.sjɔ̃",category:"social",level:"A2",pexels_query:"invitation party celebration",emoji:"💌"},
  {id:"a2_018",word:"cadeau",translation_tr:"hediye",translation_en:"gift",phonetic:"ka.do",category:"social",level:"A2",pexels_query:"gift present wrapped",emoji:"🎁"},
  {id:"a2_019",word:"anniversaire",translation_tr:"doğum günü / yıldönümü",translation_en:"birthday/anniversary",phonetic:"a.ni.vɛʁ.sɛʁ",category:"social",level:"A2",pexels_query:"birthday cake celebration",emoji:"🎂"},
  {id:"a2_020",word:"santé",translation_tr:"sağlık",translation_en:"health",phonetic:"sɑ̃.te",category:"health",level:"A2",pexels_query:"health wellness medical",emoji:"❤️"}
];

const DATA_A1_SENTENCES = [
  {id:"s_a1_001",sentence:"Bonjour, je m'appelle Marie.",words:["Bonjour,","je","m'appelle","Marie."],translation_tr:"Merhaba, benim adım Marie.",translation_en:"Hello, my name is Marie.",level:"A1",topic:"introductions"},
  {id:"s_a1_002",sentence:"Comment vous appelez-vous ?",words:["Comment","vous","appelez-vous","?"],translation_tr:"Adınız ne?",translation_en:"What is your name?",level:"A1",topic:"introductions"},
  {id:"s_a1_003",sentence:"J'habite à Paris.",words:["J'habite","à","Paris."],translation_tr:"Paris'te oturuyorum.",translation_en:"I live in Paris.",level:"A1",topic:"places"},
  {id:"s_a1_004",sentence:"Il fait beau aujourd'hui.",words:["Il","fait","beau","aujourd'hui."],translation_tr:"Bugün hava güzel.",translation_en:"The weather is nice today.",level:"A1",topic:"weather"},
  {id:"s_a1_005",sentence:"Je voudrais un café, s'il vous plaît.",words:["Je","voudrais","un","café,","s'il","vous","plaît."],translation_tr:"Bir kahve istiyorum, lütfen.",translation_en:"I would like a coffee, please.",level:"A1",topic:"cafe"},
  {id:"s_a1_006",sentence:"Où est la gare ?",words:["Où","est","la","gare","?"],translation_tr:"Tren garı nerede?",translation_en:"Where is the train station?",level:"A1",topic:"directions"},
  {id:"s_a1_007",sentence:"Je parle un peu français.",words:["Je","parle","un","peu","français."],translation_tr:"Biraz Fransızca konuşuyorum.",translation_en:"I speak a little French.",level:"A1",topic:"language"},
  {id:"s_a1_008",sentence:"La maison est grande.",words:["La","maison","est","grande."],translation_tr:"Ev büyük.",translation_en:"The house is big.",level:"A1",topic:"home"},
  {id:"s_a1_009",sentence:"J'aime beaucoup la musique.",words:["J'aime","beaucoup","la","musique."],translation_tr:"Müziği çok seviyorum.",translation_en:"I love music very much.",level:"A1",topic:"hobbies"},
  {id:"s_a1_010",sentence:"Je mange une pomme.",words:["Je","mange","une","pomme."],translation_tr:"Bir elma yiyorum.",translation_en:"I am eating an apple.",level:"A1",topic:"food"},
  {id:"s_a1_011",sentence:"Mon chat s'appelle Minou.",words:["Mon","chat","s'appelle","Minou."],translation_tr:"Kedimin adı Minou.",translation_en:"My cat is called Minou.",level:"A1",topic:"animals"},
  {id:"s_a1_012",sentence:"Je vais à l'école en bus.",words:["Je","vais","à","l'école","en","bus."],translation_tr:"Okula otobüsle gidiyorum.",translation_en:"I go to school by bus.",level:"A1",topic:"transport"},
  {id:"s_a1_013",sentence:"Bonne nuit, à demain !",words:["Bonne","nuit,","à","demain","!"],translation_tr:"İyi geceler, yarına kadar!",translation_en:"Good night, see you tomorrow!",level:"A1",topic:"greetings"},
  {id:"s_a1_014",sentence:"Il y a un parc près d'ici.",words:["Il","y","a","un","parc","près","d'ici."],translation_tr:"Buranın yakınında bir park var.",translation_en:"There is a park near here.",level:"A1",topic:"places"},
  {id:"s_a1_015",sentence:"Quel âge avez-vous ?",words:["Quel","âge","avez-vous","?"],translation_tr:"Kaç yaşındasınız?",translation_en:"How old are you?",level:"A1",topic:"introductions"}
];

const DATA_A2_SENTENCES = [
  {id:"s_a2_001",sentence:"Je travaille dans une entreprise depuis deux ans.",words:["Je","travaille","dans","une","entreprise","depuis","deux","ans."],translation_tr:"İki yıldır bir şirkette çalışıyorum.",translation_en:"I have been working in a company for two years.",level:"A2",topic:"work"},
  {id:"s_a2_002",sentence:"Est-ce que vous pouvez répéter, s'il vous plaît ?",words:["Est-ce","que","vous","pouvez","répéter,","s'il","vous","plaît","?"],translation_tr:"Tekrar edebilir misiniz, lütfen?",translation_en:"Can you repeat that, please?",level:"A2",topic:"communication"},
  {id:"s_a2_003",sentence:"Le week-end, j'aime faire du sport.",words:["Le","week-end,","j'aime","faire","du","sport."],translation_tr:"Hafta sonları spor yapmayı seviyorum.",translation_en:"On weekends, I like to do sports.",level:"A2",topic:"hobbies"},
  {id:"s_a2_004",sentence:"Je suis allé au cinéma hier soir.",words:["Je","suis","allé","au","cinéma","hier","soir."],translation_tr:"Dün gece sinemaya gittim.",translation_en:"I went to the cinema last night.",level:"A2",topic:"leisure"},
  {id:"s_a2_005",sentence:"Pouvez-vous m'indiquer le chemin pour aller à la poste ?",words:["Pouvez-vous","m'indiquer","le","chemin","pour","aller","à","la","poste","?"],translation_tr:"Postaneye giden yolu gösterebilir misiniz?",translation_en:"Can you show me the way to the post office?",level:"A2",topic:"directions"},
  {id:"s_a2_006",sentence:"J'ai besoin d'acheter des médicaments.",words:["J'ai","besoin","d'acheter","des","médicaments."],translation_tr:"İlaç satın almam gerekiyor.",translation_en:"I need to buy some medicine.",level:"A2",topic:"health"},
  {id:"s_a2_007",sentence:"Le restaurant est ouvert tous les jours sauf le lundi.",words:["Le","restaurant","est","ouvert","tous","les","jours","sauf","le","lundi."],translation_tr:"Restoran pazartesi hariç her gün açık.",translation_en:"The restaurant is open every day except Monday.",level:"A2",topic:"food"},
  {id:"s_a2_008",sentence:"Je préfère voyager en train plutôt qu'en avion.",words:["Je","préfère","voyager","en","train","plutôt","qu'en","avion."],translation_tr:"Uçakla seyahat etmek yerine trenle gitmeyi tercih ederim.",translation_en:"I prefer to travel by train rather than by plane.",level:"A2",topic:"transport"},
  {id:"s_a2_009",sentence:"Mon appartement est au troisième étage.",words:["Mon","appartement","est","au","troisième","étage."],translation_tr:"Dairem üçüncü katta.",translation_en:"My apartment is on the third floor.",level:"A2",topic:"home"},
  {id:"s_a2_010",sentence:"Depuis combien de temps apprenez-vous le français ?",words:["Depuis","combien","de","temps","apprenez-vous","le","français","?"],translation_tr:"Ne zamandır Fransızca öğreniyorsunuz?",translation_en:"How long have you been learning French?",level:"A2",topic:"language"}
];
