const DATA_A1_WORDS = [

  // ─── SELAMLAŞMA & TEMEL İFADELER (20) ───
  {id:"a1_001",word:"bonjour",article:"",translation_tr:"merhaba",translation_en:"hello",phonetic:"bɔ̃.ʒuʁ",category:"greetings",gender:"v",level:"A1",emoji:"👋"},
  {id:"a1_002",word:"bonsoir",article:"",translation_tr:"iyi akşamlar",translation_en:"good evening",phonetic:"bɔ̃.swaʁ",category:"greetings",gender:"v",level:"A1",emoji:"🌙"},
  {id:"a1_003",word:"bonne nuit",article:"",translation_tr:"iyi geceler",translation_en:"good night",phonetic:"bɔn nɥi",category:"greetings",gender:"v",level:"A1",emoji:"😴"},
  {id:"a1_004",word:"au revoir",article:"",translation_tr:"hoşça kal",translation_en:"goodbye",phonetic:"o ʁə.vwaʁ",category:"greetings",gender:"v",level:"A1",emoji:"👋"},
  {id:"a1_005",word:"merci",article:"",translation_tr:"teşekkür ederim",translation_en:"thank you",phonetic:"mɛʁ.si",category:"greetings",gender:"v",level:"A1",emoji:"🙏"},
  {id:"a1_006",word:"s'il vous plaît",article:"",translation_tr:"lütfen (resmi)",translation_en:"please (formal)",phonetic:"sil vu plɛ",category:"greetings",gender:"v",level:"A1",emoji:"✨"},
  {id:"a1_007",word:"s'il te plaît",article:"",translation_tr:"lütfen (samimi)",translation_en:"please (informal)",phonetic:"sil tə plɛ",category:"greetings",gender:"v",level:"A1",emoji:"✨"},
  {id:"a1_008",word:"pardon",article:"",translation_tr:"özür dilerim",translation_en:"sorry/excuse me",phonetic:"paʁ.dɔ̃",category:"greetings",gender:"v",level:"A1",emoji:"🙇"},
  {id:"a1_009",word:"excusez-moi",article:"",translation_tr:"affedersiniz",translation_en:"excuse me",phonetic:"ɛks.ky.ze mwa",category:"greetings",gender:"v",level:"A1",emoji:"🙋"},
  {id:"a1_010",word:"oui",article:"",translation_tr:"evet",translation_en:"yes",phonetic:"wi",category:"basics",gender:"v",level:"A1",emoji:"✅"},
  {id:"a1_011",word:"non",article:"",translation_tr:"hayır",translation_en:"no",phonetic:"nɔ̃",category:"basics",gender:"v",level:"A1",emoji:"❌"},
  {id:"a1_012",word:"peut-être",article:"",translation_tr:"belki",translation_en:"maybe",phonetic:"pø.tɛtʁ",category:"basics",gender:"v",level:"A1",emoji:"🤔"},
  {id:"a1_013",word:"voilà",article:"",translation_tr:"işte / buyurun",translation_en:"here it is",phonetic:"vwa.la",category:"basics",gender:"v",level:"A1",emoji:"👌"},
  {id:"a1_014",word:"d'accord",article:"",translation_tr:"tamam / anlaştık",translation_en:"okay/agreed",phonetic:"da.kɔʁ",category:"basics",gender:"v",level:"A1",emoji:"👍"},
  {id:"a1_015",word:"bien sûr",article:"",translation_tr:"tabii ki",translation_en:"of course",phonetic:"bjɛ̃ syʁ",category:"basics",gender:"v",level:"A1",emoji:"💯"},
  {id:"a1_016",word:"comment",article:"",translation_tr:"nasıl",translation_en:"how",phonetic:"kɔ.mɑ̃",category:"basics",gender:"v",level:"A1",emoji:"❓"},
  {id:"a1_017",word:"pourquoi",article:"",translation_tr:"neden",translation_en:"why",phonetic:"puʁ.kwa",category:"basics",gender:"v",level:"A1",emoji:"❓"},
  {id:"a1_018",word:"quand",article:"",translation_tr:"ne zaman",translation_en:"when",phonetic:"kɑ̃",category:"basics",gender:"v",level:"A1",emoji:"📅"},
  {id:"a1_019",word:"où",article:"",translation_tr:"nerede",translation_en:"where",phonetic:"u",category:"basics",gender:"v",level:"A1",emoji:"📍"},
  {id:"a1_020",word:"combien",article:"",translation_tr:"kaç / ne kadar",translation_en:"how much/many",phonetic:"kɔ̃.bjɛ̃",category:"basics",gender:"v",level:"A1",emoji:"🔢"},

  // ─── KİŞİLER & AİLE (30) ───
  {id:"a1_021",word:"homme",article:"un",translation_tr:"adam / erkek",translation_en:"man",phonetic:"ɔm",category:"people",gender:"m",level:"A1",emoji:"👨"},
  {id:"a1_022",word:"femme",article:"une",translation_tr:"kadın",translation_en:"woman",phonetic:"fam",category:"people",gender:"f",level:"A1",emoji:"👩"},
  {id:"a1_023",word:"garçon",article:"un",translation_tr:"oğlan",translation_en:"boy",phonetic:"ɡaʁ.sɔ̃",category:"people",gender:"m",level:"A1",emoji:"👦"},
  {id:"a1_024",word:"fille",article:"une",translation_tr:"kız",translation_en:"girl",phonetic:"fij",category:"people",gender:"f",level:"A1",emoji:"👧"},
  {id:"a1_025",word:"enfant",article:"un",translation_tr:"çocuk",translation_en:"child",phonetic:"ɑ̃.fɑ̃",category:"people",gender:"m",level:"A1",emoji:"👶"},
  {id:"a1_026",word:"bébé",article:"un",translation_tr:"bebek",translation_en:"baby",phonetic:"be.be",category:"people",gender:"m",level:"A1",emoji:"👶"},
  {id:"a1_027",word:"famille",article:"une",translation_tr:"aile",translation_en:"family",phonetic:"fa.mij",category:"people",gender:"f",level:"A1",emoji:"👨‍👩‍👧"},
  {id:"a1_028",word:"père",article:"un",translation_tr:"baba",translation_en:"father",phonetic:"pɛʁ",category:"people",gender:"m",level:"A1",emoji:"👨"},
  {id:"a1_029",word:"mère",article:"une",translation_tr:"anne",translation_en:"mother",phonetic:"mɛʁ",category:"people",gender:"f",level:"A1",emoji:"👩"},
  {id:"a1_030",word:"fils",article:"un",translation_tr:"oğul",translation_en:"son",phonetic:"fis",category:"people",gender:"m",level:"A1",emoji:"👦"},
  {id:"a1_031",word:"fille",article:"une",translation_tr:"kız evlat",translation_en:"daughter",phonetic:"fij",category:"people",gender:"f",level:"A1",emoji:"👧"},
  {id:"a1_032",word:"frère",article:"un",translation_tr:"erkek kardeş",translation_en:"brother",phonetic:"fʁɛʁ",category:"people",gender:"m",level:"A1",emoji:"👦"},
  {id:"a1_033",word:"sœur",article:"une",translation_tr:"kız kardeş",translation_en:"sister",phonetic:"sœʁ",category:"people",gender:"f",level:"A1",emoji:"👧"},
  {id:"a1_034",word:"grand-père",article:"un",translation_tr:"büyükbaba",translation_en:"grandfather",phonetic:"ɡʁɑ̃.pɛʁ",category:"people",gender:"m",level:"A1",emoji:"👴"},
  {id:"a1_035",word:"grand-mère",article:"une",translation_tr:"büyükanne",translation_en:"grandmother",phonetic:"ɡʁɑ̃.mɛʁ",category:"people",gender:"f",level:"A1",emoji:"👵"},
  {id:"a1_036",word:"oncle",article:"un",translation_tr:"amca / dayı",translation_en:"uncle",phonetic:"ɔ̃kl",category:"people",gender:"m",level:"A1",emoji:"👨"},
  {id:"a1_037",word:"tante",article:"une",translation_tr:"hala / teyze",translation_en:"aunt",phonetic:"tɑ̃t",category:"people",gender:"f",level:"A1",emoji:"👩"},
  {id:"a1_038",word:"cousin",article:"un",translation_tr:"erkek kuzen",translation_en:"male cousin",phonetic:"ku.zɛ̃",category:"people",gender:"m",level:"A1",emoji:"👦"},
  {id:"a1_039",word:"cousine",article:"une",translation_tr:"kız kuzen",translation_en:"female cousin",phonetic:"ku.zin",category:"people",gender:"f",level:"A1",emoji:"👧"},
  {id:"a1_040",word:"ami",article:"un",translation_tr:"arkadaş (erkek)",translation_en:"friend (m)",phonetic:"a.mi",category:"people",gender:"m",level:"A1",emoji:"👫"},
  {id:"a1_041",word:"amie",article:"une",translation_tr:"arkadaş (kadın)",translation_en:"friend (f)",phonetic:"a.mi",category:"people",gender:"f",level:"A1",emoji:"👭"},
  {id:"a1_042",word:"voisin",article:"un",translation_tr:"komşu (erkek)",translation_en:"neighbour (m)",phonetic:"vwa.zɛ̃",category:"people",gender:"m",level:"A1",emoji:"🏘️"},
  {id:"a1_043",word:"voisine",article:"une",translation_tr:"komşu (kadın)",translation_en:"neighbour (f)",phonetic:"vwa.zin",category:"people",gender:"f",level:"A1",emoji:"🏘️"},
  {id:"a1_044",word:"monsieur",article:"",translation_tr:"bay / efendi",translation_en:"sir/mister",phonetic:"mə.sjø",category:"people",gender:"m",level:"A1",emoji:"🎩"},
  {id:"a1_045",word:"madame",article:"",translation_tr:"bayan / hanım",translation_en:"madam/mrs",phonetic:"ma.dam",category:"people",gender:"f",level:"A1",emoji:"👒"},
  {id:"a1_046",word:"mademoiselle",article:"",translation_tr:"bayan (genç)",translation_en:"miss",phonetic:"mad.mwa.zɛl",category:"people",gender:"f",level:"A1",emoji:"👧"},
  {id:"a1_047",word:"personne",article:"une",translation_tr:"kişi",translation_en:"person",phonetic:"pɛʁ.sɔn",category:"people",gender:"f",level:"A1",emoji:"🧑"},
  {id:"a1_048",word:"gens",article:"des",translation_tr:"insanlar",translation_en:"people",phonetic:"ʒɑ̃",category:"people",gender:"m",level:"A1",emoji:"👥"},
  {id:"a1_049",word:"mari",article:"un",translation_tr:"koca / eş (erkek)",translation_en:"husband",phonetic:"ma.ʁi",category:"people",gender:"m",level:"A1",emoji:"💍"},
  {id:"a1_050",word:"femme",article:"une",translation_tr:"eş (kadın) / karı",translation_en:"wife",phonetic:"fam",category:"people",gender:"f",level:"A1",emoji:"💍"},

  // ─── BEDEN & SAĞLIK (20) ───
  {id:"a1_051",word:"tête",article:"une",translation_tr:"baş / kafa",translation_en:"head",phonetic:"tɛt",category:"body",gender:"f",level:"A1",emoji:"🧠"},
  {id:"a1_052",word:"visage",article:"un",translation_tr:"yüz",translation_en:"face",phonetic:"vi.zaʒ",category:"body",gender:"m",level:"A1",emoji:"😊"},
  {id:"a1_053",word:"œil",article:"un",translation_tr:"göz",translation_en:"eye",phonetic:"œj",category:"body",gender:"m",level:"A1",emoji:"👁️"},
  {id:"a1_054",word:"nez",article:"un",translation_tr:"burun",translation_en:"nose",phonetic:"ne",category:"body",gender:"m",level:"A1",emoji:"👃"},
  {id:"a1_055",word:"bouche",article:"une",translation_tr:"ağız",translation_en:"mouth",phonetic:"buʃ",category:"body",gender:"f",level:"A1",emoji:"👄"},
  {id:"a1_056",word:"oreille",article:"une",translation_tr:"kulak",translation_en:"ear",phonetic:"ɔ.ʁɛj",category:"body",gender:"f",level:"A1",emoji:"👂"},
  {id:"a1_057",word:"cheveux",article:"des",translation_tr:"saç",translation_en:"hair",phonetic:"ʃə.vø",category:"body",gender:"m",level:"A1",emoji:"💇"},
  {id:"a1_058",word:"main",article:"une",translation_tr:"el",translation_en:"hand",phonetic:"mɛ̃",category:"body",gender:"f",level:"A1",emoji:"✋"},
  {id:"a1_059",word:"bras",article:"un",translation_tr:"kol",translation_en:"arm",phonetic:"bʁa",category:"body",gender:"m",level:"A1",emoji:"💪"},
  {id:"a1_060",word:"jambe",article:"une",translation_tr:"bacak",translation_en:"leg",phonetic:"ʒɑ̃b",category:"body",gender:"f",level:"A1",emoji:"🦵"},
  {id:"a1_061",word:"pied",article:"un",translation_tr:"ayak",translation_en:"foot",phonetic:"pje",category:"body",gender:"m",level:"A1",emoji:"🦶"},
  {id:"a1_062",word:"dos",article:"un",translation_tr:"sırt",translation_en:"back",phonetic:"do",category:"body",gender:"m",level:"A1",emoji:"🔙"},
  {id:"a1_063",word:"ventre",article:"un",translation_tr:"karın",translation_en:"belly/stomach",phonetic:"vɑ̃tʁ",category:"body",gender:"m",level:"A1",emoji:"🫃"},
  {id:"a1_064",word:"cœur",article:"un",translation_tr:"kalp",translation_en:"heart",phonetic:"kœʁ",category:"body",gender:"m",level:"A1",emoji:"❤️"},
  {id:"a1_065",word:"santé",article:"la",translation_tr:"sağlık",translation_en:"health",phonetic:"sɑ̃.te",category:"health",gender:"f",level:"A1",emoji:"💊"},
  {id:"a1_066",word:"médecin",article:"un",translation_tr:"doktor",translation_en:"doctor",phonetic:"me.dsɛ̃",category:"health",gender:"m",level:"A1",emoji:"👨‍⚕️"},
  {id:"a1_067",word:"hôpital",article:"un",translation_tr:"hastane",translation_en:"hospital",phonetic:"o.pi.tal",category:"health",gender:"m",level:"A1",emoji:"🏥"},
  {id:"a1_068",word:"pharmacie",article:"une",translation_tr:"eczane",translation_en:"pharmacy",phonetic:"faʁ.ma.si",category:"health",gender:"f",level:"A1",emoji:"💊"},
  {id:"a1_069",word:"médicament",article:"un",translation_tr:"ilaç",translation_en:"medicine",phonetic:"me.di.ka.mɑ̃",category:"health",gender:"m",level:"A1",emoji:"💉"},
  {id:"a1_070",word:"douleur",article:"une",translation_tr:"ağrı",translation_en:"pain",phonetic:"du.lœʁ",category:"health",gender:"f",level:"A1",emoji:"😢"},

  // ─── EV & MEKAN (30) ───
  {id:"a1_071",word:"maison",article:"une",translation_tr:"ev",translation_en:"house",phonetic:"mɛ.zɔ̃",category:"home",gender:"f",level:"A1",emoji:"🏠"},
  {id:"a1_072",word:"appartement",article:"un",translation_tr:"daire",translation_en:"apartment",phonetic:"a.paʁ.tə.mɑ̃",category:"home",gender:"m",level:"A1",emoji:"🏢"},
  {id:"a1_073",word:"pièce",article:"une",translation_tr:"oda",translation_en:"room",phonetic:"pjɛs",category:"home",gender:"f",level:"A1",emoji:"🚪"},
  {id:"a1_074",word:"salon",article:"un",translation_tr:"oturma odası",translation_en:"living room",phonetic:"sa.lɔ̃",category:"home",gender:"m",level:"A1",emoji:"🛋️"},
  {id:"a1_075",word:"cuisine",article:"une",translation_tr:"mutfak",translation_en:"kitchen",phonetic:"kɥi.zin",category:"home",gender:"f",level:"A1",emoji:"👨‍🍳"},
  {id:"a1_076",word:"chambre",article:"une",translation_tr:"yatak odası",translation_en:"bedroom",phonetic:"ʃɑ̃bʁ",category:"home",gender:"f",level:"A1",emoji:"🛏️"},
  {id:"a1_077",word:"salle de bains",article:"une",translation_tr:"banyo",translation_en:"bathroom",phonetic:"sal də bɛ̃",category:"home",gender:"f",level:"A1",emoji:"🛁"},
  {id:"a1_078",word:"toilettes",article:"des",translation_tr:"tuvalet",translation_en:"toilet",phonetic:"twa.lɛt",category:"home",gender:"f",level:"A1",emoji:"🚽"},
  {id:"a1_079",word:"jardin",article:"un",translation_tr:"bahçe",translation_en:"garden",phonetic:"ʒaʁ.dɛ̃",category:"home",gender:"m",level:"A1",emoji:"🌿"},
  {id:"a1_080",word:"porte",article:"une",translation_tr:"kapı",translation_en:"door",phonetic:"pɔʁt",category:"home",gender:"f",level:"A1",emoji:"🚪"},
  {id:"a1_081",word:"fenêtre",article:"une",translation_tr:"pencere",translation_en:"window",phonetic:"fə.nɛtʁ",category:"home",gender:"f",level:"A1",emoji:"🪟"},
  {id:"a1_082",word:"escalier",article:"un",translation_tr:"merdiven",translation_en:"stairs",phonetic:"ɛs.ka.lje",category:"home",gender:"m",level:"A1",emoji:"🪜"},
  {id:"a1_083",word:"table",article:"une",translation_tr:"masa",translation_en:"table",phonetic:"tabl",category:"home",gender:"f",level:"A1",emoji:"🪑"},
  {id:"a1_084",word:"chaise",article:"une",translation_tr:"sandalye",translation_en:"chair",phonetic:"ʃɛz",category:"home",gender:"f",level:"A1",emoji:"🪑"},
  {id:"a1_085",word:"lit",article:"un",translation_tr:"yatak",translation_en:"bed",phonetic:"li",category:"home",gender:"m",level:"A1",emoji:"🛏️"},
  {id:"a1_086",word:"canapé",article:"un",translation_tr:"kanepe",translation_en:"sofa",phonetic:"ka.na.pe",category:"home",gender:"m",level:"A1",emoji:"🛋️"},
  {id:"a1_087",word:"armoire",article:"une",translation_tr:"dolap",translation_en:"wardrobe",phonetic:"aʁ.mwaʁ",category:"home",gender:"f",level:"A1",emoji:"🗄️"},
  {id:"a1_088",word:"lampe",article:"une",translation_tr:"lamba",translation_en:"lamp",phonetic:"lɑ̃p",category:"home",gender:"f",level:"A1",emoji:"💡"},
  {id:"a1_089",word:"télévision",article:"une",translation_tr:"televizyon",translation_en:"television",phonetic:"te.le.vi.zjɔ̃",category:"home",gender:"f",level:"A1",emoji:"📺"},
  {id:"a1_090",word:"téléphone",article:"un",translation_tr:"telefon",translation_en:"telephone",phonetic:"te.le.fɔn",category:"home",gender:"m",level:"A1",emoji:"📱"},
  {id:"a1_091",word:"ordinateur",article:"un",translation_tr:"bilgisayar",translation_en:"computer",phonetic:"ɔʁ.di.na.tœʁ",category:"home",gender:"m",level:"A1",emoji:"💻"},
  {id:"a1_092",word:"clé",article:"une",translation_tr:"anahtar",translation_en:"key",phonetic:"kle",category:"home",gender:"f",level:"A1",emoji:"🔑"},
  {id:"a1_093",word:"adresse",article:"une",translation_tr:"adres",translation_en:"address",phonetic:"a.dʁɛs",category:"home",gender:"f",level:"A1",emoji:"📍"},
  {id:"a1_094",word:"étage",article:"un",translation_tr:"kat",translation_en:"floor/storey",phonetic:"e.taʒ",category:"home",gender:"m",level:"A1",emoji:"🏢"},
  {id:"a1_095",word:"immeuble",article:"un",translation_tr:"bina / apartman",translation_en:"building",phonetic:"i.mœbl",category:"home",gender:"m",level:"A1",emoji:"🏢"},
  {id:"a1_096",word:"quartier",article:"un",translation_tr:"mahalle / semt",translation_en:"neighbourhood",phonetic:"kaʁ.tje",category:"places",gender:"m",level:"A1",emoji:"🏘️"},
  {id:"a1_097",word:"rue",article:"une",translation_tr:"sokak",translation_en:"street",phonetic:"ʁy",category:"places",gender:"f",level:"A1",emoji:"🛣️"},
  {id:"a1_098",word:"avenue",article:"une",translation_tr:"cadde / bulvar",translation_en:"avenue",phonetic:"a.vny",category:"places",gender:"f",level:"A1",emoji:"🛣️"},
  {id:"a1_099",word:"place",article:"une",translation_tr:"meydan",translation_en:"square/place",phonetic:"plas",category:"places",gender:"f",level:"A1",emoji:"⛲"},
  {id:"a1_100",word:"chemin",article:"un",translation_tr:"yol / patika",translation_en:"path/way",phonetic:"ʃə.mɛ̃",category:"places",gender:"m",level:"A1",emoji:"🛤️"},

  // ─── YEMEK & İÇECEK (40) ───
  {id:"a1_101",word:"eau",article:"une",translation_tr:"su",translation_en:"water",phonetic:"o",category:"food",gender:"f",level:"A1",emoji:"💧"},
  {id:"a1_102",word:"café",article:"un",translation_tr:"kahve",translation_en:"coffee",phonetic:"ka.fe",category:"food",gender:"m",level:"A1",emoji:"☕"},
  {id:"a1_103",word:"thé",article:"un",translation_tr:"çay",translation_en:"tea",phonetic:"te",category:"food",gender:"m",level:"A1",emoji:"🍵"},
  {id:"a1_104",word:"lait",article:"un",translation_tr:"süt",translation_en:"milk",phonetic:"lɛ",category:"food",gender:"m",level:"A1",emoji:"🥛"},
  {id:"a1_105",word:"jus",article:"un",translation_tr:"meyve suyu",translation_en:"juice",phonetic:"ʒy",category:"food",gender:"m",level:"A1",emoji:"🧃"},
  {id:"a1_106",word:"vin",article:"un",translation_tr:"şarap",translation_en:"wine",phonetic:"vɛ̃",category:"food",gender:"m",level:"A1",emoji:"🍷"},
  {id:"a1_107",word:"bière",article:"une",translation_tr:"bira",translation_en:"beer",phonetic:"bjɛʁ",category:"food",gender:"f",level:"A1",emoji:"🍺"},
  {id:"a1_108",word:"pain",article:"un",translation_tr:"ekmek",translation_en:"bread",phonetic:"pɛ̃",category:"food",gender:"m",level:"A1",emoji:"🍞"},
  {id:"a1_109",word:"beurre",article:"un",translation_tr:"tereyağı",translation_en:"butter",phonetic:"bœʁ",category:"food",gender:"m",level:"A1",emoji:"🧈"},
  {id:"a1_110",word:"fromage",article:"un",translation_tr:"peynir",translation_en:"cheese",phonetic:"fʁo.maʒ",category:"food",gender:"m",level:"A1",emoji:"🧀"},
  {id:"a1_111",word:"œuf",article:"un",translation_tr:"yumurta",translation_en:"egg",phonetic:"œf",category:"food",gender:"m",level:"A1",emoji:"🥚"},
  {id:"a1_112",word:"viande",article:"une",translation_tr:"et",translation_en:"meat",phonetic:"vjɑ̃d",category:"food",gender:"f",level:"A1",emoji:"🥩"},
  {id:"a1_113",word:"poulet",article:"un",translation_tr:"tavuk",translation_en:"chicken",phonetic:"pu.lɛ",category:"food",gender:"m",level:"A1",emoji:"🍗"},
  {id:"a1_114",word:"poisson",article:"un",translation_tr:"balık",translation_en:"fish",phonetic:"pwa.sɔ̃",category:"food",gender:"m",level:"A1",emoji:"🐟"},
  {id:"a1_115",word:"légume",article:"un",translation_tr:"sebze",translation_en:"vegetable",phonetic:"le.ɡym",category:"food",gender:"m",level:"A1",emoji:"🥦"},
  {id:"a1_116",word:"fruit",article:"un",translation_tr:"meyve",translation_en:"fruit",phonetic:"fʁɥi",category:"food",gender:"m",level:"A1",emoji:"🍎"},
  {id:"a1_117",word:"pomme",article:"une",translation_tr:"elma",translation_en:"apple",phonetic:"pɔm",category:"food",gender:"f",level:"A1",emoji:"🍎"},
  {id:"a1_118",word:"orange",article:"une",translation_tr:"portakal",translation_en:"orange",phonetic:"ɔ.ʁɑ̃ʒ",category:"food",gender:"f",level:"A1",emoji:"🍊"},
  {id:"a1_119",word:"banane",article:"une",translation_tr:"muz",translation_en:"banana",phonetic:"ba.nan",category:"food",gender:"f",level:"A1",emoji:"🍌"},
  {id:"a1_120",word:"tomate",article:"une",translation_tr:"domates",translation_en:"tomato",phonetic:"tɔ.mat",category:"food",gender:"f",level:"A1",emoji:"🍅"},
  {id:"a1_121",word:"salade",article:"une",translation_tr:"salata",translation_en:"salad",phonetic:"sa.lad",category:"food",gender:"f",level:"A1",emoji:"🥗"},
  {id:"a1_122",word:"soupe",article:"une",translation_tr:"çorba",translation_en:"soup",phonetic:"sup",category:"food",gender:"f",level:"A1",emoji:"🍲"},
  {id:"a1_123",word:"sandwich",article:"un",translation_tr:"sandviç",translation_en:"sandwich",phonetic:"sɑ̃d.witʃ",category:"food",gender:"m",level:"A1",emoji:"🥪"},
  {id:"a1_124",word:"pizza",article:"une",translation_tr:"pizza",translation_en:"pizza",phonetic:"pid.za",category:"food",gender:"f",level:"A1",emoji:"🍕"},
  {id:"a1_125",word:"gâteau",article:"un",translation_tr:"kek / pasta",translation_en:"cake",phonetic:"ɡa.to",category:"food",gender:"m",level:"A1",emoji:"🎂"},
  {id:"a1_126",word:"sucre",article:"un",translation_tr:"şeker",translation_en:"sugar",phonetic:"sykʁ",category:"food",gender:"m",level:"A1",emoji:"🍬"},
  {id:"a1_127",word:"sel",article:"un",translation_tr:"tuz",translation_en:"salt",phonetic:"sɛl",category:"food",gender:"m",level:"A1",emoji:"🧂"},
  {id:"a1_128",word:"huile",article:"une",translation_tr:"yağ (sıvı)",translation_en:"oil",phonetic:"ɥil",category:"food",gender:"f",level:"A1",emoji:"🫙"},
  {id:"a1_129",word:"repas",article:"un",translation_tr:"yemek / öğün",translation_en:"meal",phonetic:"ʁə.pa",category:"food",gender:"m",level:"A1",emoji:"🍽️"},
  {id:"a1_130",word:"petit-déjeuner",article:"un",translation_tr:"kahvaltı",translation_en:"breakfast",phonetic:"pə.ti de.ʒœ.ne",category:"food",gender:"m",level:"A1",emoji:"🥐"},
  {id:"a1_131",word:"déjeuner",article:"un",translation_tr:"öğle yemeği",translation_en:"lunch",phonetic:"de.ʒœ.ne",category:"food",gender:"m",level:"A1",emoji:"🍱"},
  {id:"a1_132",word:"dîner",article:"un",translation_tr:"akşam yemeği",translation_en:"dinner",phonetic:"di.ne",category:"food",gender:"m",level:"A1",emoji:"🍽️"},
  {id:"a1_133",word:"restaurant",article:"un",translation_tr:"restoran",translation_en:"restaurant",phonetic:"ʁɛs.tɔ.ʁɑ̃",category:"places",gender:"m",level:"A1",emoji:"🍽️"},
  {id:"a1_134",word:"boulangerie",article:"une",translation_tr:"fırın / pastane",translation_en:"bakery",phonetic:"bu.lɑ̃.ʒʁi",category:"places",gender:"f",level:"A1",emoji:"🥖"},
  {id:"a1_135",word:"boucherie",article:"une",translation_tr:"kasap",translation_en:"butcher's",phonetic:"buʃ.ʁi",category:"places",gender:"f",level:"A1",emoji:"🥩"},
  {id:"a1_136",word:"épicerie",article:"une",translation_tr:"bakkal",translation_en:"grocery store",phonetic:"e.pis.ʁi",category:"places",gender:"f",level:"A1",emoji:"🛒"},
  {id:"a1_137",word:"supermarché",article:"un",translation_tr:"süpermarket",translation_en:"supermarket",phonetic:"sy.pɛʁ.maʁ.ʃe",category:"places",gender:"m",level:"A1",emoji:"🛒"},
  {id:"a1_138",word:"marché",article:"un",translation_tr:"pazar",translation_en:"market",phonetic:"maʁ.ʃe",category:"places",gender:"m",level:"A1",emoji:"🛍️"},
  {id:"a1_139",word:"menu",article:"un",translation_tr:"menü",translation_en:"menu",phonetic:"mə.ny",category:"food",gender:"m",level:"A1",emoji:"📋"},
  {id:"a1_140",word:"addition",article:"une",translation_tr:"hesap",translation_en:"bill/check",phonetic:"a.di.sjɔ̃",category:"food",gender:"f",level:"A1",emoji:"🧾"},

  // ─── GİYSİLER (20) ───
  {id:"a1_141",word:"vêtement",article:"un",translation_tr:"giysi",translation_en:"clothing",phonetic:"vɛt.mɑ̃",category:"clothes",gender:"m",level:"A1",emoji:"👕"},
  {id:"a1_142",word:"pantalon",article:"un",translation_tr:"pantolon",translation_en:"trousers",phonetic:"pɑ̃.ta.lɔ̃",category:"clothes",gender:"m",level:"A1",emoji:"👖"},
  {id:"a1_143",word:"jupe",article:"une",translation_tr:"etek",translation_en:"skirt",phonetic:"ʒyp",category:"clothes",gender:"f",level:"A1",emoji:"👗"},
  {id:"a1_144",word:"robe",article:"une",translation_tr:"elbise",translation_en:"dress",phonetic:"ʁɔb",category:"clothes",gender:"f",level:"A1",emoji:"👗"},
  {id:"a1_145",word:"chemise",article:"une",translation_tr:"gömlek",translation_en:"shirt",phonetic:"ʃə.miz",category:"clothes",gender:"f",level:"A1",emoji:"👔"},
  {id:"a1_146",word:"pull",article:"un",translation_tr:"kazak",translation_en:"sweater",phonetic:"pyl",category:"clothes",gender:"m",level:"A1",emoji:"🧥"},
  {id:"a1_147",word:"veste",article:"une",translation_tr:"ceket",translation_en:"jacket",phonetic:"vɛst",category:"clothes",gender:"f",level:"A1",emoji:"🧥"},
  {id:"a1_148",word:"manteau",article:"un",translation_tr:"palto",translation_en:"coat",phonetic:"mɑ̃.to",category:"clothes",gender:"m",level:"A1",emoji:"🧥"},
  {id:"a1_149",word:"chaussure",article:"une",translation_tr:"ayakkabı",translation_en:"shoe",phonetic:"ʃo.syʁ",category:"clothes",gender:"f",level:"A1",emoji:"👟"},
  {id:"a1_150",word:"chaussette",article:"une",translation_tr:"çorap",translation_en:"sock",phonetic:"ʃo.sɛt",category:"clothes",gender:"f",level:"A1",emoji:"🧦"},
  {id:"a1_151",word:"chapeau",article:"un",translation_tr:"şapka",translation_en:"hat",phonetic:"ʃa.po",category:"clothes",gender:"m",level:"A1",emoji:"🎩"},
  {id:"a1_152",word:"écharpe",article:"une",translation_tr:"atkı / eşarp",translation_en:"scarf",phonetic:"e.ʃaʁp",category:"clothes",gender:"f",level:"A1",emoji:"🧣"},
  {id:"a1_153",word:"gant",article:"un",translation_tr:"eldiven",translation_en:"glove",phonetic:"ɡɑ̃",category:"clothes",gender:"m",level:"A1",emoji:"🧤"},
  {id:"a1_154",word:"lunettes",article:"des",translation_tr:"gözlük",translation_en:"glasses",phonetic:"ly.nɛt",category:"clothes",gender:"f",level:"A1",emoji:"👓"},
  {id:"a1_155",word:"sac",article:"un",translation_tr:"çanta",translation_en:"bag",phonetic:"sak",category:"clothes",gender:"m",level:"A1",emoji:"👜"},
  {id:"a1_156",word:"sac à dos",article:"un",translation_tr:"sırt çantası",translation_en:"backpack",phonetic:"sak a do",category:"clothes",gender:"m",level:"A1",emoji:"🎒"},
  {id:"a1_157",word:"ceinture",article:"une",translation_tr:"kemer",translation_en:"belt",phonetic:"sɛ̃.tyʁ",category:"clothes",gender:"f",level:"A1",emoji:"👔"},
  {id:"a1_158",word:"montre",article:"une",translation_tr:"kol saati",translation_en:"watch",phonetic:"mɔ̃tʁ",category:"clothes",gender:"f",level:"A1",emoji:"⌚"},
  {id:"a1_159",word:"couleur",article:"une",translation_tr:"renk",translation_en:"colour",phonetic:"ku.lœʁ",category:"clothes",gender:"f",level:"A1",emoji:"🎨"},
  {id:"a1_160",word:"taille",article:"une",translation_tr:"beden / boyut",translation_en:"size",phonetic:"taj",category:"clothes",gender:"f",level:"A1",emoji:"📏"},

  // ─── RENKler (12) ───
  {id:"a1_161",word:"rouge",article:"",translation_tr:"kırmızı",translation_en:"red",phonetic:"ʁuʒ",category:"colors",gender:"v",level:"A1",emoji:"🔴"},
  {id:"a1_162",word:"bleu",article:"",translation_tr:"mavi",translation_en:"blue",phonetic:"blø",category:"colors",gender:"v",level:"A1",emoji:"🔵"},
  {id:"a1_163",word:"vert",article:"",translation_tr:"yeşil",translation_en:"green",phonetic:"vɛʁ",category:"colors",gender:"v",level:"A1",emoji:"🟢"},
  {id:"a1_164",word:"jaune",article:"",translation_tr:"sarı",translation_en:"yellow",phonetic:"ʒon",category:"colors",gender:"v",level:"A1",emoji:"🟡"},
  {id:"a1_165",word:"noir",article:"",translation_tr:"siyah",translation_en:"black",phonetic:"nwaʁ",category:"colors",gender:"v",level:"A1",emoji:"⚫"},
  {id:"a1_166",word:"blanc",article:"",translation_tr:"beyaz",translation_en:"white",phonetic:"blɑ̃",category:"colors",gender:"v",level:"A1",emoji:"⚪"},
  {id:"a1_167",word:"gris",article:"",translation_tr:"gri",translation_en:"grey",phonetic:"ɡʁi",category:"colors",gender:"v",level:"A1",emoji:"🩶"},
  {id:"a1_168",word:"orange",article:"",translation_tr:"turuncu",translation_en:"orange",phonetic:"ɔ.ʁɑ̃ʒ",category:"colors",gender:"v",level:"A1",emoji:"🟠"},
  {id:"a1_169",word:"rose",article:"",translation_tr:"pembe",translation_en:"pink",phonetic:"ʁoz",category:"colors",gender:"v",level:"A1",emoji:"🩷"},
  {id:"a1_170",word:"violet",article:"",translation_tr:"mor",translation_en:"purple",phonetic:"vjɔ.lɛ",category:"colors",gender:"v",level:"A1",emoji:"🟣"},
  {id:"a1_171",word:"marron",article:"",translation_tr:"kahverengi",translation_en:"brown",phonetic:"ma.ʁɔ̃",category:"colors",gender:"v",level:"A1",emoji:"🟤"},
  {id:"a1_172",word:"beige",article:"",translation_tr:"bej",translation_en:"beige",phonetic:"bɛʒ",category:"colors",gender:"v",level:"A1",emoji:"🟫"},

  // ─── ULAŞIM (20) ───
  {id:"a1_173",word:"voiture",article:"une",translation_tr:"araba",translation_en:"car",phonetic:"vwa.tyʁ",category:"transport",gender:"f",level:"A1",emoji:"🚗"},
  {id:"a1_174",word:"bus",article:"un",translation_tr:"otobüs",translation_en:"bus",phonetic:"bys",category:"transport",gender:"m",level:"A1",emoji:"🚌"},
  {id:"a1_175",word:"train",article:"un",translation_tr:"tren",translation_en:"train",phonetic:"tʁɛ̃",category:"transport",gender:"m",level:"A1",emoji:"🚂"},
  {id:"a1_176",word:"métro",article:"un",translation_tr:"metro",translation_en:"metro/subway",phonetic:"me.tʁo",category:"transport",gender:"m",level:"A1",emoji:"🚇"},
  {id:"a1_177",word:"avion",article:"un",translation_tr:"uçak",translation_en:"airplane",phonetic:"a.vjɔ̃",category:"transport",gender:"m",level:"A1",emoji:"✈️"},
  {id:"a1_178",word:"vélo",article:"un",translation_tr:"bisiklet",translation_en:"bicycle",phonetic:"ve.lo",category:"transport",gender:"m",level:"A1",emoji:"🚲"},
  {id:"a1_179",word:"moto",article:"une",translation_tr:"motosiklet",translation_en:"motorbike",phonetic:"mo.to",category:"transport",gender:"f",level:"A1",emoji:"🏍️"},
  {id:"a1_180",word:"taxi",article:"un",translation_tr:"taksi",translation_en:"taxi",phonetic:"tak.si",category:"transport",gender:"m",level:"A1",emoji:"🚕"},
  {id:"a1_181",word:"bateau",article:"un",translation_tr:"tekne / gemi",translation_en:"boat",phonetic:"ba.to",category:"transport",gender:"m",level:"A1",emoji:"⛵"},
  {id:"a1_182",word:"gare",article:"une",translation_tr:"tren garı",translation_en:"train station",phonetic:"ɡaʁ",category:"places",gender:"f",level:"A1",emoji:"🚉"},
  {id:"a1_183",word:"aéroport",article:"un",translation_tr:"havalimanı",translation_en:"airport",phonetic:"a.e.ʁo.pɔʁ",category:"places",gender:"m",level:"A1",emoji:"✈️"},
  {id:"a1_184",word:"arrêt",article:"un",translation_tr:"durak",translation_en:"stop",phonetic:"a.ʁɛ",category:"transport",gender:"m",level:"A1",emoji:"🚏"},
  {id:"a1_185",word:"ticket",article:"un",translation_tr:"bilet",translation_en:"ticket",phonetic:"ti.kɛ",category:"transport",gender:"m",level:"A1",emoji:"🎫"},
  {id:"a1_186",word:"billet",article:"un",translation_tr:"bilet (tren/uçak)",translation_en:"ticket (train/plane)",phonetic:"bi.jɛ",category:"transport",gender:"m",level:"A1",emoji:"🎟️"},
  {id:"a1_187",word:"route",article:"une",translation_tr:"yol / karayolu",translation_en:"road",phonetic:"ʁut",category:"transport",gender:"f",level:"A1",emoji:"🛣️"},
  {id:"a1_188",word:"pont",article:"un",translation_tr:"köprü",translation_en:"bridge",phonetic:"pɔ̃",category:"places",gender:"m",level:"A1",emoji:"🌉"},
  {id:"a1_189",word:"carrefour",article:"un",translation_tr:"kavşak",translation_en:"crossroads",phonetic:"kaʁ.fuʁ",category:"places",gender:"m",level:"A1",emoji:"🔀"},
  {id:"a1_190",word:"parking",article:"un",translation_tr:"otopark",translation_en:"car park",phonetic:"paʁ.kiŋ",category:"places",gender:"m",level:"A1",emoji:"🅿️"},
  {id:"a1_191",word:"essence",article:"une",translation_tr:"benzin / yakıt",translation_en:"petrol/gas",phonetic:"e.sɑ̃s",category:"transport",gender:"f",level:"A1",emoji:"⛽"},
  {id:"a1_192",word:"permis de conduire",article:"un",translation_tr:"ehliyet",translation_en:"driving licence",phonetic:"pɛʁ.mi də kɔ̃.dɥiʁ",category:"transport",gender:"m",level:"A1",emoji:"🪪"},

  // ─── MEKANLAR & ŞEHİR (25) ───
  {id:"a1_193",word:"ville",article:"une",translation_tr:"şehir",translation_en:"city",phonetic:"vil",category:"places",gender:"f",level:"A1",emoji:"🏙️"},
  {id:"a1_194",word:"pays",article:"un",translation_tr:"ülke",translation_en:"country",phonetic:"pe.i",category:"places",gender:"m",level:"A1",emoji:"🗺️"},
  {id:"a1_195",word:"région",article:"une",translation_tr:"bölge",translation_en:"region",phonetic:"ʁe.ʒjɔ̃",category:"places",gender:"f",level:"A1",emoji:"🗺️"},
  {id:"a1_196",word:"centre-ville",article:"un",translation_tr:"şehir merkezi",translation_en:"city centre",phonetic:"sɑ̃tʁ vil",category:"places",gender:"m",level:"A1",emoji:"🏙️"},
  {id:"a1_197",word:"magasin",article:"un",translation_tr:"mağaza",translation_en:"shop/store",phonetic:"ma.ɡa.zɛ̃",category:"places",gender:"m",level:"A1",emoji:"🏪"},
  {id:"a1_198",word:"banque",article:"une",translation_tr:"banka",translation_en:"bank",phonetic:"bɑ̃k",category:"places",gender:"f",level:"A1",emoji:"🏦"},
  {id:"a1_199",word:"poste",article:"une",translation_tr:"postane",translation_en:"post office",phonetic:"pɔst",category:"places",gender:"f",level:"A1",emoji:"📮"},
  {id:"a1_200",word:"école",article:"une",translation_tr:"okul",translation_en:"school",phonetic:"e.kɔl",category:"places",gender:"f",level:"A1",emoji:"🏫"},
  {id:"a1_201",word:"université",article:"une",translation_tr:"üniversite",translation_en:"university",phonetic:"y.ni.vɛʁ.si.te",category:"places",gender:"f",level:"A1",emoji:"🎓"},
  {id:"a1_202",word:"bibliothèque",article:"une",translation_tr:"kütüphane",translation_en:"library",phonetic:"bi.bljɔ.tɛk",category:"places",gender:"f",level:"A1",emoji:"📚"},
  {id:"a1_203",word:"musée",article:"un",translation_tr:"müze",translation_en:"museum",phonetic:"my.ze",category:"places",gender:"m",level:"A1",emoji:"🏛️"},
  {id:"a1_204",word:"cinéma",article:"un",translation_tr:"sinema",translation_en:"cinema",phonetic:"si.ne.ma",category:"places",gender:"m",level:"A1",emoji:"🎬"},
  {id:"a1_205",word:"théâtre",article:"un",translation_tr:"tiyatro",translation_en:"theatre",phonetic:"te.atʁ",category:"places",gender:"m",level:"A1",emoji:"🎭"},
  {id:"a1_206",word:"hôtel",article:"un",translation_tr:"otel",translation_en:"hotel",phonetic:"o.tɛl",category:"places",gender:"m",level:"A1",emoji:"🏨"},
  {id:"a1_207",word:"église",article:"une",translation_tr:"kilise",translation_en:"church",phonetic:"e.ɡliz",category:"places",gender:"f",level:"A1",emoji:"⛪"},
  {id:"a1_208",word:"parc",article:"un",translation_tr:"park",translation_en:"park",phonetic:"paʁk",category:"places",gender:"m",level:"A1",emoji:"🌳"},
  {id:"a1_209",word:"jardin public",article:"un",translation_tr:"halk bahçesi",translation_en:"public garden",phonetic:"ʒaʁ.dɛ̃ py.blik",category:"places",gender:"m",level:"A1",emoji:"🌿"},
  {id:"a1_210",word:"piscine",article:"une",translation_tr:"yüzme havuzu",translation_en:"swimming pool",phonetic:"pi.sin",category:"places",gender:"f",level:"A1",emoji:"🏊"},
  {id:"a1_211",word:"stade",article:"un",translation_tr:"stadyum",translation_en:"stadium",phonetic:"stad",category:"places",gender:"m",level:"A1",emoji:"🏟️"},
  {id:"a1_212",word:"plage",article:"une",translation_tr:"plaj / sahil",translation_en:"beach",phonetic:"plaʒ",category:"places",gender:"f",level:"A1",emoji:"🏖️"},
  {id:"a1_213",word:"montagne",article:"une",translation_tr:"dağ",translation_en:"mountain",phonetic:"mɔ̃.taɲ",category:"nature",gender:"f",level:"A1",emoji:"⛰️"},
  {id:"a1_214",word:"mer",article:"une",translation_tr:"deniz",translation_en:"sea",phonetic:"mɛʁ",category:"nature",gender:"f",level:"A1",emoji:"🌊"},
  {id:"a1_215",word:"forêt",article:"une",translation_tr:"orman",translation_en:"forest",phonetic:"fɔ.ʁɛ",category:"nature",gender:"f",level:"A1",emoji:"🌲"},
  {id:"a1_216",word:"rivière",article:"une",translation_tr:"nehir / ırmak",translation_en:"river",phonetic:"ʁi.vjɛʁ",category:"nature",gender:"f",level:"A1",emoji:"🏞️"},
  {id:"a1_217",word:"campagne",article:"une",translation_tr:"kırsal / taşra",translation_en:"countryside",phonetic:"kɑ̃.paɲ",category:"nature",gender:"f",level:"A1",emoji:"🌾"},

  // ─── DOĞA & HAVA DURUMU (18) ───
  {id:"a1_218",word:"soleil",article:"un",translation_tr:"güneş",translation_en:"sun",phonetic:"sɔ.lɛj",category:"nature",gender:"m",level:"A1",emoji:"☀️"},
  {id:"a1_219",word:"pluie",article:"une",translation_tr:"yağmur",translation_en:"rain",phonetic:"plɥi",category:"nature",gender:"f",level:"A1",emoji:"🌧️"},
  {id:"a1_220",word:"neige",article:"une",translation_tr:"kar",translation_en:"snow",phonetic:"nɛʒ",category:"nature",gender:"f",level:"A1",emoji:"❄️"},
  {id:"a1_221",word:"vent",article:"un",translation_tr:"rüzgar",translation_en:"wind",phonetic:"vɑ̃",category:"nature",gender:"m",level:"A1",emoji:"💨"},
  {id:"a1_222",word:"nuage",article:"un",translation_tr:"bulut",translation_en:"cloud",phonetic:"nɥaʒ",category:"nature",gender:"m",level:"A1",emoji:"☁️"},
  {id:"a1_223",word:"ciel",article:"un",translation_tr:"gökyüzü",translation_en:"sky",phonetic:"sjɛl",category:"nature",gender:"m",level:"A1",emoji:"🌤️"},
  {id:"a1_224",word:"météo",article:"une",translation_tr:"hava durumu",translation_en:"weather",phonetic:"me.te.o",category:"nature",gender:"f",level:"A1",emoji:"⛅"},
  {id:"a1_225",word:"température",article:"une",translation_tr:"sıcaklık",translation_en:"temperature",phonetic:"tɑ̃.pe.ʁa.tyʁ",category:"nature",gender:"f",level:"A1",emoji:"🌡️"},
  {id:"a1_226",word:"chaud",article:"",translation_tr:"sıcak",translation_en:"hot/warm",phonetic:"ʃo",category:"nature",gender:"v",level:"A1",emoji:"🌡️"},
  {id:"a1_227",word:"froid",article:"",translation_tr:"soğuk",translation_en:"cold",phonetic:"fʁwa",category:"nature",gender:"v",level:"A1",emoji:"🥶"},
  {id:"a1_228",word:"fleur",article:"une",translation_tr:"çiçek",translation_en:"flower",phonetic:"flœʁ",category:"nature",gender:"f",level:"A1",emoji:"🌸"},
  {id:"a1_229",word:"arbre",article:"un",translation_tr:"ağaç",translation_en:"tree",phonetic:"aʁbʁ",category:"nature",gender:"m",level:"A1",emoji:"🌳"},
  {id:"a1_230",word:"herbe",article:"une",translation_tr:"çim / ot",translation_en:"grass",phonetic:"ɛʁb",category:"nature",gender:"f",level:"A1",emoji:"🌿"},
  {id:"a1_231",word:"lune",article:"une",translation_tr:"ay",translation_en:"moon",phonetic:"lyn",category:"nature",gender:"f",level:"A1",emoji:"🌙"},
  {id:"a1_232",word:"étoile",article:"une",translation_tr:"yıldız",translation_en:"star",phonetic:"e.twal",category:"nature",gender:"f",level:"A1",emoji:"⭐"},
  {id:"a1_233",word:"saison",article:"une",translation_tr:"mevsim",translation_en:"season",phonetic:"sɛ.zɔ̃",category:"nature",gender:"f",level:"A1",emoji:"🍂"},
  {id:"a1_234",word:"printemps",article:"un",translation_tr:"ilkbahar",translation_en:"spring",phonetic:"pʁɛ̃.tɑ̃",category:"nature",gender:"m",level:"A1",emoji:"🌸"},
  {id:"a1_235",word:"été",article:"un",translation_tr:"yaz",translation_en:"summer",phonetic:"e.te",category:"nature",gender:"m",level:"A1",emoji:"☀️"},

  // ─── ZAMAN & TARİH (30) ───
  {id:"a1_236",word:"heure",article:"une",translation_tr:"saat (zaman birimi)",translation_en:"hour",phonetic:"œʁ",category:"time",gender:"f",level:"A1",emoji:"🕐"},
  {id:"a1_237",word:"minute",article:"une",translation_tr:"dakika",translation_en:"minute",phonetic:"mi.nyt",category:"time",gender:"f",level:"A1",emoji:"⏱️"},
  {id:"a1_238",word:"seconde",article:"une",translation_tr:"saniye",translation_en:"second",phonetic:"sə.ɡɔ̃d",category:"time",gender:"f",level:"A1",emoji:"⏱️"},
  {id:"a1_239",word:"jour",article:"un",translation_tr:"gün",translation_en:"day",phonetic:"ʒuʁ",category:"time",gender:"m",level:"A1",emoji:"📅"},
  {id:"a1_240",word:"semaine",article:"une",translation_tr:"hafta",translation_en:"week",phonetic:"sə.mɛn",category:"time",gender:"f",level:"A1",emoji:"🗓️"},
  {id:"a1_241",word:"mois",article:"un",translation_tr:"ay (takvim)",translation_en:"month",phonetic:"mwa",category:"time",gender:"m",level:"A1",emoji:"📅"},
  {id:"a1_242",word:"an",article:"un",translation_tr:"yıl",translation_en:"year",phonetic:"ɑ̃",category:"time",gender:"m",level:"A1",emoji:"🎉"},
  {id:"a1_243",word:"année",article:"une",translation_tr:"yıl (süre)",translation_en:"year",phonetic:"a.ne",category:"time",gender:"f",level:"A1",emoji:"🗓️"},
  {id:"a1_244",word:"matin",article:"un",translation_tr:"sabah",translation_en:"morning",phonetic:"ma.tɛ̃",category:"time",gender:"m",level:"A1",emoji:"🌅"},
  {id:"a1_245",word:"après-midi",article:"un",translation_tr:"öğleden sonra",translation_en:"afternoon",phonetic:"a.pʁɛ mi.di",category:"time",gender:"m",level:"A1",emoji:"🌤️"},
  {id:"a1_246",word:"soir",article:"un",translation_tr:"akşam",translation_en:"evening",phonetic:"swaʁ",category:"time",gender:"m",level:"A1",emoji:"🌆"},
  {id:"a1_247",word:"nuit",article:"une",translation_tr:"gece",translation_en:"night",phonetic:"nɥi",category:"time",gender:"f",level:"A1",emoji:"🌙"},
  {id:"a1_248",word:"aujourd'hui",article:"",translation_tr:"bugün",translation_en:"today",phonetic:"o.ʒuʁ.dɥi",category:"time",gender:"v",level:"A1",emoji:"📅"},
  {id:"a1_249",word:"demain",article:"",translation_tr:"yarın",translation_en:"tomorrow",phonetic:"də.mɛ̃",category:"time",gender:"v",level:"A1",emoji:"➡️"},
  {id:"a1_250",word:"hier",article:"",translation_tr:"dün",translation_en:"yesterday",phonetic:"jɛʁ",category:"time",gender:"v",level:"A1",emoji:"⬅️"},
  {id:"a1_251",word:"maintenant",article:"",translation_tr:"şimdi",translation_en:"now",phonetic:"mɛ̃.tə.nɑ̃",category:"time",gender:"v",level:"A1",emoji:"⏰"},
  {id:"a1_252",word:"lundi",article:"un",translation_tr:"pazartesi",translation_en:"Monday",phonetic:"lœ̃.di",category:"time",gender:"m",level:"A1",emoji:"📅"},
  {id:"a1_253",word:"mardi",article:"un",translation_tr:"salı",translation_en:"Tuesday",phonetic:"maʁ.di",category:"time",gender:"m",level:"A1",emoji:"📅"},
  {id:"a1_254",word:"mercredi",article:"un",translation_tr:"çarşamba",translation_en:"Wednesday",phonetic:"mɛʁ.kʁə.di",category:"time",gender:"m",level:"A1",emoji:"📅"},
  {id:"a1_255",word:"jeudi",article:"un",translation_tr:"perşembe",translation_en:"Thursday",phonetic:"ʒø.di",category:"time",gender:"m",level:"A1",emoji:"📅"},
  {id:"a1_256",word:"vendredi",article:"un",translation_tr:"cuma",translation_en:"Friday",phonetic:"vɑ̃.dʁə.di",category:"time",gender:"m",level:"A1",emoji:"📅"},
  {id:"a1_257",word:"samedi",article:"un",translation_tr:"cumartesi",translation_en:"Saturday",phonetic:"sam.di",category:"time",gender:"m",level:"A1",emoji:"📅"},
  {id:"a1_258",word:"dimanche",article:"un",translation_tr:"pazar",translation_en:"Sunday",phonetic:"di.mɑ̃ʃ",category:"time",gender:"m",level:"A1",emoji:"📅"},
  {id:"a1_259",word:"janvier",article:"un",translation_tr:"ocak",translation_en:"January",phonetic:"ʒɑ̃.vje",category:"time",gender:"m",level:"A1",emoji:"❄️"},
  {id:"a1_260",word:"février",article:"un",translation_tr:"şubat",translation_en:"February",phonetic:"fe.vʁje",category:"time",gender:"m",level:"A1",emoji:"❤️"},
  {id:"a1_261",word:"mars",article:"un",translation_tr:"mart",translation_en:"March",phonetic:"maʁs",category:"time",gender:"m",level:"A1",emoji:"🌱"},
  {id:"a1_262",word:"avril",article:"un",translation_tr:"nisan",translation_en:"April",phonetic:"a.vʁil",category:"time",gender:"m",level:"A1",emoji:"🌸"},
  {id:"a1_263",word:"mai",article:"un",translation_tr:"mayıs",translation_en:"May",phonetic:"mɛ",category:"time",gender:"m",level:"A1",emoji:"🌷"},
  {id:"a1_264",word:"juin",article:"un",translation_tr:"haziran",translation_en:"June",phonetic:"ʒɥɛ̃",category:"time",gender:"m",level:"A1",emoji:"☀️"},
  {id:"a1_265",word:"juillet",article:"un",translation_tr:"temmuz",translation_en:"July",phonetic:"ʒɥi.jɛ",category:"time",gender:"m",level:"A1",emoji:"🌞"},

  // ─── SAYILAR & MİKTAR (20) ───
  {id:"a1_266",word:"zéro",article:"",translation_tr:"sıfır",translation_en:"zero",phonetic:"ze.ʁo",category:"numbers",gender:"v",level:"A1",emoji:"0️⃣"},
  {id:"a1_267",word:"un",article:"",translation_tr:"bir",translation_en:"one",phonetic:"œ̃",category:"numbers",gender:"v",level:"A1",emoji:"1️⃣"},
  {id:"a1_268",word:"deux",article:"",translation_tr:"iki",translation_en:"two",phonetic:"dø",category:"numbers",gender:"v",level:"A1",emoji:"2️⃣"},
  {id:"a1_269",word:"trois",article:"",translation_tr:"üç",translation_en:"three",phonetic:"tʁwa",category:"numbers",gender:"v",level:"A1",emoji:"3️⃣"},
  {id:"a1_270",word:"quatre",article:"",translation_tr:"dört",translation_en:"four",phonetic:"katʁ",category:"numbers",gender:"v",level:"A1",emoji:"4️⃣"},
  {id:"a1_271",word:"cinq",article:"",translation_tr:"beş",translation_en:"five",phonetic:"sɛ̃k",category:"numbers",gender:"v",level:"A1",emoji:"5️⃣"},
  {id:"a1_272",word:"six",article:"",translation_tr:"altı",translation_en:"six",phonetic:"sis",category:"numbers",gender:"v",level:"A1",emoji:"6️⃣"},
  {id:"a1_273",word:"sept",article:"",translation_tr:"yedi",translation_en:"seven",phonetic:"sɛt",category:"numbers",gender:"v",level:"A1",emoji:"7️⃣"},
  {id:"a1_274",word:"huit",article:"",translation_tr:"sekiz",translation_en:"eight",phonetic:"ɥit",category:"numbers",gender:"v",level:"A1",emoji:"8️⃣"},
  {id:"a1_275",word:"neuf",article:"",translation_tr:"dokuz",translation_en:"nine",phonetic:"nœf",category:"numbers",gender:"v",level:"A1",emoji:"9️⃣"},
  {id:"a1_276",word:"dix",article:"",translation_tr:"on",translation_en:"ten",phonetic:"dis",category:"numbers",gender:"v",level:"A1",emoji:"🔟"},
  {id:"a1_277",word:"vingt",article:"",translation_tr:"yirmi",translation_en:"twenty",phonetic:"vɛ̃",category:"numbers",gender:"v",level:"A1",emoji:"2️⃣0️⃣"},
  {id:"a1_278",word:"trente",article:"",translation_tr:"otuz",translation_en:"thirty",phonetic:"tʁɑ̃t",category:"numbers",gender:"v",level:"A1",emoji:"3️⃣0️⃣"},
  {id:"a1_279",word:"cent",article:"",translation_tr:"yüz",translation_en:"hundred",phonetic:"sɑ̃",category:"numbers",gender:"v",level:"A1",emoji:"💯"},
  {id:"a1_280",word:"mille",article:"",translation_tr:"bin",translation_en:"thousand",phonetic:"mil",category:"numbers",gender:"v",level:"A1",emoji:"🔢"},
  {id:"a1_281",word:"premier",article:"",translation_tr:"birinci / ilk",translation_en:"first",phonetic:"pʁə.mje",category:"numbers",gender:"v",level:"A1",emoji:"🥇"},
  {id:"a1_282",word:"dernier",article:"",translation_tr:"son / sonuncu",translation_en:"last",phonetic:"dɛʁ.nje",category:"numbers",gender:"v",level:"A1",emoji:"🏁"},
  {id:"a1_283",word:"beaucoup",article:"",translation_tr:"çok (miktar)",translation_en:"a lot/much",phonetic:"bo.ku",category:"numbers",gender:"v",level:"A1",emoji:"📊"},
  {id:"a1_284",word:"peu",article:"",translation_tr:"az / biraz",translation_en:"a little/few",phonetic:"pø",category:"numbers",gender:"v",level:"A1",emoji:"🔽"},
  {id:"a1_285",word:"assez",article:"",translation_tr:"yeterince",translation_en:"enough",phonetic:"a.se",category:"numbers",gender:"v",level:"A1",emoji:"✅"},

  // ─── İŞ & EĞİTİM (25) ───
  {id:"a1_286",word:"travail",article:"un",translation_tr:"iş",translation_en:"work/job",phonetic:"tʁa.vaj",category:"work",gender:"m",level:"A1",emoji:"💼"},
  {id:"a1_287",word:"bureau",article:"un",translation_tr:"ofis / büro",translation_en:"office",phonetic:"by.ʁo",category:"work",gender:"m",level:"A1",emoji:"🏢"},
  {id:"a1_288",word:"entreprise",article:"une",translation_tr:"şirket / işletme",translation_en:"company",phonetic:"ɑ̃.tʁə.pʁiz",category:"work",gender:"f",level:"A1",emoji:"🏢"},
  {id:"a1_289",word:"collègue",article:"un",translation_tr:"iş arkadaşı",translation_en:"colleague",phonetic:"kɔ.lɛɡ",category:"work",gender:"m",level:"A1",emoji:"👥"},
  {id:"a1_290",word:"patron",article:"un",translation_tr:"patron / işveren",translation_en:"boss",phonetic:"pa.tʁɔ̃",category:"work",gender:"m",level:"A1",emoji:"👔"},
  {id:"a1_291",word:"réunion",article:"une",translation_tr:"toplantı",translation_en:"meeting",phonetic:"ʁe.y.njɔ̃",category:"work",gender:"f",level:"A1",emoji:"🤝"},
  {id:"a1_292",word:"rendez-vous",article:"un",translation_tr:"randevu",translation_en:"appointment",phonetic:"ʁɑ̃.de.vu",category:"work",gender:"m",level:"A1",emoji:"📅"},
  {id:"a1_293",word:"salaire",article:"un",translation_tr:"maaş",translation_en:"salary",phonetic:"sa.lɛʁ",category:"work",gender:"m",level:"A1",emoji:"💰"},
  {id:"a1_294",word:"métier",article:"un",translation_tr:"meslek",translation_en:"profession",phonetic:"me.tje",category:"work",gender:"m",level:"A1",emoji:"🔧"},
  {id:"a1_295",word:"profession",article:"une",translation_tr:"meslek / profesyon",translation_en:"profession",phonetic:"pʁɔ.fɛ.sjɔ̃",category:"work",gender:"f",level:"A1",emoji:"💼"},
  {id:"a1_296",word:"classe",article:"une",translation_tr:"sınıf",translation_en:"class/classroom",phonetic:"klas",category:"education",gender:"f",level:"A1",emoji:"🏫"},
  {id:"a1_297",word:"cours",article:"un",translation_tr:"ders",translation_en:"lesson/course",phonetic:"kuʁ",category:"education",gender:"m",level:"A1",emoji:"📝"},
  {id:"a1_298",word:"leçon",article:"une",translation_tr:"ders",translation_en:"lesson",phonetic:"lə.sɔ̃",category:"education",gender:"f",level:"A1",emoji:"📖"},
  {id:"a1_299",word:"professeur",article:"un",translation_tr:"öğretmen",translation_en:"teacher",phonetic:"pʁɔ.fɛ.sœʁ",category:"education",gender:"m",level:"A1",emoji:"👨‍🏫"},
  {id:"a1_300",word:"élève",article:"un",translation_tr:"öğrenci (ilk/ortaokul)",translation_en:"pupil",phonetic:"e.lɛv",category:"education",gender:"m",level:"A1",emoji:"🧑‍🎓"},
  {id:"a1_301",word:"étudiant",article:"un",translation_tr:"öğrenci (üniversite)",translation_en:"student",phonetic:"e.ty.djɑ̃",category:"education",gender:"m",level:"A1",emoji:"🎓"},
  {id:"a1_302",word:"livre",article:"un",translation_tr:"kitap",translation_en:"book",phonetic:"livʁ",category:"education",gender:"m",level:"A1",emoji:"📚"},
  {id:"a1_303",word:"cahier",article:"un",translation_tr:"defter",translation_en:"notebook",phonetic:"ka.je",category:"education",gender:"m",level:"A1",emoji:"📓"},
  {id:"a1_304",word:"stylo",article:"un",translation_tr:"kalem (tükenmez)",translation_en:"pen",phonetic:"sti.lo",category:"education",gender:"m",level:"A1",emoji:"🖊️"},
  {id:"a1_305",word:"crayon",article:"un",translation_tr:"kalem (kurşun)",translation_en:"pencil",phonetic:"kʁɛ.jɔ̃",category:"education",gender:"m",level:"A1",emoji:"✏️"},
  {id:"a1_306",word:"dictionnaire",article:"un",translation_tr:"sözlük",translation_en:"dictionary",phonetic:"dik.sjɔ.nɛʁ",category:"education",gender:"m",level:"A1",emoji:"📖"},
  {id:"a1_307",word:"exercice",article:"un",translation_tr:"alıştırma / egzersiz",translation_en:"exercise",phonetic:"ɛɡ.zɛʁ.sis",category:"education",gender:"m",level:"A1",emoji:"📝"},
  {id:"a1_308",word:"devoir",article:"un",translation_tr:"ödev",translation_en:"homework",phonetic:"də.vwaʁ",category:"education",gender:"m",level:"A1",emoji:"📋"},
  {id:"a1_309",word:"examen",article:"un",translation_tr:"sınav",translation_en:"exam",phonetic:"ɛɡ.za.mɛ̃",category:"education",gender:"m",level:"A1",emoji:"📝"},
  {id:"a1_310",word:"question",article:"une",translation_tr:"soru",translation_en:"question",phonetic:"kɛs.tjɔ̃",category:"education",gender:"f",level:"A1",emoji:"❓"},

  // ─── HOBİLER & BOŞ ZAMAN (20) ───
  {id:"a1_311",word:"sport",article:"un",translation_tr:"spor",translation_en:"sport",phonetic:"spɔʁ",category:"hobbies",gender:"m",level:"A1",emoji:"⚽"},
  {id:"a1_312",word:"football",article:"un",translation_tr:"futbol",translation_en:"football",phonetic:"fut.bol",category:"hobbies",gender:"m",level:"A1",emoji:"⚽"},
  {id:"a1_313",word:"tennis",article:"un",translation_tr:"tenis",translation_en:"tennis",phonetic:"tɛ.nis",category:"hobbies",gender:"m",level:"A1",emoji:"🎾"},
  {id:"a1_314",word:"natation",article:"une",translation_tr:"yüzme",translation_en:"swimming",phonetic:"na.ta.sjɔ̃",category:"hobbies",gender:"f",level:"A1",emoji:"🏊"},
  {id:"a1_315",word:"musique",article:"une",translation_tr:"müzik",translation_en:"music",phonetic:"my.zik",category:"hobbies",gender:"f",level:"A1",emoji:"🎵"},
  {id:"a1_316",word:"danse",article:"une",translation_tr:"dans",translation_en:"dance",phonetic:"dɑ̃s",category:"hobbies",gender:"f",level:"A1",emoji:"💃"},
  {id:"a1_317",word:"film",article:"un",translation_tr:"film",translation_en:"film/movie",phonetic:"film",category:"hobbies",gender:"m",level:"A1",emoji:"🎬"},
  {id:"a1_318",word:"lecture",article:"une",translation_tr:"okuma",translation_en:"reading",phonetic:"lɛk.tyʁ",category:"hobbies",gender:"f",level:"A1",emoji:"📖"},
  {id:"a1_319",word:"voyage",article:"un",translation_tr:"seyahat",translation_en:"travel",phonetic:"vwa.jaʒ",category:"hobbies",gender:"m",level:"A1",emoji:"✈️"},
  {id:"a1_320",word:"vacances",article:"des",translation_tr:"tatil",translation_en:"holidays",phonetic:"va.kɑ̃s",category:"hobbies",gender:"f",level:"A1",emoji:"🏖️"},
  {id:"a1_321",word:"photographie",article:"une",translation_tr:"fotoğraf / fotoğrafçılık",translation_en:"photography",phonetic:"fɔ.tɔ.ɡʁa.fi",category:"hobbies",gender:"f",level:"A1",emoji:"📸"},
  {id:"a1_322",word:"dessin",article:"un",translation_tr:"çizim / resim",translation_en:"drawing",phonetic:"dɛ.sɛ̃",category:"hobbies",gender:"m",level:"A1",emoji:"🎨"},
  {id:"a1_323",word:"peinture",article:"une",translation_tr:"resim yapma / boya",translation_en:"painting",phonetic:"pɛ̃.tyʁ",category:"hobbies",gender:"f",level:"A1",emoji:"🖼️"},
  {id:"a1_324",word:"cuisine",article:"une",translation_tr:"yemek pişirme",translation_en:"cooking",phonetic:"kɥi.zin",category:"hobbies",gender:"f",level:"A1",emoji:"👨‍🍳"},
  {id:"a1_325",word:"jardinage",article:"un",translation_tr:"bahçecilik",translation_en:"gardening",phonetic:"ʒaʁ.di.naʒ",category:"hobbies",gender:"m",level:"A1",emoji:"🌱"},
  {id:"a1_326",word:"jeu",article:"un",translation_tr:"oyun",translation_en:"game",phonetic:"ʒø",category:"hobbies",gender:"m",level:"A1",emoji:"🎮"},
  {id:"a1_327",word:"promenade",article:"une",translation_tr:"yürüyüş / gezinti",translation_en:"walk/stroll",phonetic:"pʁɔm.nad",category:"hobbies",gender:"f",level:"A1",emoji:"🚶"},
  {id:"a1_328",word:"concert",article:"un",translation_tr:"konser",translation_en:"concert",phonetic:"kɔ̃.sɛʁ",category:"hobbies",gender:"m",level:"A1",emoji:"🎸"},
  {id:"a1_329",word:"spectacle",article:"un",translation_tr:"gösteri",translation_en:"show/performance",phonetic:"spɛk.takl",category:"hobbies",gender:"m",level:"A1",emoji:"🎭"},
  {id:"a1_330",word:"exposition",article:"une",translation_tr:"sergi",translation_en:"exhibition",phonetic:"ɛks.po.zi.sjɔ̃",category:"hobbies",gender:"f",level:"A1",emoji:"🖼️"},

  // ─── HAYVANLAR (15) ───
  {id:"a1_331",word:"chat",article:"un",translation_tr:"kedi",translation_en:"cat",phonetic:"ʃa",category:"animals",gender:"m",level:"A1",emoji:"🐱"},
  {id:"a1_332",word:"chien",article:"un",translation_tr:"köpek",translation_en:"dog",phonetic:"ʃjɛ̃",category:"animals",gender:"m",level:"A1",emoji:"🐶"},
  {id:"a1_333",word:"oiseau",article:"un",translation_tr:"kuş",translation_en:"bird",phonetic:"wa.zo",category:"animals",gender:"m",level:"A1",emoji:"🐦"},
  {id:"a1_334",word:"poisson",article:"un",translation_tr:"balık",translation_en:"fish",phonetic:"pwa.sɔ̃",category:"animals",gender:"m",level:"A1",emoji:"🐟"},
  {id:"a1_335",word:"cheval",article:"un",translation_tr:"at",translation_en:"horse",phonetic:"ʃə.val",category:"animals",gender:"m",level:"A1",emoji:"🐴"},
  {id:"a1_336",word:"vache",article:"une",translation_tr:"inek",translation_en:"cow",phonetic:"vaʃ",category:"animals",gender:"f",level:"A1",emoji:"🐄"},
  {id:"a1_337",word:"mouton",article:"un",translation_tr:"koyun",translation_en:"sheep",phonetic:"mu.tɔ̃",category:"animals",gender:"m",level:"A1",emoji:"🐑"},
  {id:"a1_338",word:"cochon",article:"un",translation_tr:"domuz",translation_en:"pig",phonetic:"kɔ.ʃɔ̃",category:"animals",gender:"m",level:"A1",emoji:"🐷"},
  {id:"a1_339",word:"lapin",article:"un",translation_tr:"tavşan",translation_en:"rabbit",phonetic:"la.pɛ̃",category:"animals",gender:"m",level:"A1",emoji:"🐰"},
  {id:"a1_340",word:"lion",article:"un",translation_tr:"aslan",translation_en:"lion",phonetic:"ljɔ̃",category:"animals",gender:"m",level:"A1",emoji:"🦁"},
  {id:"a1_341",word:"tigre",article:"un",translation_tr:"kaplan",translation_en:"tiger",phonetic:"tiɡʁ",category:"animals",gender:"m",level:"A1",emoji:"🐯"},
  {id:"a1_342",word:"éléphant",article:"un",translation_tr:"fil",translation_en:"elephant",phonetic:"e.le.fɑ̃",category:"animals",gender:"m",level:"A1",emoji:"🐘"},
  {id:"a1_343",word:"singe",article:"un",translation_tr:"maymun",translation_en:"monkey",phonetic:"sɛ̃ʒ",category:"animals",gender:"m",level:"A1",emoji:"🐵"},
  {id:"a1_344",word:"serpent",article:"un",translation_tr:"yılan",translation_en:"snake",phonetic:"sɛʁ.pɑ̃",category:"animals",gender:"m",level:"A1",emoji:"🐍"},
  {id:"a1_345",word:"insecte",article:"un",translation_tr:"böcek",translation_en:"insect",phonetic:"ɛ̃.sɛkt",category:"animals",gender:"m",level:"A1",emoji:"🐛"},

  // ─── NESNELER & EŞYALAR (25) ───
  {id:"a1_346",word:"stylo",article:"un",translation_tr:"kalem",translation_en:"pen",phonetic:"sti.lo",category:"objects",gender:"m",level:"A1",emoji:"🖊️"},
  {id:"a1_347",word:"papier",article:"un",translation_tr:"kağıt",translation_en:"paper",phonetic:"pa.pje",category:"objects",gender:"m",level:"A1",emoji:"📄"},
  {id:"a1_348",word:"enveloppe",article:"une",translation_tr:"zarf",translation_en:"envelope",phonetic:"ɑ̃.və.lɔp",category:"objects",gender:"f",level:"A1",emoji:"✉️"},
  {id:"a1_349",word:"timbre",article:"un",translation_tr:"pul",translation_en:"stamp",phonetic:"tɛ̃bʁ",category:"objects",gender:"m",level:"A1",emoji:"📮"},
  {id:"a1_350",word:"journal",article:"un",translation_tr:"gazete",translation_en:"newspaper",phonetic:"ʒuʁ.nal",category:"objects",gender:"m",level:"A1",emoji:"📰"},
  {id:"a1_351",word:"magazine",article:"un",translation_tr:"dergi",translation_en:"magazine",phonetic:"ma.ɡa.zin",category:"objects",gender:"m",level:"A1",emoji:"📔"},
  {id:"a1_352",word:"argent",article:"un",translation_tr:"para / gümüş",translation_en:"money/silver",phonetic:"aʁ.ʒɑ̃",category:"objects",gender:"m",level:"A1",emoji:"💰"},
  {id:"a1_353",word:"carte",article:"une",translation_tr:"kart / harita",translation_en:"card/map",phonetic:"kaʁt",category:"objects",gender:"f",level:"A1",emoji:"🗺️"},
  {id:"a1_354",word:"photo",article:"une",translation_tr:"fotoğraf",translation_en:"photo",phonetic:"fo.to",category:"objects",gender:"f",level:"A1",emoji:"📸"},
  {id:"a1_355",word:"appareil photo",article:"un",translation_tr:"fotoğraf makinesi",translation_en:"camera",phonetic:"a.pa.ʁɛj fo.to",category:"objects",gender:"m",level:"A1",emoji:"📷"},
  {id:"a1_356",word:"téléphone portable",article:"un",translation_tr:"cep telefonu",translation_en:"mobile phone",phonetic:"te.le.fɔn pɔʁ.tabl",category:"objects",gender:"m",level:"A1",emoji:"📱"},
  {id:"a1_357",word:"horloge",article:"une",translation_tr:"duvar saati",translation_en:"clock",phonetic:"ɔʁ.lɔʒ",category:"objects",gender:"f",level:"A1",emoji:"🕐"},
  {id:"a1_358",word:"miroir",article:"un",translation_tr:"ayna",translation_en:"mirror",phonetic:"mi.ʁwaʁ",category:"objects",gender:"m",level:"A1",emoji:"🪞"},
  {id:"a1_359",word:"brosse à dents",article:"une",translation_tr:"diş fırçası",translation_en:"toothbrush",phonetic:"bʁɔs a dɑ̃",category:"objects",gender:"f",level:"A1",emoji:"🪥"},
  {id:"a1_360",word:"savon",article:"un",translation_tr:"sabun",translation_en:"soap",phonetic:"sa.vɔ̃",category:"objects",gender:"m",level:"A1",emoji:"🧼"},
  {id:"a1_361",word:"serviette",article:"une",translation_tr:"havlu",translation_en:"towel",phonetic:"sɛʁ.vjɛt",category:"objects",gender:"f",level:"A1",emoji:"🧺"},
  {id:"a1_362",word:"parapluie",article:"un",translation_tr:"şemsiye",translation_en:"umbrella",phonetic:"pa.ʁa.plɥi",category:"objects",gender:"m",level:"A1",emoji:"☂️"},
  {id:"a1_363",word:"fleur",article:"une",translation_tr:"çiçek",translation_en:"flower",phonetic:"flœʁ",category:"objects",gender:"f",level:"A1",emoji:"🌸"},
  {id:"a1_364",word:"cadeau",article:"un",translation_tr:"hediye",translation_en:"gift",phonetic:"ka.do",category:"objects",gender:"m",level:"A1",emoji:"🎁"},
  {id:"a1_365",word:"valise",article:"une",translation_tr:"bavul",translation_en:"suitcase",phonetic:"va.liz",category:"objects",gender:"f",level:"A1",emoji:"🧳"},
  {id:"a1_366",word:"clé",article:"une",translation_tr:"anahtar",translation_en:"key",phonetic:"kle",category:"objects",gender:"f",level:"A1",emoji:"🔑"},
  {id:"a1_367",word:"lampe",article:"une",translation_tr:"lamba",translation_en:"lamp",phonetic:"lɑ̃p",category:"objects",gender:"f",level:"A1",emoji:"💡"},
  {id:"a1_368",word:"bouteille",article:"une",translation_tr:"şişe",translation_en:"bottle",phonetic:"bu.tɛj",category:"objects",gender:"f",level:"A1",emoji:"🍾"},
  {id:"a1_369",word:"verre",article:"un",translation_tr:"bardak / cam",translation_en:"glass",phonetic:"vɛʁ",category:"objects",gender:"m",level:"A1",emoji:"🥤"},
  {id:"a1_370",word:"assiette",article:"une",translation_tr:"tabak",translation_en:"plate",phonetic:"a.sjɛt",category:"objects",gender:"f",level:"A1",emoji:"🍽️"},

  // ─── SIFATLAR (30) ───
  {id:"a1_371",word:"grand",article:"",translation_tr:"büyük / uzun boylu",translation_en:"big/tall",phonetic:"ɡʁɑ̃",category:"adjectives",gender:"v",level:"A1",emoji:"⬆️"},
  {id:"a1_372",word:"petit",article:"",translation_tr:"küçük / kısa boylu",translation_en:"small/short",phonetic:"pə.ti",category:"adjectives",gender:"v",level:"A1",emoji:"⬇️"},
  {id:"a1_373",word:"beau",article:"",translation_tr:"güzel / yakışıklı",translation_en:"beautiful/handsome",phonetic:"bo",category:"adjectives",gender:"v",level:"A1",emoji:"😍"},
  {id:"a1_374",word:"joli",article:"",translation_tr:"güzel / şirin",translation_en:"pretty/nice",phonetic:"ʒɔ.li",category:"adjectives",gender:"v",level:"A1",emoji:"✨"},
  {id:"a1_375",word:"bon",article:"",translation_tr:"iyi / güzel (lezzet)",translation_en:"good",phonetic:"bɔ̃",category:"adjectives",gender:"v",level:"A1",emoji:"👍"},
  {id:"a1_376",word:"mauvais",article:"",translation_tr:"kötü",translation_en:"bad",phonetic:"mo.vɛ",category:"adjectives",gender:"v",level:"A1",emoji:"👎"},
  {id:"a1_377",word:"nouveau",article:"",translation_tr:"yeni",translation_en:"new",phonetic:"nu.vo",category:"adjectives",gender:"v",level:"A1",emoji:"🆕"},
  {id:"a1_378",word:"vieux",article:"",translation_tr:"eski / yaşlı",translation_en:"old",phonetic:"vjø",category:"adjectives",gender:"v",level:"A1",emoji:"👴"},
  {id:"a1_379",word:"jeune",article:"",translation_tr:"genç",translation_en:"young",phonetic:"ʒœn",category:"adjectives",gender:"v",level:"A1",emoji:"👦"},
  {id:"a1_380",word:"fort",article:"",translation_tr:"güçlü / kuvvetli",translation_en:"strong",phonetic:"fɔʁ",category:"adjectives",gender:"v",level:"A1",emoji:"💪"},
  {id:"a1_381",word:"faible",article:"",translation_tr:"zayıf",translation_en:"weak",phonetic:"fɛbl",category:"adjectives",gender:"v",level:"A1",emoji:"😔"},
  {id:"a1_382",word:"long",article:"",translation_tr:"uzun",translation_en:"long",phonetic:"lɔ̃",category:"adjectives",gender:"v",level:"A1",emoji:"📏"},
  {id:"a1_383",word:"court",article:"",translation_tr:"kısa",translation_en:"short",phonetic:"kuʁ",category:"adjectives",gender:"v",level:"A1",emoji:"📏"},
  {id:"a1_384",word:"large",article:"",translation_tr:"geniş",translation_en:"wide/broad",phonetic:"laʁʒ",category:"adjectives",gender:"v",level:"A1",emoji:"↔️"},
  {id:"a1_385",word:"étroit",article:"",translation_tr:"dar / ince",translation_en:"narrow",phonetic:"e.tʁwa",category:"adjectives",gender:"v",level:"A1",emoji:"↔️"},
  {id:"a1_386",word:"lourd",article:"",translation_tr:"ağır",translation_en:"heavy",phonetic:"luʁ",category:"adjectives",gender:"v",level:"A1",emoji:"⚖️"},
  {id:"a1_387",word:"léger",article:"",translation_tr:"hafif",translation_en:"light",phonetic:"le.ʒe",category:"adjectives",gender:"v",level:"A1",emoji:"🪶"},
  {id:"a1_388",word:"rapide",article:"",translation_tr:"hızlı",translation_en:"fast",phonetic:"ʁa.pid",category:"adjectives",gender:"v",level:"A1",emoji:"⚡"},
  {id:"a1_389",word:"lent",article:"",translation_tr:"yavaş",translation_en:"slow",phonetic:"lɑ̃",category:"adjectives",gender:"v",level:"A1",emoji:"🐢"},
  {id:"a1_390",word:"facile",article:"",translation_tr:"kolay",translation_en:"easy",phonetic:"fa.sil",category:"adjectives",gender:"v",level:"A1",emoji:"✅"},
  {id:"a1_391",word:"difficile",article:"",translation_tr:"zor / güç",translation_en:"difficult",phonetic:"di.fi.sil",category:"adjectives",gender:"v",level:"A1",emoji:"❗"},
  {id:"a1_392",word:"intéressant",article:"",translation_tr:"ilginç / ilgi çekici",translation_en:"interesting",phonetic:"ɛ̃.te.ʁɛ.sɑ̃",category:"adjectives",gender:"v",level:"A1",emoji:"🤩"},
  {id:"a1_393",word:"ennuyeux",article:"",translation_tr:"sıkıcı",translation_en:"boring",phonetic:"ɑ̃.nɥi.jø",category:"adjectives",gender:"v",level:"A1",emoji:"😴"},
  {id:"a1_394",word:"sympa",article:"",translation_tr:"sempatik / hoş",translation_en:"nice/friendly",phonetic:"sɛ̃.pa",category:"adjectives",gender:"v",level:"A1",emoji:"😊"},
  {id:"a1_395",word:"content",article:"",translation_tr:"mutlu / memnun",translation_en:"happy/pleased",phonetic:"kɔ̃.tɑ̃",category:"adjectives",gender:"v",level:"A1",emoji:"😊"},
  {id:"a1_396",word:"triste",article:"",translation_tr:"üzgün",translation_en:"sad",phonetic:"tʁist",category:"adjectives",gender:"v",level:"A1",emoji:"😢"},
  {id:"a1_397",word:"fatigué",article:"",translation_tr:"yorgun",translation_en:"tired",phonetic:"fa.ti.ɡe",category:"adjectives",gender:"v",level:"A1",emoji:"😴"},
  {id:"a1_398",word:"malade",article:"",translation_tr:"hasta",translation_en:"ill/sick",phonetic:"ma.lad",category:"adjectives",gender:"v",level:"A1",emoji:"🤒"},
  {id:"a1_399",word:"libre",article:"",translation_tr:"özgür / boş",translation_en:"free",phonetic:"libʁ",category:"adjectives",gender:"v",level:"A1",emoji:"🕊️"},
  {id:"a1_400",word:"occupé",article:"",translation_tr:"meşgul",translation_en:"busy",phonetic:"ɔ.ky.pe",category:"adjectives",gender:"v",level:"A1",emoji:"📋"},

  // ─── ZARFLAR & EDATLAR (30) ───
  {id:"a1_401",word:"ici",article:"",translation_tr:"burada",translation_en:"here",phonetic:"i.si",category:"adverbs",gender:"v",level:"A1",emoji:"📍"},
  {id:"a1_402",word:"là",article:"",translation_tr:"orada",translation_en:"there",phonetic:"la",category:"adverbs",gender:"v",level:"A1",emoji:"📍"},
  {id:"a1_403",word:"là-bas",article:"",translation_tr:"şurada / uzakta",translation_en:"over there",phonetic:"la ba",category:"adverbs",gender:"v",level:"A1",emoji:"👉"},
  {id:"a1_404",word:"devant",article:"",translation_tr:"önünde",translation_en:"in front of",phonetic:"də.vɑ̃",category:"adverbs",gender:"v",level:"A1",emoji:"⬆️"},
  {id:"a1_405",word:"derrière",article:"",translation_tr:"arkasında",translation_en:"behind",phonetic:"dɛ.ʁjɛʁ",category:"adverbs",gender:"v",level:"A1",emoji:"⬇️"},
  {id:"a1_406",word:"à côté de",article:"",translation_tr:"yanında",translation_en:"next to",phonetic:"a ko.te də",category:"adverbs",gender:"v",level:"A1",emoji:"↔️"},
  {id:"a1_407",word:"entre",article:"",translation_tr:"arasında",translation_en:"between",phonetic:"ɑ̃tʁ",category:"adverbs",gender:"v",level:"A1",emoji:"↔️"},
  {id:"a1_408",word:"sur",article:"",translation_tr:"üstünde",translation_en:"on/above",phonetic:"syʁ",category:"adverbs",gender:"v",level:"A1",emoji:"⬆️"},
  {id:"a1_409",word:"sous",article:"",translation_tr:"altında",translation_en:"under/below",phonetic:"su",category:"adverbs",gender:"v",level:"A1",emoji:"⬇️"},
  {id:"a1_410",word:"dans",article:"",translation_tr:"içinde",translation_en:"in/inside",phonetic:"dɑ̃",category:"adverbs",gender:"v",level:"A1",emoji:"📦"},
  {id:"a1_411",word:"en face de",article:"",translation_tr:"karşısında",translation_en:"opposite/facing",phonetic:"ɑ̃ fas də",category:"adverbs",gender:"v",level:"A1",emoji:"👁️"},
  {id:"a1_412",word:"près de",article:"",translation_tr:"yakınında",translation_en:"near/close to",phonetic:"pʁɛ də",category:"adverbs",gender:"v",level:"A1",emoji:"📍"},
  {id:"a1_413",word:"loin de",article:"",translation_tr:"uzağında",translation_en:"far from",phonetic:"lwɛ̃ də",category:"adverbs",gender:"v",level:"A1",emoji:"🗺️"},
  {id:"a1_414",word:"à gauche",article:"",translation_tr:"solda",translation_en:"on the left",phonetic:"a ɡoʃ",category:"adverbs",gender:"v",level:"A1",emoji:"⬅️"},
  {id:"a1_415",word:"à droite",article:"",translation_tr:"sağda",translation_en:"on the right",phonetic:"a dʁwat",category:"adverbs",gender:"v",level:"A1",emoji:"➡️"},
  {id:"a1_416",word:"tout droit",article:"",translation_tr:"düz / ileri",translation_en:"straight ahead",phonetic:"tu dʁwa",category:"adverbs",gender:"v",level:"A1",emoji:"⬆️"},
  {id:"a1_417",word:"vite",article:"",translation_tr:"hızlıca",translation_en:"quickly",phonetic:"vit",category:"adverbs",gender:"v",level:"A1",emoji:"⚡"},
  {id:"a1_418",word:"lentement",article:"",translation_tr:"yavaşça",translation_en:"slowly",phonetic:"lɑ̃t.mɑ̃",category:"adverbs",gender:"v",level:"A1",emoji:"🐢"},
  {id:"a1_419",word:"souvent",article:"",translation_tr:"sık sık",translation_en:"often",phonetic:"su.vɑ̃",category:"adverbs",gender:"v",level:"A1",emoji:"🔄"},
  {id:"a1_420",word:"toujours",article:"",translation_tr:"her zaman",translation_en:"always",phonetic:"tu.ʒuʁ",category:"adverbs",gender:"v",level:"A1",emoji:"♾️"},
  {id:"a1_421",word:"jamais",article:"",translation_tr:"hiçbir zaman",translation_en:"never",phonetic:"ʒa.mɛ",category:"adverbs",gender:"v",level:"A1",emoji:"🚫"},
  {id:"a1_422",word:"parfois",article:"",translation_tr:"bazen",translation_en:"sometimes",phonetic:"paʁ.fwa",category:"adverbs",gender:"v",level:"A1",emoji:"🔀"},
  {id:"a1_423",word:"encore",article:"",translation_tr:"hâlâ / yine",translation_en:"still/again",phonetic:"ɑ̃.kɔʁ",category:"adverbs",gender:"v",level:"A1",emoji:"🔁"},
  {id:"a1_424",word:"déjà",article:"",translation_tr:"zaten / artık",translation_en:"already",phonetic:"de.ʒa",category:"adverbs",gender:"v",level:"A1",emoji:"✅"},
  {id:"a1_425",word:"bientôt",article:"",translation_tr:"yakında",translation_en:"soon",phonetic:"bjɛ̃.to",category:"adverbs",gender:"v",level:"A1",emoji:"⏰"},
  {id:"a1_426",word:"enfin",article:"",translation_tr:"sonunda / nihayet",translation_en:"finally",phonetic:"ɑ̃.fɛ̃",category:"adverbs",gender:"v",level:"A1",emoji:"🎉"},
  {id:"a1_427",word:"ensemble",article:"",translation_tr:"birlikte",translation_en:"together",phonetic:"ɑ̃.sɑ̃bl",category:"adverbs",gender:"v",level:"A1",emoji:"👥"},
  {id:"a1_428",word:"seul",article:"",translation_tr:"yalnız / tek",translation_en:"alone",phonetic:"sœl",category:"adverbs",gender:"v",level:"A1",emoji:"🧍"},
  {id:"a1_429",word:"surtout",article:"",translation_tr:"özellikle",translation_en:"especially",phonetic:"syʁ.tu",category:"adverbs",gender:"v",level:"A1",emoji:"⭐"},
  {id:"a1_430",word:"vraiment",article:"",translation_tr:"gerçekten",translation_en:"really/truly",phonetic:"vʁɛ.mɑ̃",category:"adverbs",gender:"v",level:"A1",emoji:"💯"},

  // ─── BAĞLAÇLAR & İFADELER (20) ───
  {id:"a1_431",word:"et",article:"",translation_tr:"ve",translation_en:"and",phonetic:"e",category:"connectors",gender:"v",level:"A1",emoji:"➕"},
  {id:"a1_432",word:"ou",article:"",translation_tr:"veya",translation_en:"or",phonetic:"u",category:"connectors",gender:"v",level:"A1",emoji:"❓"},
  {id:"a1_433",word:"mais",article:"",translation_tr:"ama / fakat",translation_en:"but",phonetic:"mɛ",category:"connectors",gender:"v",level:"A1",emoji:"↩️"},
  {id:"a1_434",word:"donc",article:"",translation_tr:"o halde / demek ki",translation_en:"so/therefore",phonetic:"dɔ̃k",category:"connectors",gender:"v",level:"A1",emoji:"➡️"},
  {id:"a1_435",word:"parce que",article:"",translation_tr:"çünkü",translation_en:"because",phonetic:"paʁs kə",category:"connectors",gender:"v",level:"A1",emoji:"💡"},
  {id:"a1_436",word:"alors",article:"",translation_tr:"o zaman / peki",translation_en:"so/then",phonetic:"a.lɔʁ",category:"connectors",gender:"v",level:"A1",emoji:"➡️"},
  {id:"a1_437",word:"quand",article:"",translation_tr:"ne zaman / -dığında",translation_en:"when",phonetic:"kɑ̃",category:"connectors",gender:"v",level:"A1",emoji:"📅"},
  {id:"a1_438",word:"si",article:"",translation_tr:"eğer",translation_en:"if",phonetic:"si",category:"connectors",gender:"v",level:"A1",emoji:"❓"},
  {id:"a1_439",word:"comme",article:"",translation_tr:"gibi / çünkü",translation_en:"like/as",phonetic:"kɔm",category:"connectors",gender:"v",level:"A1",emoji:"🔄"},
  {id:"a1_440",word:"avec",article:"",translation_tr:"ile / birlikte",translation_en:"with",phonetic:"a.vɛk",category:"connectors",gender:"v",level:"A1",emoji:"🤝"},
  {id:"a1_441",word:"sans",article:"",translation_tr:"olmadan",translation_en:"without",phonetic:"sɑ̃",category:"connectors",gender:"v",level:"A1",emoji:"🚫"},
  {id:"a1_442",word:"pour",article:"",translation_tr:"için",translation_en:"for/in order to",phonetic:"puʁ",category:"connectors",gender:"v",level:"A1",emoji:"🎯"},
  {id:"a1_443",word:"après",article:"",translation_tr:"sonra",translation_en:"after",phonetic:"a.pʁɛ",category:"connectors",gender:"v",level:"A1",emoji:"➡️"},
  {id:"a1_444",word:"avant",article:"",translation_tr:"önce / daha önce",translation_en:"before",phonetic:"a.vɑ̃",category:"connectors",gender:"v",level:"A1",emoji:"⬅️"},
  {id:"a1_445",word:"pendant",article:"",translation_tr:"sırasında / boyunca",translation_en:"during/while",phonetic:"pɑ̃.dɑ̃",category:"connectors",gender:"v",level:"A1",emoji:"⏱️"},
  {id:"a1_446",word:"depuis",article:"",translation_tr:"-den beri / -dır",translation_en:"since/for",phonetic:"də.pɥi",category:"connectors",gender:"v",level:"A1",emoji:"⏳"},
  {id:"a1_447",word:"aussi",article:"",translation_tr:"de / da / ayrıca",translation_en:"also/too",phonetic:"o.si",category:"connectors",gender:"v",level:"A1",emoji:"➕"},
  {id:"a1_448",word:"très",article:"",translation_tr:"çok (sıfat için)",translation_en:"very",phonetic:"tʁɛ",category:"connectors",gender:"v",level:"A1",emoji:"⭐"},
  {id:"a1_449",word:"trop",article:"",translation_tr:"fazla / çok fazla",translation_en:"too/too much",phonetic:"tʁo",category:"connectors",gender:"v",level:"A1",emoji:"❗"},
  {id:"a1_450",word:"ne...pas",article:"",translation_tr:"...değil (olumsuzluk)",translation_en:"not",phonetic:"nə pa",category:"connectors",gender:"v",level:"A1",emoji:"🚫"},

  // ─── DUYGULAR & KİŞİLİK (20) ───
  {id:"a1_451",word:"amour",article:"un",translation_tr:"aşk / sevgi",translation_en:"love",phonetic:"a.muʁ",category:"emotions",gender:"m",level:"A1",emoji:"❤️"},
  {id:"a1_452",word:"joie",article:"une",translation_tr:"sevinç / neşe",translation_en:"joy",phonetic:"ʒwa",category:"emotions",gender:"f",level:"A1",emoji:"😊"},
  {id:"a1_453",word:"peur",article:"une",translation_tr:"korku",translation_en:"fear",phonetic:"pœʁ",category:"emotions",gender:"f",level:"A1",emoji:"😨"},
  {id:"a1_454",word:"colère",article:"une",translation_tr:"öfke",translation_en:"anger",phonetic:"kɔ.lɛʁ",category:"emotions",gender:"f",level:"A1",emoji:"😠"},
  {id:"a1_455",word:"surprise",article:"une",translation_tr:"sürpriz / şaşkınlık",translation_en:"surprise",phonetic:"syʁ.pʁiz",category:"emotions",gender:"f",level:"A1",emoji:"😲"},
  {id:"a1_456",word:"bonheur",article:"un",translation_tr:"mutluluk",translation_en:"happiness",phonetic:"bɔ.nœʁ",category:"emotions",gender:"m",level:"A1",emoji:"😄"},
  {id:"a1_457",word:"problème",article:"un",translation_tr:"sorun",translation_en:"problem",phonetic:"pʁɔ.blɛm",category:"emotions",gender:"m",level:"A1",emoji:"❗"},
  {id:"a1_458",word:"idée",article:"une",translation_tr:"fikir",translation_en:"idea",phonetic:"i.de",category:"emotions",gender:"f",level:"A1",emoji:"💡"},
  {id:"a1_459",word:"rêve",article:"un",translation_tr:"rüya / hayal",translation_en:"dream",phonetic:"ʁɛv",category:"emotions",gender:"m",level:"A1",emoji:"💭"},
  {id:"a1_460",word:"espoir",article:"un",translation_tr:"umut",translation_en:"hope",phonetic:"ɛs.pwaʁ",category:"emotions",gender:"m",level:"A1",emoji:"🌈"},
  {id:"a1_461",word:"gentil",article:"",translation_tr:"kibar / nazik",translation_en:"kind/nice",phonetic:"ʒɑ̃.ti",category:"emotions",gender:"v",level:"A1",emoji:"😊"},
  {id:"a1_462",word:"généreux",article:"",translation_tr:"cömert",translation_en:"generous",phonetic:"ʒe.ne.ʁø",category:"emotions",gender:"v",level:"A1",emoji:"🎁"},
  {id:"a1_463",word:"intelligent",article:"",translation_tr:"zeki / akıllı",translation_en:"intelligent",phonetic:"ɛ̃.tɛ.li.ʒɑ̃",category:"emotions",gender:"v",level:"A1",emoji:"🧠"},
  {id:"a1_464",word:"courageux",article:"",translation_tr:"cesur",translation_en:"brave",phonetic:"ku.ʁa.ʒø",category:"emotions",gender:"v",level:"A1",emoji:"💪"},
  {id:"a1_465",word:"timide",article:"",translation_tr:"utangaç",translation_en:"shy",phonetic:"ti.mid",category:"emotions",gender:"v",level:"A1",emoji:"😳"},
  {id:"a1_466",word:"drôle",article:"",translation_tr:"komik / eğlenceli",translation_en:"funny",phonetic:"dʁol",category:"emotions",gender:"v",level:"A1",emoji:"😂"},
  {id:"a1_467",word:"sérieux",article:"",translation_tr:"ciddi",translation_en:"serious",phonetic:"se.ʁjø",category:"emotions",gender:"v",level:"A1",emoji:"😐"},
  {id:"a1_468",word:"calme",article:"",translation_tr:"sakin",translation_en:"calm",phonetic:"kalm",category:"emotions",gender:"v",level:"A1",emoji:"😌"},
  {id:"a1_469",word:"poli",article:"",translation_tr:"kibar / nazik",translation_en:"polite",phonetic:"pɔ.li",category:"emotions",gender:"v",level:"A1",emoji:"🎩"},
  {id:"a1_470",word:"sympathique",article:"",translation_tr:"sempatik",translation_en:"likeable",phonetic:"sɛ̃.pa.tik",category:"emotions",gender:"v",level:"A1",emoji:"😊"},

  // ─── İLETİŞİM & MEDYA (15) ───
  {id:"a1_471",word:"mot",article:"un",translation_tr:"kelime / sözcük",translation_en:"word",phonetic:"mo",category:"communication",gender:"m",level:"A1",emoji:"📝"},
  {id:"a1_472",word:"phrase",article:"une",translation_tr:"cümle",translation_en:"sentence",phonetic:"fʁaz",category:"communication",gender:"f",level:"A1",emoji:"💬"},
  {id:"a1_473",word:"langue",article:"une",translation_tr:"dil",translation_en:"language",phonetic:"lɑ̃ɡ",category:"communication",gender:"f",level:"A1",emoji:"🗣️"},
  {id:"a1_474",word:"message",article:"un",translation_tr:"mesaj",translation_en:"message",phonetic:"mɛ.saʒ",category:"communication",gender:"m",level:"A1",emoji:"💬"},
  {id:"a1_475",word:"lettre",article:"une",translation_tr:"mektup / harf",translation_en:"letter",phonetic:"lɛtʁ",category:"communication",gender:"f",level:"A1",emoji:"✉️"},
  {id:"a1_476",word:"email",article:"un",translation_tr:"e-posta",translation_en:"email",phonetic:"i.mɛl",category:"communication",gender:"m",level:"A1",emoji:"📧"},
  {id:"a1_477",word:"internet",article:"un",translation_tr:"internet",translation_en:"internet",phonetic:"ɛ̃.tɛʁ.nɛt",category:"communication",gender:"m",level:"A1",emoji:"🌐"},
  {id:"a1_478",word:"site web",article:"un",translation_tr:"web sitesi",translation_en:"website",phonetic:"sit wɛb",category:"communication",gender:"m",level:"A1",emoji:"🌐"},
  {id:"a1_479",word:"radio",article:"une",translation_tr:"radyo",translation_en:"radio",phonetic:"ʁa.djo",category:"communication",gender:"f",level:"A1",emoji:"📻"},
  {id:"a1_480",word:"nouvelles",article:"des",translation_tr:"haberler",translation_en:"news",phonetic:"nu.vɛl",category:"communication",gender:"f",level:"A1",emoji:"📰"},
  {id:"a1_481",word:"information",article:"une",translation_tr:"bilgi / haber",translation_en:"information",phonetic:"ɛ̃.fɔʁ.ma.sjɔ̃",category:"communication",gender:"f",level:"A1",emoji:"ℹ️"},
  {id:"a1_482",word:"réponse",article:"une",translation_tr:"cevap / yanıt",translation_en:"answer/reply",phonetic:"ʁe.pɔ̃s",category:"communication",gender:"f",level:"A1",emoji:"💬"},
  {id:"a1_483",word:"conversation",article:"une",translation_tr:"konuşma / sohbet",translation_en:"conversation",phonetic:"kɔ̃.vɛʁ.sa.sjɔ̃",category:"communication",gender:"f",level:"A1",emoji:"💬"},
  {id:"a1_484",word:"histoire",article:"une",translation_tr:"hikaye / tarih",translation_en:"story/history",phonetic:"is.twaʁ",category:"communication",gender:"f",level:"A1",emoji:"📖"},
  {id:"a1_485",word:"chanson",article:"une",translation_tr:"şarkı",translation_en:"song",phonetic:"ʃɑ̃.sɔ̃",category:"communication",gender:"f",level:"A1",emoji:"🎵"},

  // ─── ALIŞVERIŞ & PARA (15) ───
  {id:"a1_486",word:"prix",article:"un",translation_tr:"fiyat",translation_en:"price",phonetic:"pʁi",category:"shopping",gender:"m",level:"A1",emoji:"💰"},
  {id:"a1_487",word:"euro",article:"un",translation_tr:"euro",translation_en:"euro",phonetic:"ø.ʁo",category:"shopping",gender:"m",level:"A1",emoji:"💶"},
  {id:"a1_488",word:"monnaie",article:"une",translation_tr:"bozuk para / üstü",translation_en:"change/coins",phonetic:"mɔ.nɛ",category:"shopping",gender:"f",level:"A1",emoji:"🪙"},
  {id:"a1_489",word:"achat",article:"un",translation_tr:"alım / satın alma",translation_en:"purchase",phonetic:"a.ʃa",category:"shopping",gender:"m",level:"A1",emoji:"🛒"},
  {id:"a1_490",word:"vente",article:"une",translation_tr:"satış",translation_en:"sale",phonetic:"vɑ̃t",category:"shopping",gender:"f",level:"A1",emoji:"🏷️"},
  {id:"a1_491",word:"soldes",article:"des",translation_tr:"indirim",translation_en:"sales/discounts",phonetic:"sɔld",category:"shopping",gender:"m",level:"A1",emoji:"🏷️"},
  {id:"a1_492",word:"caddie",article:"un",translation_tr:"alışveriş arabası",translation_en:"shopping cart",phonetic:"ka.di",category:"shopping",gender:"m",level:"A1",emoji:"🛒"},
  {id:"a1_493",word:"caisse",article:"une",translation_tr:"kasa",translation_en:"checkout/till",phonetic:"kɛs",category:"shopping",gender:"f",level:"A1",emoji:"💳"},
  {id:"a1_494",word:"carte bancaire",article:"une",translation_tr:"banka kartı",translation_en:"bank card",phonetic:"kaʁt bɑ̃.kɛʁ",category:"shopping",gender:"f",level:"A1",emoji:"💳"},
  {id:"a1_495",word:"reçu",article:"un",translation_tr:"makbuz / fiş",translation_en:"receipt",phonetic:"ʁə.sy",category:"shopping",gender:"m",level:"A1",emoji:"🧾"},
  {id:"a1_496",word:"vitrine",article:"une",translation_tr:"vitrin",translation_en:"shop window",phonetic:"vi.tʁin",category:"shopping",gender:"f",level:"A1",emoji:"🪟"},
  {id:"a1_497",word:"rayon",article:"un",translation_tr:"raf / bölüm",translation_en:"shelf/section",phonetic:"ʁɛ.jɔ̃",category:"shopping",gender:"m",level:"A1",emoji:"📦"},
  {id:"a1_498",word:"commande",article:"une",translation_tr:"sipariş",translation_en:"order",phonetic:"kɔ.mɑ̃d",category:"shopping",gender:"f",level:"A1",emoji:"📋"},
  {id:"a1_499",word:"livraison",article:"une",translation_tr:"teslimat",translation_en:"delivery",phonetic:"li.vʁɛ.zɔ̃",category:"shopping",gender:"f",level:"A1",emoji:"📦"},
  {id:"a1_500",word:"gratuit",article:"",translation_tr:"ücretsiz / bedava",translation_en:"free (no cost)",phonetic:"ɡʁa.tɥi",category:"shopping",gender:"v",level:"A1",emoji:"🆓"},

];
