const DATA_A2_WORDS = [
  // ─── İŞ & MESLEKLER (25) ───
  {id:"a2_001",word:"médecin",article:"un",translation_tr:"doktor",translation_en:"doctor",phonetic:"me.dsɛ̃",category:"work",gender:"m",level:"A2",emoji:"👨‍⚕️"},
  {id:"a2_002",word:"infirmier",article:"un",translation_tr:"hemşire (erkek)",translation_en:"nurse",phonetic:"ɛ̃.fiʁ.mje",category:"work",gender:"m",level:"A2",emoji:"🏥"},
  {id:"a2_003",word:"avocat",article:"un",translation_tr:"avukat",translation_en:"lawyer",phonetic:"a.vɔ.ka",category:"work",gender:"m",level:"A2",emoji:"⚖️"},
  {id:"a2_004",word:"architecte",article:"un",translation_tr:"mimar",translation_en:"architect",phonetic:"aʁ.ʃi.tɛkt",category:"work",gender:"m",level:"A2",emoji:"🏗️"},
  {id:"a2_005",word:"ingénieur",article:"un",translation_tr:"mühendis",translation_en:"engineer",phonetic:"ɛ̃.ʒe.njœʁ",category:"work",gender:"m",level:"A2",emoji:"⚙️"},
  {id:"a2_006",word:"comptable",article:"un",translation_tr:"muhasebeci",translation_en:"accountant",phonetic:"kɔ̃.tabl",category:"work",gender:"m",level:"A2",emoji:"💼"},
  {id:"a2_007",word:"vendeur",article:"un",translation_tr:"satıcı",translation_en:"salesperson",phonetic:"vɑ̃.dœʁ",category:"work",gender:"m",level:"A2",emoji:"🏪"},
  {id:"a2_008",word:"serveur",article:"un",translation_tr:"garson",translation_en:"waiter",phonetic:"sɛʁ.vœʁ",category:"work",gender:"m",level:"A2",emoji:"🍽️"},
  {id:"a2_009",word:"cuisinier",article:"un",translation_tr:"aşçı",translation_en:"cook",phonetic:"kɥi.zi.nje",category:"work",gender:"m",level:"A2",emoji:"👨‍🍳"},
  {id:"a2_010",word:"boulanger",article:"un",translation_tr:"fırıncı",translation_en:"baker",phonetic:"bu.lɑ̃.ʒe",category:"work",gender:"m",level:"A2",emoji:"🥖"},
  {id:"a2_011",word:"policier",article:"un",translation_tr:"polis",translation_en:"police officer",phonetic:"pɔ.li.sje",category:"work",gender:"m",level:"A2",emoji:"👮"},
  {id:"a2_012",word:"pompier",article:"un",translation_tr:"itfaiyeci",translation_en:"firefighter",phonetic:"pɔ̃.pje",category:"work",gender:"m",level:"A2",emoji:"🚒"},
  {id:"a2_013",word:"journaliste",article:"un",translation_tr:"gazeteci",translation_en:"journalist",phonetic:"ʒuʁ.na.list",category:"work",gender:"m",level:"A2",emoji:"📰"},
  {id:"a2_014",word:"acteur",article:"un",translation_tr:"oyuncu",translation_en:"actor",phonetic:"ak.tœʁ",category:"work",gender:"m",level:"A2",emoji:"🎭"},
  {id:"a2_015",word:"musicien",article:"un",translation_tr:"müzisyen",translation_en:"musician",phonetic:"my.zi.sjɛ̃",category:"work",gender:"m",level:"A2",emoji:"🎵"},
  {id:"a2_016",word:"directeur",article:"un",translation_tr:"müdür",translation_en:"director",phonetic:"di.ʁɛk.tœʁ",category:"work",gender:"m",level:"A2",emoji:"👔"},
  {id:"a2_017",word:"employé",article:"un",translation_tr:"çalışan",translation_en:"employee",phonetic:"ɑ̃.plwa.je",category:"work",gender:"m",level:"A2",emoji:"👷"},
  {id:"a2_018",word:"chômage",article:"un",translation_tr:"işsizlik",translation_en:"unemployment",phonetic:"ʃo.maʒ",category:"work",gender:"m",level:"A2",emoji:"📉"},
  {id:"a2_019",word:"contrat",article:"un",translation_tr:"sözleşme",translation_en:"contract",phonetic:"kɔ̃.tʁa",category:"work",gender:"m",level:"A2",emoji:"📄"},
  {id:"a2_020",word:"formation",article:"une",translation_tr:"eğitim / kurs",translation_en:"training",phonetic:"fɔʁ.ma.sjɔ̃",category:"work",gender:"f",level:"A2",emoji:"📚"},
  {id:"a2_021",word:"entretien",article:"un",translation_tr:"mülakat",translation_en:"interview",phonetic:"ɑ̃.tʁə.tjɛ̃",category:"work",gender:"m",level:"A2",emoji:"🤝"},
  {id:"a2_022",word:"candidature",article:"une",translation_tr:"başvuru",translation_en:"application",phonetic:"kɑ̃.di.da.tyʁ",category:"work",gender:"f",level:"A2",emoji:"📝"},
  {id:"a2_023",word:"salaire",article:"un",translation_tr:"maaş",translation_en:"salary",phonetic:"sa.lɛʁ",category:"work",gender:"m",level:"A2",emoji:"💰"},
  {id:"a2_024",word:"collègue",article:"un",translation_tr:"iş arkadaşı",translation_en:"colleague",phonetic:"kɔ.lɛɡ",category:"work",gender:"m",level:"A2",emoji:"👥"},
  {id:"a2_025",word:"patron",article:"un",translation_tr:"patron",translation_en:"boss",phonetic:"pa.tʁɔ̃",category:"work",gender:"m",level:"A2",emoji:"👔"},

  // ─── EĞİTİM (20) ───
  {id:"a2_026",word:"lycée",article:"un",translation_tr:"lise",translation_en:"high school",phonetic:"li.se",category:"education",gender:"m",level:"A2",emoji:"🏫"},
  {id:"a2_027",word:"diplôme",article:"un",translation_tr:"diploma",translation_en:"diploma",phonetic:"di.plom",category:"education",gender:"m",level:"A2",emoji:"🎓"},
  {id:"a2_028",word:"note",article:"une",translation_tr:"not / puan",translation_en:"grade",phonetic:"nɔt",category:"education",gender:"f",level:"A2",emoji:"📊"},
  {id:"a2_029",word:"moyenne",article:"une",translation_tr:"ortalama",translation_en:"average",phonetic:"mwa.jɛn",category:"education",gender:"f",level:"A2",emoji:"📊"},
  {id:"a2_030",word:"recherche",article:"une",translation_tr:"araştırma",translation_en:"research",phonetic:"ʁə.ʃɛʁʃ",category:"education",gender:"f",level:"A2",emoji:"🔍"},
  {id:"a2_031",word:"résumé",article:"un",translation_tr:"özet",translation_en:"summary",phonetic:"ʁe.zy.me",category:"education",gender:"m",level:"A2",emoji:"📝"},
  {id:"a2_032",word:"histoire",article:"une",translation_tr:"tarih",translation_en:"history",phonetic:"is.twaʁ",category:"education",gender:"f",level:"A2",emoji:"📜"},
  {id:"a2_033",word:"géographie",article:"une",translation_tr:"coğrafya",translation_en:"geography",phonetic:"ʒe.ɔ.ɡʁa.fi",category:"education",gender:"f",level:"A2",emoji:"🌍"},
  {id:"a2_034",word:"mathématiques",article:"des",translation_tr:"matematik",translation_en:"mathematics",phonetic:"ma.te.ma.tik",category:"education",gender:"f",level:"A2",emoji:"➗"},
  {id:"a2_035",word:"sciences",article:"des",translation_tr:"bilimler",translation_en:"sciences",phonetic:"sjɑ̃s",category:"education",gender:"f",level:"A2",emoji:"🔬"},
  {id:"a2_036",word:"littérature",article:"une",translation_tr:"edebiyat",translation_en:"literature",phonetic:"li.te.ʁa.tyʁ",category:"education",gender:"f",level:"A2",emoji:"📚"},
  {id:"a2_037",word:"faculté",article:"une",translation_tr:"fakülte",translation_en:"faculty",phonetic:"fa.kyl.te",category:"education",gender:"f",level:"A2",emoji:"🎓"},
  {id:"a2_038",word:"calcul",article:"un",translation_tr:"hesap",translation_en:"calculation",phonetic:"kal.kyl",category:"education",gender:"m",level:"A2",emoji:"🧮"},
  {id:"a2_039",word:"règle",article:"une",translation_tr:"kural / cetvel",translation_en:"rule/ruler",phonetic:"ʁɛɡl",category:"education",gender:"f",level:"A2",emoji:"📏"},
  {id:"a2_040",word:"tableau",article:"un",translation_tr:"tahta",translation_en:"board",phonetic:"ta.blo",category:"education",gender:"m",level:"A2",emoji:"📋"},
  {id:"a2_041",word:"examen",article:"un",translation_tr:"sınav",translation_en:"exam",phonetic:"ɛɡ.za.mɛ̃",category:"education",gender:"m",level:"A2",emoji:"📝"},
  {id:"a2_042",word:"exercice",article:"un",translation_tr:"alıştırma",translation_en:"exercise",phonetic:"ɛɡ.zɛʁ.sis",category:"education",gender:"m",level:"A2",emoji:"📝"},
  {id:"a2_043",word:"devoir",article:"un",translation_tr:"ödev",translation_en:"homework",phonetic:"də.vwaʁ",category:"education",gender:"m",level:"A2",emoji:"📋"},
  {id:"a2_044",word:"conférence",article:"une",translation_tr:"konferans",translation_en:"lecture",phonetic:"kɔ̃.fe.ʁɑ̃s",category:"education",gender:"f",level:"A2",emoji:"🎤"},
  {id:"a2_045",word:"économie",article:"une",translation_tr:"ekonomi",translation_en:"economics",phonetic:"e.kɔ.nɔ.mi",category:"education",gender:"f",level:"A2",emoji:"📈"},

  // ─── SAĞLIK (20) ───
  {id:"a2_046",word:"ordonnance",article:"une",translation_tr:"reçete",translation_en:"prescription",phonetic:"ɔʁ.dɔ.nɑ̃s",category:"health",gender:"f",level:"A2",emoji:"📋"},
  {id:"a2_047",word:"urgences",article:"des",translation_tr:"acil servis",translation_en:"emergency room",phonetic:"yʁ.ʒɑ̃s",category:"health",gender:"f",level:"A2",emoji:"🚑"},
  {id:"a2_048",word:"ambulance",article:"une",translation_tr:"ambulans",translation_en:"ambulance",phonetic:"ɑ̃.by.lɑ̃s",category:"health",gender:"f",level:"A2",emoji:"🚑"},
  {id:"a2_049",word:"blessure",article:"une",translation_tr:"yara",translation_en:"injury/wound",phonetic:"blɛ.syʁ",category:"health",gender:"f",level:"A2",emoji:"🩹"},
  {id:"a2_050",word:"fièvre",article:"une",translation_tr:"ateş (hastalık)",translation_en:"fever",phonetic:"fjɛvʁ",category:"health",gender:"f",level:"A2",emoji:"🤒"},
  {id:"a2_051",word:"rhume",article:"un",translation_tr:"nezle",translation_en:"cold",phonetic:"ʁym",category:"health",gender:"m",level:"A2",emoji:"🤧"},
  {id:"a2_052",word:"grippe",article:"une",translation_tr:"grip",translation_en:"flu",phonetic:"ɡʁip",category:"health",gender:"f",level:"A2",emoji:"🤒"},
  {id:"a2_053",word:"allergie",article:"une",translation_tr:"alerji",translation_en:"allergy",phonetic:"a.lɛʁ.ʒi",category:"health",gender:"f",level:"A2",emoji:"🤧"},
  {id:"a2_054",word:"régime",article:"un",translation_tr:"diyet",translation_en:"diet",phonetic:"ʁe.ʒim",category:"health",gender:"m",level:"A2",emoji:"🥗"},
  {id:"a2_055",word:"stress",article:"un",translation_tr:"stres",translation_en:"stress",phonetic:"stʁɛs",category:"health",gender:"m",level:"A2",emoji:"😰"},
  {id:"a2_056",word:"sommeil",article:"un",translation_tr:"uyku",translation_en:"sleep",phonetic:"sɔ.mɛj",category:"health",gender:"m",level:"A2",emoji:"😴"},
  {id:"a2_057",word:"repos",article:"un",translation_tr:"dinlenme",translation_en:"rest",phonetic:"ʁə.po",category:"health",gender:"m",level:"A2",emoji:"😴"},
  {id:"a2_058",word:"muscle",article:"un",translation_tr:"kas",translation_en:"muscle",phonetic:"myskl",category:"health",gender:"m",level:"A2",emoji:"💪"},
  {id:"a2_059",word:"sang",article:"un",translation_tr:"kan",translation_en:"blood",phonetic:"sɑ̃",category:"health",gender:"m",level:"A2",emoji:"🩸"},
  {id:"a2_060",word:"peau",article:"une",translation_tr:"deri / cilt",translation_en:"skin",phonetic:"po",category:"health",gender:"f",level:"A2",emoji:"🧴"},
  {id:"a2_061",word:"gorge",article:"une",translation_tr:"boğaz",translation_en:"throat",phonetic:"ɡɔʁʒ",category:"health",gender:"f",level:"A2",emoji:"😮"},
  {id:"a2_062",word:"dent",article:"une",translation_tr:"diş",translation_en:"tooth",phonetic:"dɑ̃",category:"health",gender:"f",level:"A2",emoji:"🦷"},
  {id:"a2_063",word:"dentiste",article:"un",translation_tr:"diş hekimi",translation_en:"dentist",phonetic:"dɑ̃.tist",category:"health",gender:"m",level:"A2",emoji:"🦷"},
  {id:"a2_064",word:"opération",article:"une",translation_tr:"ameliyat",translation_en:"operation",phonetic:"ɔ.pe.ʁa.sjɔ̃",category:"health",gender:"f",level:"A2",emoji:"🏥"},
  {id:"a2_065",word:"vitamine",article:"une",translation_tr:"vitamin",translation_en:"vitamin",phonetic:"vi.ta.min",category:"health",gender:"f",level:"A2",emoji:"💊"},

  // ─── EV & YAŞAM (20) ───
  {id:"a2_066",word:"loyer",article:"un",translation_tr:"kira",translation_en:"rent",phonetic:"lwa.je",category:"home",gender:"m",level:"A2",emoji:"🏠"},
  {id:"a2_067",word:"propriétaire",article:"un",translation_tr:"ev sahibi",translation_en:"landlord",phonetic:"pʁɔ.pʁje.tɛʁ",category:"home",gender:"m",level:"A2",emoji:"🔑"},
  {id:"a2_068",word:"locataire",article:"un",translation_tr:"kiracı",translation_en:"tenant",phonetic:"lɔ.ka.tɛʁ",category:"home",gender:"m",level:"A2",emoji:"🏠"},
  {id:"a2_069",word:"chauffage",article:"un",translation_tr:"ısıtma",translation_en:"heating",phonetic:"ʃo.faʒ",category:"home",gender:"m",level:"A2",emoji:"🔥"},
  {id:"a2_070",word:"ascenseur",article:"un",translation_tr:"asansör",translation_en:"lift/elevator",phonetic:"a.sɑ̃.sœʁ",category:"home",gender:"m",level:"A2",emoji:"🛗"},
  {id:"a2_071",word:"terrasse",article:"une",translation_tr:"teras",translation_en:"terrace",phonetic:"tɛ.ʁas",category:"home",gender:"f",level:"A2",emoji:"🌿"},
  {id:"a2_072",word:"balcon",article:"un",translation_tr:"balkon",translation_en:"balcony",phonetic:"bal.kɔ̃",category:"home",gender:"m",level:"A2",emoji:"🏠"},
  {id:"a2_073",word:"garage",article:"un",translation_tr:"garaj",translation_en:"garage",phonetic:"ɡa.ʁaʒ",category:"home",gender:"m",level:"A2",emoji:"🚗"},
  {id:"a2_074",word:"lave-linge",article:"un",translation_tr:"çamaşır makinesi",translation_en:"washing machine",phonetic:"lav lɛ̃ʒ",category:"home",gender:"m",level:"A2",emoji:"👕"},
  {id:"a2_075",word:"réfrigérateur",article:"un",translation_tr:"buzdolabı",translation_en:"fridge",phonetic:"ʁe.fʁi.ʒe.ʁa.tœʁ",category:"home",gender:"m",level:"A2",emoji:"🧊"},
  {id:"a2_076",word:"four",article:"un",translation_tr:"fırın",translation_en:"oven",phonetic:"fuʁ",category:"home",gender:"m",level:"A2",emoji:"🔥"},
  {id:"a2_077",word:"aspirateur",article:"un",translation_tr:"elektrik süpürgesi",translation_en:"vacuum cleaner",phonetic:"as.pi.ʁa.tœʁ",category:"home",gender:"m",level:"A2",emoji:"🧹"},
  {id:"a2_078",word:"poubelle",article:"une",translation_tr:"çöp kutusu",translation_en:"bin",phonetic:"pu.bɛl",category:"home",gender:"f",level:"A2",emoji:"🗑️"},
  {id:"a2_079",word:"déménagement",article:"un",translation_tr:"taşınma",translation_en:"moving house",phonetic:"de.me.naʒ.mɑ̃",category:"home",gender:"m",level:"A2",emoji:"📦"},
  {id:"a2_080",word:"électricité",article:"une",translation_tr:"elektrik",translation_en:"electricity",phonetic:"e.lɛk.tʁi.si.te",category:"home",gender:"f",level:"A2",emoji:"⚡"},
  {id:"a2_081",word:"robinet",article:"un",translation_tr:"musluk",translation_en:"tap/faucet",phonetic:"ʁɔ.bi.nɛ",category:"home",gender:"m",level:"A2",emoji:"🚰"},
  {id:"a2_082",word:"micro-ondes",article:"un",translation_tr:"mikrodalga",translation_en:"microwave",phonetic:"mi.kʁo ɔ̃d",category:"home",gender:"m",level:"A2",emoji:"📡"},
  {id:"a2_083",word:"cave",article:"une",translation_tr:"bodrum",translation_en:"cellar",phonetic:"kav",category:"home",gender:"f",level:"A2",emoji:"🏚️"},
  {id:"a2_084",word:"grenier",article:"un",translation_tr:"tavan arası",translation_en:"attic",phonetic:"ɡʁə.nje",category:"home",gender:"m",level:"A2",emoji:"🏠"},
  {id:"a2_085",word:"voisinage",article:"un",translation_tr:"komşuluk",translation_en:"neighbourhood",phonetic:"vwa.zi.naʒ",category:"home",gender:"m",level:"A2",emoji:"🏘️"},

  // ─── SEYAHAT & TURİZM (20) ───
  {id:"a2_086",word:"passeport",article:"un",translation_tr:"pasaport",translation_en:"passport",phonetic:"pas.pɔʁ",category:"travel",gender:"m",level:"A2",emoji:"🛂"},
  {id:"a2_087",word:"visa",article:"un",translation_tr:"vize",translation_en:"visa",phonetic:"vi.za",category:"travel",gender:"m",level:"A2",emoji:"📋"},
  {id:"a2_088",word:"douane",article:"une",translation_tr:"gümrük",translation_en:"customs",phonetic:"dwan",category:"travel",gender:"f",level:"A2",emoji:"🛃"},
  {id:"a2_089",word:"hébergement",article:"un",translation_tr:"konaklama",translation_en:"accommodation",phonetic:"e.bɛʁ.ʒə.mɑ̃",category:"travel",gender:"m",level:"A2",emoji:"🏨"},
  {id:"a2_090",word:"réception",article:"une",translation_tr:"resepsiyon",translation_en:"reception",phonetic:"ʁe.sɛp.sjɔ̃",category:"travel",gender:"f",level:"A2",emoji:"🏨"},
  {id:"a2_091",word:"camping",article:"un",translation_tr:"kamp",translation_en:"camping",phonetic:"kɑ̃.piŋ",category:"travel",gender:"m",level:"A2",emoji:"⛺"},
  {id:"a2_092",word:"excursion",article:"une",translation_tr:"gezi / tur",translation_en:"excursion",phonetic:"ɛks.kyʁ.sjɔ̃",category:"travel",gender:"f",level:"A2",emoji:"🗺️"},
  {id:"a2_093",word:"monument",article:"un",translation_tr:"anıt",translation_en:"monument",phonetic:"mɔ.ny.mɑ̃",category:"travel",gender:"m",level:"A2",emoji:"🗿"},
  {id:"a2_094",word:"château",article:"un",translation_tr:"şato / kale",translation_en:"castle",phonetic:"ʃa.to",category:"travel",gender:"m",level:"A2",emoji:"🏰"},
  {id:"a2_095",word:"souvenir",article:"un",translation_tr:"hatıra eşyası",translation_en:"souvenir",phonetic:"su.və.niʁ",category:"travel",gender:"m",level:"A2",emoji:"🎁"},
  {id:"a2_096",word:"frontière",article:"une",translation_tr:"sınır",translation_en:"border",phonetic:"fʁɔ̃.tjɛʁ",category:"travel",gender:"f",level:"A2",emoji:"🛂"},
  {id:"a2_097",word:"retard",article:"un",translation_tr:"gecikme",translation_en:"delay",phonetic:"ʁə.taʁ",category:"travel",gender:"m",level:"A2",emoji:"⏰"},
  {id:"a2_098",word:"annulation",article:"une",translation_tr:"iptal",translation_en:"cancellation",phonetic:"a.ny.la.sjɔ̃",category:"travel",gender:"f",level:"A2",emoji:"❌"},
  {id:"a2_099",word:"assurance",article:"une",translation_tr:"sigorta",translation_en:"insurance",phonetic:"a.sy.ʁɑ̃s",category:"travel",gender:"f",level:"A2",emoji:"🛡️"},
  {id:"a2_100",word:"correspondance",article:"une",translation_tr:"aktarma",translation_en:"connection",phonetic:"kɔ.ʁɛs.pɔ̃.dɑ̃s",category:"travel",gender:"f",level:"A2",emoji:"🔄"},
  {id:"a2_101",word:"croisière",article:"une",translation_tr:"gemi seyahati",translation_en:"cruise",phonetic:"kʁwa.zjɛʁ",category:"travel",gender:"f",level:"A2",emoji:"🚢"},
  {id:"a2_102",word:"office de tourisme",article:"un",translation_tr:"turizm bürosu",translation_en:"tourist office",phonetic:"ɔ.fis də tu.ʁism",category:"travel",gender:"m",level:"A2",emoji:"ℹ️"},
  {id:"a2_103",word:"guide touristique",article:"un",translation_tr:"rehber kitap",translation_en:"travel guide",phonetic:"ɡid tu.ʁis.tik",category:"travel",gender:"m",level:"A2",emoji:"📖"},
  {id:"a2_104",word:"brochure",article:"une",translation_tr:"broşür",translation_en:"brochure",phonetic:"bʁɔ.ʃyʁ",category:"travel",gender:"f",level:"A2",emoji:"📄"},
  {id:"a2_105",word:"carte routière",article:"une",translation_tr:"karayolu haritası",translation_en:"road map",phonetic:"kaʁt ʁu.tjɛʁ",category:"travel",gender:"f",level:"A2",emoji:"🗺️"},

  // ─── TEKNOLOJİ (20) ───
  {id:"a2_106",word:"application",article:"une",translation_tr:"uygulama (app)",translation_en:"app",phonetic:"a.pli.ka.sjɔ̃",category:"technology",gender:"f",level:"A2",emoji:"📱"},
  {id:"a2_107",word:"réseau social",article:"un",translation_tr:"sosyal medya",translation_en:"social network",phonetic:"ʁe.zo sɔ.sjal",category:"technology",gender:"m",level:"A2",emoji:"📱"},
  {id:"a2_108",word:"logiciel",article:"un",translation_tr:"yazılım",translation_en:"software",phonetic:"lɔ.ʒi.sjɛl",category:"technology",gender:"m",level:"A2",emoji:"💻"},
  {id:"a2_109",word:"fichier",article:"un",translation_tr:"dosya",translation_en:"file",phonetic:"fi.ʃje",category:"technology",gender:"m",level:"A2",emoji:"📁"},
  {id:"a2_110",word:"connexion",article:"une",translation_tr:"bağlantı",translation_en:"connection",phonetic:"kɔ.nɛk.sjɔ̃",category:"technology",gender:"f",level:"A2",emoji:"🌐"},
  {id:"a2_111",word:"mot de passe",article:"un",translation_tr:"şifre",translation_en:"password",phonetic:"mo də pas",category:"technology",gender:"m",level:"A2",emoji:"🔐"},
  {id:"a2_112",word:"écran",article:"un",translation_tr:"ekran",translation_en:"screen",phonetic:"e.kʁɑ̃",category:"technology",gender:"m",level:"A2",emoji:"🖥️"},
  {id:"a2_113",word:"clavier",article:"un",translation_tr:"klavye",translation_en:"keyboard",phonetic:"kla.vje",category:"technology",gender:"m",level:"A2",emoji:"⌨️"},
  {id:"a2_114",word:"imprimante",article:"une",translation_tr:"yazıcı",translation_en:"printer",phonetic:"ɛ̃.pʁi.mɑ̃t",category:"technology",gender:"f",level:"A2",emoji:"🖨️"},
  {id:"a2_115",word:"batterie",article:"une",translation_tr:"pil / batarya",translation_en:"battery",phonetic:"ba.tʁi",category:"technology",gender:"f",level:"A2",emoji:"🔋"},
  {id:"a2_116",word:"chargeur",article:"un",translation_tr:"şarj cihazı",translation_en:"charger",phonetic:"ʃaʁ.ʒœʁ",category:"technology",gender:"m",level:"A2",emoji:"🔌"},
  {id:"a2_117",word:"casque",article:"un",translation_tr:"kulaklık",translation_en:"headphones",phonetic:"kask",category:"technology",gender:"m",level:"A2",emoji:"🎧"},
  {id:"a2_118",word:"caméra",article:"une",translation_tr:"kamera",translation_en:"camera",phonetic:"ka.me.ʁa",category:"technology",gender:"f",level:"A2",emoji:"📹"},
  {id:"a2_119",word:"notification",article:"une",translation_tr:"bildirim",translation_en:"notification",phonetic:"nɔ.ti.fi.ka.sjɔ̃",category:"technology",gender:"f",level:"A2",emoji:"🔔"},
  {id:"a2_120",word:"abonnement",article:"un",translation_tr:"abonelik",translation_en:"subscription",phonetic:"a.bɔn.mɑ̃",category:"technology",gender:"m",level:"A2",emoji:"📋"},
  {id:"a2_121",word:"téléchargement",article:"un",translation_tr:"indirme",translation_en:"download",phonetic:"te.le.ʃaʁʒ.mɑ̃",category:"technology",gender:"m",level:"A2",emoji:"⬇️"},
  {id:"a2_122",word:"visioconférence",article:"une",translation_tr:"görüntülü toplantı",translation_en:"video conference",phonetic:"vi.zjo.kɔ̃.fe.ʁɑ̃s",category:"technology",gender:"f",level:"A2",emoji:"💻"},
  {id:"a2_123",word:"messagerie",article:"une",translation_tr:"mesajlaşma",translation_en:"messaging",phonetic:"mɛ.sa.ʒʁi",category:"technology",gender:"f",level:"A2",emoji:"💬"},
  {id:"a2_124",word:"souris",article:"une",translation_tr:"fare (bilgisayar)",translation_en:"mouse",phonetic:"su.ʁi",category:"technology",gender:"f",level:"A2",emoji:"🖱️"},
  {id:"a2_125",word:"télétravail",article:"un",translation_tr:"uzaktan çalışma",translation_en:"remote work",phonetic:"te.le tʁa.vaj",category:"technology",gender:"m",level:"A2",emoji:"🏠"},

  // ─── ÇEVRE & TOPLUM (20) ───
  {id:"a2_126",word:"environnement",article:"un",translation_tr:"çevre",translation_en:"environment",phonetic:"ɑ̃.vi.ʁɔn.mɑ̃",category:"society",gender:"m",level:"A2",emoji:"🌍"},
  {id:"a2_127",word:"pollution",article:"une",translation_tr:"kirlilik",translation_en:"pollution",phonetic:"pɔ.ly.sjɔ̃",category:"society",gender:"f",level:"A2",emoji:"🏭"},
  {id:"a2_128",word:"recyclage",article:"un",translation_tr:"geri dönüşüm",translation_en:"recycling",phonetic:"ʁə.si.klaʒ",category:"society",gender:"m",level:"A2",emoji:"♻️"},
  {id:"a2_129",word:"énergie",article:"une",translation_tr:"enerji",translation_en:"energy",phonetic:"e.nɛʁ.ʒi",category:"society",gender:"f",level:"A2",emoji:"⚡"},
  {id:"a2_130",word:"société",article:"une",translation_tr:"toplum",translation_en:"society",phonetic:"sɔ.sje.te",category:"society",gender:"f",level:"A2",emoji:"👥"},
  {id:"a2_131",word:"gouvernement",article:"un",translation_tr:"hükümet",translation_en:"government",phonetic:"ɡu.vɛʁn.mɑ̃",category:"society",gender:"m",level:"A2",emoji:"🏛️"},
  {id:"a2_132",word:"loi",article:"une",translation_tr:"kanun / yasa",translation_en:"law",phonetic:"lwa",category:"society",gender:"f",level:"A2",emoji:"⚖️"},
  {id:"a2_133",word:"droit",article:"un",translation_tr:"hak / hukuk",translation_en:"right/law",phonetic:"dʁwa",category:"society",gender:"m",level:"A2",emoji:"⚖️"},
  {id:"a2_134",word:"liberté",article:"une",translation_tr:"özgürlük",translation_en:"freedom",phonetic:"li.bɛʁ.te",category:"society",gender:"f",level:"A2",emoji:"🕊️"},
  {id:"a2_135",word:"égalité",article:"une",translation_tr:"eşitlik",translation_en:"equality",phonetic:"e.ɡa.li.te",category:"society",gender:"f",level:"A2",emoji:"⚖️"},
  {id:"a2_136",word:"association",article:"une",translation_tr:"dernek",translation_en:"association",phonetic:"a.sɔ.sja.sjɔ̃",category:"society",gender:"f",level:"A2",emoji:"🤝"},
  {id:"a2_137",word:"bénévole",article:"un",translation_tr:"gönüllü",translation_en:"volunteer",phonetic:"be.ne.vɔl",category:"society",gender:"m",level:"A2",emoji:"🤝"},
  {id:"a2_138",word:"solidarité",article:"une",translation_tr:"dayanışma",translation_en:"solidarity",phonetic:"sɔ.li.da.ʁi.te",category:"society",gender:"f",level:"A2",emoji:"🤝"},
  {id:"a2_139",word:"élection",article:"une",translation_tr:"seçim",translation_en:"election",phonetic:"e.lɛk.sjɔ̃",category:"society",gender:"f",level:"A2",emoji:"🗳️"},
  {id:"a2_140",word:"impôt",article:"un",translation_tr:"vergi",translation_en:"tax",phonetic:"ɛ̃.po",category:"society",gender:"m",level:"A2",emoji:"💰"},
  {id:"a2_141",word:"immigration",article:"une",translation_tr:"göç",translation_en:"immigration",phonetic:"i.mi.ɡʁa.sjɔ̃",category:"society",gender:"f",level:"A2",emoji:"✈️"},
  {id:"a2_142",word:"diversité",article:"une",translation_tr:"çeşitlilik",translation_en:"diversity",phonetic:"di.vɛʁ.si.te",category:"society",gender:"f",level:"A2",emoji:"🌈"},
  {id:"a2_143",word:"manifestation",article:"une",translation_tr:"gösteri",translation_en:"demonstration",phonetic:"ma.ni.fɛs.ta.sjɔ̃",category:"society",gender:"f",level:"A2",emoji:"✊"},
  {id:"a2_144",word:"grève",article:"une",translation_tr:"grev",translation_en:"strike",phonetic:"ɡʁɛv",category:"society",gender:"f",level:"A2",emoji:"✊"},
  {id:"a2_145",word:"développement durable",article:"un",translation_tr:"sürdürülebilir kalkınma",translation_en:"sustainable development",phonetic:"de.vɛ.lɔp.mɑ̃ dy.ʁabl",category:"society",gender:"m",level:"A2",emoji:"🌱"},

  // ─── SPOR (20) ───
  {id:"a2_146",word:"équipe",article:"une",translation_tr:"takım",translation_en:"team",phonetic:"e.kip",category:"sports",gender:"f",level:"A2",emoji:"⚽"},
  {id:"a2_147",word:"match",article:"un",translation_tr:"maç",translation_en:"match",phonetic:"matʃ",category:"sports",gender:"m",level:"A2",emoji:"🏆"},
  {id:"a2_148",word:"championnat",article:"un",translation_tr:"şampiyona",translation_en:"championship",phonetic:"ʃɑ̃.pjɔ.na",category:"sports",gender:"m",level:"A2",emoji:"🏆"},
  {id:"a2_149",word:"but",article:"un",translation_tr:"gol / hedef",translation_en:"goal",phonetic:"by",category:"sports",gender:"m",level:"A2",emoji:"⚽"},
  {id:"a2_150",word:"entraînement",article:"un",translation_tr:"antrenman",translation_en:"training",phonetic:"ɑ̃.tʁɛn.mɑ̃",category:"sports",gender:"m",level:"A2",emoji:"🏃"},
  {id:"a2_151",word:"compétition",article:"une",translation_tr:"yarışma",translation_en:"competition",phonetic:"kɔ̃.pe.ti.sjɔ̃",category:"sports",gender:"f",level:"A2",emoji:"🏆"},
  {id:"a2_152",word:"victoire",article:"une",translation_tr:"zafer / galibiyet",translation_en:"victory",phonetic:"vik.twaʁ",category:"sports",gender:"f",level:"A2",emoji:"🏆"},
  {id:"a2_153",word:"défaite",article:"une",translation_tr:"yenilgi",translation_en:"defeat",phonetic:"de.fɛt",category:"sports",gender:"f",level:"A2",emoji:"😔"},
  {id:"a2_154",word:"médaille",article:"une",translation_tr:"madalya",translation_en:"medal",phonetic:"me.daj",category:"sports",gender:"f",level:"A2",emoji:"🏅"},
  {id:"a2_155",word:"ski",article:"un",translation_tr:"kayak",translation_en:"skiing",phonetic:"ski",category:"sports",gender:"m",level:"A2",emoji:"⛷️"},
  {id:"a2_156",word:"randonnée",article:"une",translation_tr:"doğa yürüyüşü",translation_en:"hiking",phonetic:"ʁɑ̃.dɔ.ne",category:"sports",gender:"f",level:"A2",emoji:"🥾"},
  {id:"a2_157",word:"salle de sport",article:"une",translation_tr:"spor salonu",translation_en:"gym",phonetic:"sal də spɔʁ",category:"sports",gender:"f",level:"A2",emoji:"🏋️"},
  {id:"a2_158",word:"arbitre",article:"un",translation_tr:"hakem",translation_en:"referee",phonetic:"aʁ.bitʁ",category:"sports",gender:"m",level:"A2",emoji:"⚽"},
  {id:"a2_159",word:"entraîneur",article:"un",translation_tr:"antrenör",translation_en:"coach",phonetic:"ɑ̃.tʁɛ.nœʁ",category:"sports",gender:"m",level:"A2",emoji:"👨‍💼"},
  {id:"a2_160",word:"cyclisme",article:"un",translation_tr:"bisiklet yarışı",translation_en:"cycling",phonetic:"si.klism",category:"sports",gender:"m",level:"A2",emoji:"🚴"},
  {id:"a2_161",word:"natation",article:"une",translation_tr:"yüzme",translation_en:"swimming",phonetic:"na.ta.sjɔ̃",category:"sports",gender:"f",level:"A2",emoji:"🏊"},
  {id:"a2_162",word:"surf",article:"un",translation_tr:"sörf",translation_en:"surfing",phonetic:"sœʁf",category:"sports",gender:"m",level:"A2",emoji:"🏄"},
  {id:"a2_163",word:"yoga",article:"un",translation_tr:"yoga",translation_en:"yoga",phonetic:"jɔ.ɡa",category:"sports",gender:"m",level:"A2",emoji:"🧘"},
  {id:"a2_164",word:"escalade",article:"une",translation_tr:"tırmanma",translation_en:"climbing",phonetic:"ɛs.ka.lad",category:"sports",gender:"f",level:"A2",emoji:"🧗"},
  {id:"a2_165",word:"voile",article:"une",translation_tr:"yelkencilik",translation_en:"sailing",phonetic:"vwal",category:"sports",gender:"f",level:"A2",emoji:"⛵"},

  // ─── SANAT & KÜLTÜR (20) ───
  {id:"a2_166",word:"tableau",article:"un",translation_tr:"tablo / resim",translation_en:"painting",phonetic:"ta.blo",category:"arts",gender:"m",level:"A2",emoji:"🖼️"},
  {id:"a2_167",word:"sculpture",article:"une",translation_tr:"heykel",translation_en:"sculpture",phonetic:"skyl.tyʁ",category:"arts",gender:"f",level:"A2",emoji:"🗿"},
  {id:"a2_168",word:"roman",article:"un",translation_tr:"roman (kitap)",translation_en:"novel",phonetic:"ʁɔ.mɑ̃",category:"arts",gender:"m",level:"A2",emoji:"📖"},
  {id:"a2_169",word:"poème",article:"un",translation_tr:"şiir",translation_en:"poem",phonetic:"pɔ.ɛm",category:"arts",gender:"m",level:"A2",emoji:"📝"},
  {id:"a2_170",word:"auteur",article:"un",translation_tr:"yazar",translation_en:"author",phonetic:"o.tœʁ",category:"arts",gender:"m",level:"A2",emoji:"✍️"},
  {id:"a2_171",word:"personnage",article:"un",translation_tr:"karakter",translation_en:"character",phonetic:"pɛʁ.sɔ.naʒ",category:"arts",gender:"m",level:"A2",emoji:"🎭"},
  {id:"a2_172",word:"scène",article:"une",translation_tr:"sahne",translation_en:"scene/stage",phonetic:"sɛn",category:"arts",gender:"f",level:"A2",emoji:"🎭"},
  {id:"a2_173",word:"réalisateur",article:"un",translation_tr:"yönetmen",translation_en:"director (film)",phonetic:"ʁe.a.li.za.tœʁ",category:"arts",gender:"m",level:"A2",emoji:"🎬"},
  {id:"a2_174",word:"piano",article:"un",translation_tr:"piyano",translation_en:"piano",phonetic:"pja.no",category:"arts",gender:"m",level:"A2",emoji:"🎹"},
  {id:"a2_175",word:"guitare",article:"une",translation_tr:"gitar",translation_en:"guitar",phonetic:"ɡi.taʁ",category:"arts",gender:"f",level:"A2",emoji:"🎸"},
  {id:"a2_176",word:"violon",article:"un",translation_tr:"keman",translation_en:"violin",phonetic:"vjɔ.lɔ̃",category:"arts",gender:"m",level:"A2",emoji:"🎻"},
  {id:"a2_177",word:"culture",article:"une",translation_tr:"kültür",translation_en:"culture",phonetic:"kyl.tyʁ",category:"arts",gender:"f",level:"A2",emoji:"🎭"},
  {id:"a2_178",word:"tradition",article:"une",translation_tr:"gelenek",translation_en:"tradition",phonetic:"tʁa.di.sjɔ̃",category:"arts",gender:"f",level:"A2",emoji:"🎎"},
  {id:"a2_179",word:"patrimoine",article:"un",translation_tr:"kültürel miras",translation_en:"heritage",phonetic:"pa.tʁi.mwan",category:"arts",gender:"m",level:"A2",emoji:"🏛️"},
  {id:"a2_180",word:"architecture",article:"une",translation_tr:"mimarlık",translation_en:"architecture",phonetic:"aʁ.ʃi.tɛk.tyʁ",category:"arts",gender:"f",level:"A2",emoji:"🏛️"},
  {id:"a2_181",word:"instrument de musique",article:"un",translation_tr:"müzik aleti",translation_en:"musical instrument",phonetic:"ɛ̃s.tʁy.mɑ̃ də my.zik",category:"arts",gender:"m",level:"A2",emoji:"🎸"},
  {id:"a2_182",word:"concert",article:"un",translation_tr:"konser",translation_en:"concert",phonetic:"kɔ̃.sɛʁ",category:"arts",gender:"m",level:"A2",emoji:"🎸"},
  {id:"a2_183",word:"exposition",article:"une",translation_tr:"sergi",translation_en:"exhibition",phonetic:"ɛks.po.zi.sjɔ̃",category:"arts",gender:"f",level:"A2",emoji:"🖼️"},
  {id:"a2_184",word:"festival",article:"un",translation_tr:"festival",translation_en:"festival",phonetic:"fɛs.ti.val",category:"arts",gender:"m",level:"A2",emoji:"🎉"},
  {id:"a2_185",word:"bande originale",article:"une",translation_tr:"film müziği",translation_en:"soundtrack",phonetic:"bɑ̃d ɔ.ʁi.ʒi.nal",category:"arts",gender:"f",level:"A2",emoji:"🎵"},

  // ─── DUYGULAR & İLİŞKİLER (20) ───
  {id:"a2_186",word:"relation",article:"une",translation_tr:"ilişki",translation_en:"relationship",phonetic:"ʁə.la.sjɔ̃",category:"emotions",gender:"f",level:"A2",emoji:"❤️"},
  {id:"a2_187",word:"amitié",article:"une",translation_tr:"dostluk",translation_en:"friendship",phonetic:"a.mi.tje",category:"emotions",gender:"f",level:"A2",emoji:"🤝"},
  {id:"a2_188",word:"confiance",article:"une",translation_tr:"güven",translation_en:"trust",phonetic:"kɔ̃.fjɑ̃s",category:"emotions",gender:"f",level:"A2",emoji:"🤝"},
  {id:"a2_189",word:"déception",article:"une",translation_tr:"hayal kırıklığı",translation_en:"disappointment",phonetic:"de.sɛp.sjɔ̃",category:"emotions",gender:"f",level:"A2",emoji:"😔"},
  {id:"a2_190",word:"fierté",article:"une",translation_tr:"gurur",translation_en:"pride",phonetic:"fjɛʁ.te",category:"emotions",gender:"f",level:"A2",emoji:"😊"},
  {id:"a2_191",word:"enthousiasme",article:"un",translation_tr:"coşku / heves",translation_en:"enthusiasm",phonetic:"ɑ̃.tu.zjasm",category:"emotions",gender:"m",level:"A2",emoji:"🎉"},
  {id:"a2_192",word:"mariage",article:"un",translation_tr:"evlilik / düğün",translation_en:"wedding",phonetic:"ma.ʁjaʒ",category:"emotions",gender:"m",level:"A2",emoji:"💍"},
  {id:"a2_193",word:"naissance",article:"une",translation_tr:"doğum",translation_en:"birth",phonetic:"nɛ.sɑ̃s",category:"emotions",gender:"f",level:"A2",emoji:"👶"},
  {id:"a2_194",word:"fête",article:"une",translation_tr:"kutlama / bayram",translation_en:"celebration",phonetic:"fɛt",category:"emotions",gender:"f",level:"A2",emoji:"🎉"},
  {id:"a2_195",word:"félicitations",article:"des",translation_tr:"tebrikler",translation_en:"congratulations",phonetic:"fe.li.si.ta.sjɔ̃",category:"emotions",gender:"f",level:"A2",emoji:"🎊"},
  {id:"a2_196",word:"invitation",article:"une",translation_tr:"davet",translation_en:"invitation",phonetic:"ɛ̃.vi.ta.sjɔ̃",category:"emotions",gender:"f",level:"A2",emoji:"💌"},
  {id:"a2_197",word:"jalousie",article:"une",translation_tr:"kıskançlık",translation_en:"jealousy",phonetic:"ʒa.lu.zi",category:"emotions",gender:"f",level:"A2",emoji:"😤"},
  {id:"a2_198",word:"nostalgie",article:"une",translation_tr:"özlem / nostalji",translation_en:"nostalgia",phonetic:"nɔs.tal.ʒi",category:"emotions",gender:"f",level:"A2",emoji:"💭"},
  {id:"a2_199",word:"honte",article:"une",translation_tr:"utanç",translation_en:"shame",phonetic:"ɔ̃t",category:"emotions",gender:"f",level:"A2",emoji:"😳"},
  {id:"a2_200",word:"anniversaire",article:"un",translation_tr:"doğum günü",translation_en:"birthday",phonetic:"a.ni.vɛʁ.sɛʁ",category:"emotions",gender:"m",level:"A2",emoji:"🎂"},

  // ─── PARA & FİNANS (20) ───
  {id:"a2_201",word:"budget",article:"un",translation_tr:"bütçe",translation_en:"budget",phonetic:"byd.ʒɛ",category:"finance",gender:"m",level:"A2",emoji:"💰"},
  {id:"a2_202",word:"dépense",article:"une",translation_tr:"harcama",translation_en:"expense",phonetic:"de.pɑ̃s",category:"finance",gender:"f",level:"A2",emoji:"💸"},
  {id:"a2_203",word:"économies",article:"des",translation_tr:"tasarruf",translation_en:"savings",phonetic:"e.kɔ.nɔ.mi",category:"finance",gender:"f",level:"A2",emoji:"🏦"},
  {id:"a2_204",word:"compte bancaire",article:"un",translation_tr:"banka hesabı",translation_en:"bank account",phonetic:"kɔ̃t bɑ̃.kɛʁ",category:"finance",gender:"m",level:"A2",emoji:"🏦"},
  {id:"a2_205",word:"facture",article:"une",translation_tr:"fatura",translation_en:"invoice/bill",phonetic:"fak.tyʁ",category:"finance",gender:"f",level:"A2",emoji:"🧾"},
  {id:"a2_206",word:"prêt",article:"un",translation_tr:"kredi / borç",translation_en:"loan",phonetic:"pʁɛ",category:"finance",gender:"m",level:"A2",emoji:"🏦"},
  {id:"a2_207",word:"remboursement",article:"un",translation_tr:"geri ödeme",translation_en:"reimbursement",phonetic:"ʁɑ̃.buʁs.mɑ̃",category:"finance",gender:"m",level:"A2",emoji:"💰"},
  {id:"a2_208",word:"retraite",article:"une",translation_tr:"emeklilik",translation_en:"retirement",phonetic:"ʁə.tʁɛt",category:"finance",gender:"f",level:"A2",emoji:"👴"},
  {id:"a2_209",word:"assurance maladie",article:"une",translation_tr:"sağlık sigortası",translation_en:"health insurance",phonetic:"a.sy.ʁɑ̃s ma.la.di",category:"finance",gender:"f",level:"A2",emoji:"🏥"},
  {id:"a2_210",word:"inflation",article:"une",translation_tr:"enflasyon",translation_en:"inflation",phonetic:"ɛ̃.fla.sjɔ̃",category:"finance",gender:"f",level:"A2",emoji:"📈"},
  {id:"a2_211",word:"commerce",article:"un",translation_tr:"ticaret",translation_en:"trade",phonetic:"kɔ.mɛʁs",category:"finance",gender:"m",level:"A2",emoji:"🏪"},
  {id:"a2_212",word:"investissement",article:"un",translation_tr:"yatırım",translation_en:"investment",phonetic:"ɛ̃.vɛs.tis.mɑ̃",category:"finance",gender:"m",level:"A2",emoji:"📈"},
  {id:"a2_213",word:"virement",article:"un",translation_tr:"havale / transfer",translation_en:"bank transfer",phonetic:"viʁ.mɑ̃",category:"finance",gender:"m",level:"A2",emoji:"💳"},
  {id:"a2_214",word:"cotisation",article:"une",translation_tr:"aidat / prim",translation_en:"contribution",phonetic:"kɔ.ti.za.sjɔ̃",category:"finance",gender:"f",level:"A2",emoji:"💰"},
  {id:"a2_215",word:"taux",article:"un",translation_tr:"oran",translation_en:"rate",phonetic:"to",category:"finance",gender:"m",level:"A2",emoji:"📊"},
  {id:"a2_216",word:"bénéfice",article:"un",translation_tr:"kâr / kazanç",translation_en:"profit",phonetic:"be.ne.fis",category:"finance",gender:"m",level:"A2",emoji:"💰"},
  {id:"a2_217",word:"allocation",article:"une",translation_tr:"ödenek / yardım",translation_en:"allowance",phonetic:"a.lɔ.ka.sjɔ̃",category:"finance",gender:"f",level:"A2",emoji:"💰"},
  {id:"a2_218",word:"subvention",article:"une",translation_tr:"hibe / destek",translation_en:"subsidy",phonetic:"syb.vɑ̃.sjɔ̃",category:"finance",gender:"f",level:"A2",emoji:"💸"},
  {id:"a2_219",word:"échange",article:"un",translation_tr:"takas / değişim",translation_en:"exchange",phonetic:"e.ʃɑ̃ʒ",category:"finance",gender:"m",level:"A2",emoji:"🔄"},
  {id:"a2_220",word:"marché boursier",article:"un",translation_tr:"borsa",translation_en:"stock market",phonetic:"maʁ.ʃe buʁ.sje",category:"finance",gender:"m",level:"A2",emoji:"📊"},

  // ─── DOĞA & ÇEVRE (20) ───
  {id:"a2_221",word:"automne",article:"un",translation_tr:"sonbahar",translation_en:"autumn",phonetic:"o.tɔn",category:"nature",gender:"m",level:"A2",emoji:"🍂"},
  {id:"a2_222",word:"hiver",article:"un",translation_tr:"kış",translation_en:"winter",phonetic:"i.vɛʁ",category:"nature",gender:"m",level:"A2",emoji:"❄️"},
  {id:"a2_223",word:"tempête",article:"une",translation_tr:"fırtına",translation_en:"storm",phonetic:"tɑ̃.pɛt",category:"nature",gender:"f",level:"A2",emoji:"⛈️"},
  {id:"a2_224",word:"inondation",article:"une",translation_tr:"sel / taşkın",translation_en:"flood",phonetic:"i.nɔ̃.da.sjɔ̃",category:"nature",gender:"f",level:"A2",emoji:"🌊"},
  {id:"a2_225",word:"volcan",article:"un",translation_tr:"volkan",translation_en:"volcano",phonetic:"vɔl.kɑ̃",category:"nature",gender:"m",level:"A2",emoji:"🌋"},
  {id:"a2_226",word:"île",article:"une",translation_tr:"ada",translation_en:"island",phonetic:"il",category:"nature",gender:"f",level:"A2",emoji:"🏝️"},
  {id:"a2_227",word:"lac",article:"un",translation_tr:"göl",translation_en:"lake",phonetic:"lak",category:"nature",gender:"m",level:"A2",emoji:"🏞️"},
  {id:"a2_228",word:"désert",article:"un",translation_tr:"çöl",translation_en:"desert",phonetic:"de.zɛʁ",category:"nature",gender:"m",level:"A2",emoji:"🏜️"},
  {id:"a2_229",word:"côte",article:"une",translation_tr:"kıyı / sahil",translation_en:"coast",phonetic:"kot",category:"nature",gender:"f",level:"A2",emoji:"🌊"},
  {id:"a2_230",word:"vallée",article:"une",translation_tr:"vadi",translation_en:"valley",phonetic:"va.le",category:"nature",gender:"f",level:"A2",emoji:"🏞️"},
  {id:"a2_231",word:"planète",article:"une",translation_tr:"gezegen",translation_en:"planet",phonetic:"pla.nɛt",category:"nature",gender:"f",level:"A2",emoji:"🌍"},
  {id:"a2_232",word:"réchauffement climatique",article:"un",translation_tr:"küresel ısınma",translation_en:"global warming",phonetic:"ʁe.ʃof.mɑ̃ kli.ma.tik",category:"nature",gender:"m",level:"A2",emoji:"🌡️"},
  {id:"a2_233",word:"biodiversité",article:"une",translation_tr:"biyoçeşitlilik",translation_en:"biodiversity",phonetic:"bjo.di.vɛʁ.si.te",category:"nature",gender:"f",level:"A2",emoji:"🌿"},
  {id:"a2_234",word:"espèce",article:"une",translation_tr:"tür (biyoloji)",translation_en:"species",phonetic:"ɛs.pɛs",category:"nature",gender:"f",level:"A2",emoji:"🦁"},
  {id:"a2_235",word:"déforestation",article:"une",translation_tr:"ormansızlaşma",translation_en:"deforestation",phonetic:"de.fɔ.ʁɛs.ta.sjɔ̃",category:"nature",gender:"f",level:"A2",emoji:"🌲"},
  {id:"a2_236",word:"tremblement de terre",article:"un",translation_tr:"deprem",translation_en:"earthquake",phonetic:"tʁɑ̃bl.mɑ̃ də tɛʁ",category:"nature",gender:"m",level:"A2",emoji:"🌍"},
  {id:"a2_237",word:"ressource naturelle",article:"une",translation_tr:"doğal kaynak",translation_en:"natural resource",phonetic:"ʁə.suʁs na.ty.ʁɛl",category:"nature",gender:"f",level:"A2",emoji:"🌿"},
  {id:"a2_238",word:"colline",article:"une",translation_tr:"tepe",translation_en:"hill",phonetic:"kɔ.lin",category:"nature",gender:"f",level:"A2",emoji:"⛰️"},
  {id:"a2_239",word:"forêt tropicale",article:"une",translation_tr:"tropik orman",translation_en:"rainforest",phonetic:"fɔ.ʁɛ tʁɔ.pi.kal",category:"nature",gender:"f",level:"A2",emoji:"🌴"},
  {id:"a2_240",word:"atmosphère",article:"une",translation_tr:"atmosfer",translation_en:"atmosphere",phonetic:"at.mɔs.fɛʁ",category:"nature",gender:"f",level:"A2",emoji:"🌍"},

  // ─── İLETİŞİM & KONUŞMA (20) ───
  {id:"a2_241",word:"traduction",article:"une",translation_tr:"çeviri",translation_en:"translation",phonetic:"tʁa.dyk.sjɔ̃",category:"communication",gender:"f",level:"A2",emoji:"🌐"},
  {id:"a2_242",word:"prononciation",article:"une",translation_tr:"telaffuz",translation_en:"pronunciation",phonetic:"pʁɔ.nɔ̃.sja.sjɔ̃",category:"communication",gender:"f",level:"A2",emoji:"🗣️"},
  {id:"a2_243",word:"grammaire",article:"une",translation_tr:"dilbilgisi",translation_en:"grammar",phonetic:"ɡʁa.mɛʁ",category:"communication",gender:"f",level:"A2",emoji:"📝"},
  {id:"a2_244",word:"vocabulaire",article:"un",translation_tr:"kelime hazinesi",translation_en:"vocabulary",phonetic:"vɔ.ka.by.lɛʁ",category:"communication",gender:"m",level:"A2",emoji:"📚"},
  {id:"a2_245",word:"débat",article:"un",translation_tr:"tartışma / münazara",translation_en:"debate",phonetic:"de.ba",category:"communication",gender:"m",level:"A2",emoji:"🗣️"},
  {id:"a2_246",word:"négociation",article:"une",translation_tr:"müzakere",translation_en:"negotiation",phonetic:"ne.ɡɔ.sja.sjɔ̃",category:"communication",gender:"f",level:"A2",emoji:"🤝"},
  {id:"a2_247",word:"annonce",article:"une",translation_tr:"duyuru / ilan",translation_en:"announcement",phonetic:"a.nɔ̃s",category:"communication",gender:"f",level:"A2",emoji:"📢"},
  {id:"a2_248",word:"publicité",article:"une",translation_tr:"reklam",translation_en:"advertisement",phonetic:"py.bli.si.te",category:"communication",gender:"f",level:"A2",emoji:"📺"},
  {id:"a2_249",word:"formulaire",article:"un",translation_tr:"form / dilekçe",translation_en:"form",phonetic:"fɔʁ.my.lɛʁ",category:"communication",gender:"m",level:"A2",emoji:"📋"},
  {id:"a2_250",word:"compte rendu",article:"un",translation_tr:"rapor / özet",translation_en:"report",phonetic:"kɔ̃t ʁɑ̃.dy",category:"communication",gender:"m",level:"A2",emoji:"📋"},
  {id:"a2_251",word:"promesse",article:"une",translation_tr:"söz / vaat",translation_en:"promise",phonetic:"pʁɔ.mɛs",category:"communication",gender:"f",level:"A2",emoji:"🤝"},
  {id:"a2_252",word:"vérité",article:"une",translation_tr:"gerçek / doğru",translation_en:"truth",phonetic:"ve.ʁi.te",category:"communication",gender:"f",level:"A2",emoji:"✅"},
  {id:"a2_253",word:"mensonge",article:"un",translation_tr:"yalan",translation_en:"lie",phonetic:"mɑ̃.sɔ̃ʒ",category:"communication",gender:"m",level:"A2",emoji:"🤥"},
  {id:"a2_254",word:"critique",article:"une",translation_tr:"eleştiri",translation_en:"criticism",phonetic:"kʁi.tik",category:"communication",gender:"f",level:"A2",emoji:"💬"},
  {id:"a2_255",word:"compliment",article:"un",translation_tr:"iltifat",translation_en:"compliment",phonetic:"kɔ̃.pli.mɑ̃",category:"communication",gender:"m",level:"A2",emoji:"😊"},
  {id:"a2_256",word:"discours",article:"un",translation_tr:"konuşma / söylev",translation_en:"speech",phonetic:"dis.kuʁ",category:"communication",gender:"m",level:"A2",emoji:"🎤"},
  {id:"a2_257",word:"accent",article:"un",translation_tr:"aksan / vurgu",translation_en:"accent",phonetic:"ak.sɑ̃",category:"communication",gender:"m",level:"A2",emoji:"🗣️"},
  {id:"a2_258",word:"expression",article:"une",translation_tr:"ifade / deyim",translation_en:"expression",phonetic:"ɛks.pʁɛ.sjɔ̃",category:"communication",gender:"f",level:"A2",emoji:"💬"},
  {id:"a2_259",word:"argot",article:"un",translation_tr:"argo",translation_en:"slang",phonetic:"aʁ.ɡo",category:"communication",gender:"m",level:"A2",emoji:"🗣️"},
  {id:"a2_260",word:"interprète",article:"un",translation_tr:"tercüman",translation_en:"interpreter",phonetic:"ɛ̃.tɛʁ.pʁɛt",category:"communication",gender:"m",level:"A2",emoji:"🌐"},

  // ─── SIFATLAR & ZARFLAR (50) ───
  {id:"a2_261",word:"agréable",article:"",translation_tr:"hoş / keyifli",translation_en:"pleasant",phonetic:"a.ɡʁe.abl",category:"adjectives",gender:"v",level:"A2",emoji:"😊"},
  {id:"a2_262",word:"désagréable",article:"",translation_tr:"nahoş / tatsız",translation_en:"unpleasant",phonetic:"de.za.ɡʁe.abl",category:"adjectives",gender:"v",level:"A2",emoji:"😒"},
  {id:"a2_263",word:"pratique",article:"",translation_tr:"pratik / kullanışlı",translation_en:"practical",phonetic:"pʁa.tik",category:"adjectives",gender:"v",level:"A2",emoji:"👍"},
  {id:"a2_264",word:"compliqué",article:"",translation_tr:"karmaşık",translation_en:"complicated",phonetic:"kɔ̃.pli.ke",category:"adjectives",gender:"v",level:"A2",emoji:"🤔"},
  {id:"a2_265",word:"moderne",article:"",translation_tr:"modern",translation_en:"modern",phonetic:"mɔ.dɛʁn",category:"adjectives",gender:"v",level:"A2",emoji:"🆕"},
  {id:"a2_266",word:"traditionnel",article:"",translation_tr:"geleneksel",translation_en:"traditional",phonetic:"tʁa.di.sjɔ.nɛl",category:"adjectives",gender:"v",level:"A2",emoji:"🎎"},
  {id:"a2_267",word:"important",article:"",translation_tr:"önemli",translation_en:"important",phonetic:"ɛ̃.pɔʁ.tɑ̃",category:"adjectives",gender:"v",level:"A2",emoji:"❗"},
  {id:"a2_268",word:"nécessaire",article:"",translation_tr:"gerekli",translation_en:"necessary",phonetic:"ne.sɛ.sɛʁ",category:"adjectives",gender:"v",level:"A2",emoji:"✅"},
  {id:"a2_269",word:"possible",article:"",translation_tr:"mümkün",translation_en:"possible",phonetic:"pɔ.sibl",category:"adjectives",gender:"v",level:"A2",emoji:"✅"},
  {id:"a2_270",word:"impossible",article:"",translation_tr:"imkânsız",translation_en:"impossible",phonetic:"ɛ̃.pɔ.sibl",category:"adjectives",gender:"v",level:"A2",emoji:"🚫"},
  {id:"a2_271",word:"propre",article:"",translation_tr:"temiz",translation_en:"clean",phonetic:"pʁɔpʁ",category:"adjectives",gender:"v",level:"A2",emoji:"✨"},
  {id:"a2_272",word:"sale",article:"",translation_tr:"kirli",translation_en:"dirty",phonetic:"sal",category:"adjectives",gender:"v",level:"A2",emoji:"🤢"},
  {id:"a2_273",word:"plein",article:"",translation_tr:"dolu",translation_en:"full",phonetic:"plɛ̃",category:"adjectives",gender:"v",level:"A2",emoji:"📦"},
  {id:"a2_274",word:"vide",article:"",translation_tr:"boş",translation_en:"empty",phonetic:"vid",category:"adjectives",gender:"v",level:"A2",emoji:"📭"},
  {id:"a2_275",word:"ouvert",article:"",translation_tr:"açık",translation_en:"open",phonetic:"u.vɛʁ",category:"adjectives",gender:"v",level:"A2",emoji:"🔓"},
  {id:"a2_276",word:"fermé",article:"",translation_tr:"kapalı",translation_en:"closed",phonetic:"fɛʁ.me",category:"adjectives",gender:"v",level:"A2",emoji:"🔒"},
  {id:"a2_277",word:"disponible",article:"",translation_tr:"müsait / mevcut",translation_en:"available",phonetic:"dis.pɔ.nibl",category:"adjectives",gender:"v",level:"A2",emoji:"✅"},
  {id:"a2_278",word:"urgent",article:"",translation_tr:"acil",translation_en:"urgent",phonetic:"yʁ.ʒɑ̃",category:"adjectives",gender:"v",level:"A2",emoji:"🚨"},
  {id:"a2_279",word:"récent",article:"",translation_tr:"yakın zamanlı",translation_en:"recent",phonetic:"ʁe.sɑ̃",category:"adjectives",gender:"v",level:"A2",emoji:"🆕"},
  {id:"a2_280",word:"certain",article:"",translation_tr:"kesin / emin",translation_en:"certain",phonetic:"sɛʁ.tɛ̃",category:"adjectives",gender:"v",level:"A2",emoji:"✅"},
  {id:"a2_281",word:"principal",article:"",translation_tr:"ana / başlıca",translation_en:"main",phonetic:"pʁɛ̃.si.pal",category:"adjectives",gender:"v",level:"A2",emoji:"⭐"},
  {id:"a2_282",word:"commun",article:"",translation_tr:"ortak / yaygın",translation_en:"common",phonetic:"kɔ.mœ̃",category:"adjectives",gender:"v",level:"A2",emoji:"🤝"},
  {id:"a2_283",word:"précis",article:"",translation_tr:"kesin / dakik",translation_en:"precise",phonetic:"pʁe.si",category:"adjectives",gender:"v",level:"A2",emoji:"🎯"},
  {id:"a2_284",word:"suffisant",article:"",translation_tr:"yeterli",translation_en:"sufficient",phonetic:"sy.fi.zɑ̃",category:"adjectives",gender:"v",level:"A2",emoji:"✅"},
  {id:"a2_285",word:"insuffisant",article:"",translation_tr:"yetersiz",translation_en:"insufficient",phonetic:"ɛ̃.sy.fi.zɑ̃",category:"adjectives",gender:"v",level:"A2",emoji:"❌"},
  {id:"a2_286",word:"cependant",article:"",translation_tr:"bununla birlikte",translation_en:"however",phonetic:"sə.pɑ̃.dɑ̃",category:"connectors",gender:"v",level:"A2",emoji:"↩️"},
  {id:"a2_287",word:"pourtant",article:"",translation_tr:"yine de",translation_en:"yet/however",phonetic:"puʁ.tɑ̃",category:"connectors",gender:"v",level:"A2",emoji:"↩️"},
  {id:"a2_288",word:"en revanche",article:"",translation_tr:"öte yandan",translation_en:"on the other hand",phonetic:"ɑ̃ ʁə.vɑ̃ʃ",category:"connectors",gender:"v",level:"A2",emoji:"↔️"},
  {id:"a2_289",word:"d'ailleurs",article:"",translation_tr:"üstelik / zaten",translation_en:"besides/moreover",phonetic:"da.jœʁ",category:"connectors",gender:"v",level:"A2",emoji:"➕"},
  {id:"a2_290",word:"de plus",article:"",translation_tr:"ayrıca",translation_en:"furthermore",phonetic:"də ply",category:"connectors",gender:"v",level:"A2",emoji:"➕"},
  {id:"a2_291",word:"en effet",article:"",translation_tr:"gerçekten",translation_en:"indeed",phonetic:"ɑ̃ ne.fɛ",category:"connectors",gender:"v",level:"A2",emoji:"✅"},
  {id:"a2_292",word:"c'est-à-dire",article:"",translation_tr:"yani",translation_en:"that is to say",phonetic:"se.ta.diʁ",category:"connectors",gender:"v",level:"A2",emoji:"💡"},
  {id:"a2_293",word:"par exemple",article:"",translation_tr:"örneğin",translation_en:"for example",phonetic:"paʁ ɛɡ.zɑ̃pl",category:"connectors",gender:"v",level:"A2",emoji:"📌"},
  {id:"a2_294",word:"en général",article:"",translation_tr:"genel olarak",translation_en:"in general",phonetic:"ɑ̃ ʒe.ne.ʁal",category:"connectors",gender:"v",level:"A2",emoji:"🌐"},
  {id:"a2_295",word:"d'abord",article:"",translation_tr:"öncelikle",translation_en:"first of all",phonetic:"da.bɔʁ",category:"connectors",gender:"v",level:"A2",emoji:"1️⃣"},
  {id:"a2_296",word:"ensuite",article:"",translation_tr:"sonra / ardından",translation_en:"then/next",phonetic:"ɑ̃.sɥit",category:"connectors",gender:"v",level:"A2",emoji:"2️⃣"},
  {id:"a2_297",word:"finalement",article:"",translation_tr:"sonunda",translation_en:"finally",phonetic:"fi.nal.mɑ̃",category:"connectors",gender:"v",level:"A2",emoji:"🏁"},
  {id:"a2_298",word:"soudain",article:"",translation_tr:"aniden",translation_en:"suddenly",phonetic:"su.dɛ̃",category:"connectors",gender:"v",level:"A2",emoji:"⚡"},
  {id:"a2_299",word:"récemment",article:"",translation_tr:"yakın zamanda",translation_en:"recently",phonetic:"ʁe.sa.mɑ̃",category:"connectors",gender:"v",level:"A2",emoji:"🆕"},
  {id:"a2_300",word:"désormais",article:"",translation_tr:"artık",translation_en:"from now on",phonetic:"de.zɔʁ.mɛ",category:"connectors",gender:"v",level:"A2",emoji:"➡️"},
  {id:"a2_301",word:"autrefois",article:"",translation_tr:"eskiden",translation_en:"formerly",phonetic:"otʁ.fwa",category:"connectors",gender:"v",level:"A2",emoji:"⏮️"},
  {id:"a2_302",word:"longtemps",article:"",translation_tr:"uzun süre",translation_en:"for a long time",phonetic:"lɔ̃.tɑ̃",category:"connectors",gender:"v",level:"A2",emoji:"⏳"},
  {id:"a2_303",word:"plutôt",article:"",translation_tr:"daha ziyade",translation_en:"rather/quite",phonetic:"ply.to",category:"connectors",gender:"v",level:"A2",emoji:"↔️"},
  {id:"a2_304",word:"quand même",article:"",translation_tr:"yine de",translation_en:"even so",phonetic:"kɑ̃ mɛm",category:"connectors",gender:"v",level:"A2",emoji:"💪"},
  {id:"a2_305",word:"à peu près",article:"",translation_tr:"yaklaşık olarak",translation_en:"approximately",phonetic:"a pø pʁɛ",category:"connectors",gender:"v",level:"A2",emoji:"≈"},
  {id:"a2_306",word:"néanmoins",article:"",translation_tr:"bununla birlikte",translation_en:"nevertheless",phonetic:"ne.ɑ̃.mwɛ̃",category:"connectors",gender:"v",level:"A2",emoji:"↩️"},
  {id:"a2_307",word:"progressivement",article:"",translation_tr:"kademeli olarak",translation_en:"gradually",phonetic:"pʁɔ.ɡʁɛ.siv.mɑ̃",category:"connectors",gender:"v",level:"A2",emoji:"📈"},
  {id:"a2_308",word:"tout à coup",article:"",translation_tr:"birdenbire",translation_en:"all of a sudden",phonetic:"tu.ta.ku",category:"connectors",gender:"v",level:"A2",emoji:"⚡"},
  {id:"a2_309",word:"par contre",article:"",translation_tr:"buna karşın",translation_en:"on the contrary",phonetic:"paʁ kɔ̃tʁ",category:"connectors",gender:"v",level:"A2",emoji:"↩️"},
  {id:"a2_310",word:"en particulier",article:"",translation_tr:"özellikle",translation_en:"in particular",phonetic:"ɑ̃ paʁ.ti.ky.lje",category:"connectors",gender:"v",level:"A2",emoji:"⭐"},

  // ─── GENEL KAVRAMLAR (190) ───
  {id:"a2_311",word:"habitude",article:"une",translation_tr:"alışkanlık",translation_en:"habit",phonetic:"a.bi.tyd",category:"general",gender:"f",level:"A2",emoji:"🔄"},
  {id:"a2_312",word:"routine",article:"une",translation_tr:"rutin",translation_en:"routine",phonetic:"ʁu.tin",category:"general",gender:"f",level:"A2",emoji:"📅"},
  {id:"a2_313",word:"objectif",article:"un",translation_tr:"hedef / amaç",translation_en:"objective",phonetic:"ɔb.ʒɛk.tif",category:"general",gender:"m",level:"A2",emoji:"🎯"},
  {id:"a2_314",word:"projet",article:"un",translation_tr:"proje / plan",translation_en:"project",phonetic:"pʁɔ.ʒɛ",category:"general",gender:"m",level:"A2",emoji:"📋"},
  {id:"a2_315",word:"décision",article:"une",translation_tr:"karar",translation_en:"decision",phonetic:"de.si.zjɔ̃",category:"general",gender:"f",level:"A2",emoji:"✅"},
  {id:"a2_316",word:"solution",article:"une",translation_tr:"çözüm",translation_en:"solution",phonetic:"sɔ.ly.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"💡"},
  {id:"a2_317",word:"effort",article:"un",translation_tr:"çaba / efor",translation_en:"effort",phonetic:"ɛ.fɔʁ",category:"general",gender:"m",level:"A2",emoji:"💪"},
  {id:"a2_318",word:"progrès",article:"un",translation_tr:"ilerleme",translation_en:"progress",phonetic:"pʁɔ.ɡʁɛ",category:"general",gender:"m",level:"A2",emoji:"📈"},
  {id:"a2_319",word:"résultat",article:"un",translation_tr:"sonuç",translation_en:"result",phonetic:"ʁe.zyl.ta",category:"general",gender:"m",level:"A2",emoji:"📊"},
  {id:"a2_320",word:"succès",article:"un",translation_tr:"başarı",translation_en:"success",phonetic:"syk.sɛ",category:"general",gender:"m",level:"A2",emoji:"🏆"},
  {id:"a2_321",word:"échec",article:"un",translation_tr:"başarısızlık",translation_en:"failure",phonetic:"e.ʃɛk",category:"general",gender:"m",level:"A2",emoji:"❌"},
  {id:"a2_322",word:"expérience",article:"une",translation_tr:"deneyim",translation_en:"experience",phonetic:"ɛks.pe.ʁjɑ̃s",category:"general",gender:"f",level:"A2",emoji:"⭐"},
  {id:"a2_323",word:"compétence",article:"une",translation_tr:"yetenek / beceri",translation_en:"skill",phonetic:"kɔ̃.pe.tɑ̃s",category:"general",gender:"f",level:"A2",emoji:"🌟"},
  {id:"a2_324",word:"opinion",article:"une",translation_tr:"görüş / fikir",translation_en:"opinion",phonetic:"ɔ.pi.njɔ̃",category:"general",gender:"f",level:"A2",emoji:"💭"},
  {id:"a2_325",word:"conseil",article:"un",translation_tr:"tavsiye",translation_en:"advice",phonetic:"kɔ̃.sɛj",category:"general",gender:"m",level:"A2",emoji:"💡"},
  {id:"a2_326",word:"accord",article:"un",translation_tr:"anlaşma",translation_en:"agreement",phonetic:"a.kɔʁ",category:"general",gender:"m",level:"A2",emoji:"🤝"},
  {id:"a2_327",word:"désaccord",article:"un",translation_tr:"anlaşmazlık",translation_en:"disagreement",phonetic:"de.za.kɔʁ",category:"general",gender:"m",level:"A2",emoji:"❌"},
  {id:"a2_328",word:"permission",article:"une",translation_tr:"izin",translation_en:"permission",phonetic:"pɛʁ.mi.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"✅"},
  {id:"a2_329",word:"interdiction",article:"une",translation_tr:"yasak",translation_en:"prohibition",phonetic:"ɛ̃.tɛʁ.dik.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"🚫"},
  {id:"a2_330",word:"obligation",article:"une",translation_tr:"zorunluluk",translation_en:"obligation",phonetic:"ɔ.bli.ɡa.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"⚠️"},
  {id:"a2_331",word:"situation",article:"une",translation_tr:"durum",translation_en:"situation",phonetic:"si.tɥa.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"📍"},
  {id:"a2_332",word:"condition",article:"une",translation_tr:"koşul",translation_en:"condition",phonetic:"kɔ̃.di.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"📋"},
  {id:"a2_333",word:"méthode",article:"une",translation_tr:"yöntem",translation_en:"method",phonetic:"me.tɔd",category:"general",gender:"f",level:"A2",emoji:"📝"},
  {id:"a2_334",word:"système",article:"un",translation_tr:"sistem",translation_en:"system",phonetic:"sis.tɛm",category:"general",gender:"m",level:"A2",emoji:"⚙️"},
  {id:"a2_335",word:"organisation",article:"une",translation_tr:"organizasyon",translation_en:"organisation",phonetic:"ɔʁ.ɡa.ni.za.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"📋"},
  {id:"a2_336",word:"amélioration",article:"une",translation_tr:"iyileştirme",translation_en:"improvement",phonetic:"a.me.ljɔ.ʁa.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"📈"},
  {id:"a2_337",word:"changement",article:"un",translation_tr:"değişim",translation_en:"change",phonetic:"ʃɑ̃ʒ.mɑ̃",category:"general",gender:"m",level:"A2",emoji:"🔄"},
  {id:"a2_338",word:"développement",article:"un",translation_tr:"gelişme",translation_en:"development",phonetic:"de.vɛ.lɔp.mɑ̃",category:"general",gender:"m",level:"A2",emoji:"📈"},
  {id:"a2_339",word:"avantage",article:"un",translation_tr:"avantaj",translation_en:"advantage",phonetic:"a.vɑ̃.taʒ",category:"general",gender:"m",level:"A2",emoji:"👍"},
  {id:"a2_340",word:"inconvénient",article:"un",translation_tr:"dezavantaj",translation_en:"disadvantage",phonetic:"ɛ̃.kɔ̃.ve.njɑ̃",category:"general",gender:"m",level:"A2",emoji:"👎"},
  {id:"a2_341",word:"risque",article:"un",translation_tr:"risk",translation_en:"risk",phonetic:"ʁisk",category:"general",gender:"m",level:"A2",emoji:"⚠️"},
  {id:"a2_342",word:"sécurité",article:"une",translation_tr:"güvenlik",translation_en:"security",phonetic:"se.ky.ʁi.te",category:"general",gender:"f",level:"A2",emoji:"🔒"},
  {id:"a2_343",word:"accident",article:"un",translation_tr:"kaza",translation_en:"accident",phonetic:"ak.si.dɑ̃",category:"general",gender:"m",level:"A2",emoji:"🚑"},
  {id:"a2_344",word:"événement",article:"un",translation_tr:"olay / etkinlik",translation_en:"event",phonetic:"e.vɛn.mɑ̃",category:"general",gender:"m",level:"A2",emoji:"📅"},
  {id:"a2_345",word:"niveau",article:"un",translation_tr:"seviye / düzey",translation_en:"level",phonetic:"ni.vo",category:"general",gender:"m",level:"A2",emoji:"📊"},
  {id:"a2_346",word:"étape",article:"une",translation_tr:"aşama / adım",translation_en:"stage/step",phonetic:"e.tap",category:"general",gender:"f",level:"A2",emoji:"📋"},
  {id:"a2_347",word:"période",article:"une",translation_tr:"dönem",translation_en:"period",phonetic:"pe.ʁjɔd",category:"general",gender:"f",level:"A2",emoji:"📅"},
  {id:"a2_348",word:"durée",article:"une",translation_tr:"süre",translation_en:"duration",phonetic:"dy.ʁe",category:"general",gender:"f",level:"A2",emoji:"⏱️"},
  {id:"a2_349",word:"délai",article:"un",translation_tr:"süre / vade",translation_en:"deadline",phonetic:"de.lɛ",category:"general",gender:"m",level:"A2",emoji:"⏰"},
  {id:"a2_350",word:"horaire",article:"un",translation_tr:"saat programı",translation_en:"schedule",phonetic:"ɔ.ʁɛʁ",category:"general",gender:"m",level:"A2",emoji:"🗓️"},
  {id:"a2_351",word:"qualité",article:"une",translation_tr:"kalite",translation_en:"quality",phonetic:"ka.li.te",category:"general",gender:"f",level:"A2",emoji:"⭐"},
  {id:"a2_352",word:"quantité",article:"une",translation_tr:"miktar",translation_en:"quantity",phonetic:"kɑ̃.ti.te",category:"general",gender:"f",level:"A2",emoji:"📊"},
  {id:"a2_353",word:"différence",article:"une",translation_tr:"fark",translation_en:"difference",phonetic:"di.fe.ʁɑ̃s",category:"general",gender:"f",level:"A2",emoji:"↔️"},
  {id:"a2_354",word:"comparaison",article:"une",translation_tr:"karşılaştırma",translation_en:"comparison",phonetic:"kɔ̃.pɛ.ʁɛ.zɔ̃",category:"general",gender:"f",level:"A2",emoji:"↔️"},
  {id:"a2_355",word:"exemple",article:"un",translation_tr:"örnek",translation_en:"example",phonetic:"ɛɡ.zɑ̃pl",category:"general",gender:"m",level:"A2",emoji:"📌"},
  {id:"a2_356",word:"thème",article:"un",translation_tr:"tema / konu",translation_en:"theme",phonetic:"tɛm",category:"general",gender:"m",level:"A2",emoji:"📝"},
  {id:"a2_357",word:"sujet",article:"un",translation_tr:"konu",translation_en:"subject",phonetic:"sy.ʒɛ",category:"general",gender:"m",level:"A2",emoji:"📝"},
  {id:"a2_358",word:"domaine",article:"un",translation_tr:"alan / saha",translation_en:"field/domain",phonetic:"dɔ.mɛn",category:"general",gender:"m",level:"A2",emoji:"📋"},
  {id:"a2_359",word:"détail",article:"un",translation_tr:"ayrıntı",translation_en:"detail",phonetic:"de.taj",category:"general",gender:"m",level:"A2",emoji:"🔍"},
  {id:"a2_360",word:"partie",article:"une",translation_tr:"bölüm / kısım",translation_en:"part",phonetic:"paʁ.ti",category:"general",gender:"f",level:"A2",emoji:"📊"},
  {id:"a2_361",word:"aspect",article:"un",translation_tr:"yön / görünüm",translation_en:"aspect",phonetic:"as.pɛ",category:"general",gender:"m",level:"A2",emoji:"🔍"},
  {id:"a2_362",word:"contenu",article:"un",translation_tr:"içerik",translation_en:"content",phonetic:"kɔ̃.tə.ny",category:"general",gender:"m",level:"A2",emoji:"📦"},
  {id:"a2_363",word:"titre",article:"un",translation_tr:"başlık / unvan",translation_en:"title",phonetic:"titʁ",category:"general",gender:"m",level:"A2",emoji:"📝"},
  {id:"a2_364",word:"chapitre",article:"un",translation_tr:"bölüm (kitap)",translation_en:"chapter",phonetic:"ʃa.pitʁ",category:"general",gender:"m",level:"A2",emoji:"📖"},
  {id:"a2_365",word:"page",article:"une",translation_tr:"sayfa",translation_en:"page",phonetic:"paʒ",category:"general",gender:"f",level:"A2",emoji:"📄"},
  {id:"a2_366",word:"liste",article:"une",translation_tr:"liste",translation_en:"list",phonetic:"list",category:"general",gender:"f",level:"A2",emoji:"📋"},
  {id:"a2_367",word:"date",article:"une",translation_tr:"tarih",translation_en:"date",phonetic:"dat",category:"general",gender:"f",level:"A2",emoji:"📅"},
  {id:"a2_368",word:"format",article:"un",translation_tr:"format / biçim",translation_en:"format",phonetic:"fɔʁ.ma",category:"general",gender:"m",level:"A2",emoji:"📄"},
  {id:"a2_369",word:"modèle",article:"un",translation_tr:"model",translation_en:"model",phonetic:"mɔ.dɛl",category:"general",gender:"m",level:"A2",emoji:"⭐"},
  {id:"a2_370",word:"version",article:"une",translation_tr:"versiyon / sürüm",translation_en:"version",phonetic:"vɛʁ.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"🆕"},
  {id:"a2_371",word:"proposition",article:"une",translation_tr:"öneri / teklif",translation_en:"proposal",phonetic:"pʁɔ.po.zi.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"💡"},
  {id:"a2_372",word:"suggestion",article:"une",translation_tr:"öneri",translation_en:"suggestion",phonetic:"syɡ.ʒɛs.tjɔ̃",category:"general",gender:"f",level:"A2",emoji:"💡"},
  {id:"a2_373",word:"explication",article:"une",translation_tr:"açıklama",translation_en:"explanation",phonetic:"ɛks.pli.ka.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"📝"},
  {id:"a2_374",word:"description",article:"une",translation_tr:"tanım / tarif",translation_en:"description",phonetic:"dɛs.kʁip.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"📝"},
  {id:"a2_375",word:"présentation",article:"une",translation_tr:"sunum",translation_en:"presentation",phonetic:"pʁe.zɑ̃.ta.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"🎤"},
  {id:"a2_376",word:"plainte",article:"une",translation_tr:"şikayet",translation_en:"complaint",phonetic:"plɛ̃t",category:"general",gender:"f",level:"A2",emoji:"😤"},
  {id:"a2_377",word:"réclamation",article:"une",translation_tr:"başvuru / şikayet",translation_en:"claim",phonetic:"ʁe.kla.ma.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"📋"},
  {id:"a2_378",word:"démarche",article:"une",translation_tr:"işlem / prosedür",translation_en:"procedure/step",phonetic:"de.maʁʃ",category:"general",gender:"f",level:"A2",emoji:"📋"},
  {id:"a2_379",word:"talent",article:"un",translation_tr:"yetenek",translation_en:"talent",phonetic:"ta.lɑ̃",category:"general",gender:"m",level:"A2",emoji:"🌟"},
  {id:"a2_380",word:"idéal",article:"un",translation_tr:"ideal",translation_en:"ideal",phonetic:"i.de.al",category:"general",gender:"m",level:"A2",emoji:"⭐"},
  {id:"a2_381",word:"réalité",article:"une",translation_tr:"gerçeklik",translation_en:"reality",phonetic:"ʁe.a.li.te",category:"general",gender:"f",level:"A2",emoji:"🌍"},
  {id:"a2_382",word:"illusion",article:"une",translation_tr:"yanılsama / illüzyon",translation_en:"illusion",phonetic:"i.ly.zjɔ̃",category:"general",gender:"f",level:"A2",emoji:"✨"},
  {id:"a2_383",word:"imagination",article:"une",translation_tr:"hayal gücü",translation_en:"imagination",phonetic:"i.ma.ʒi.na.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"💭"},
  {id:"a2_384",word:"créativité",article:"une",translation_tr:"yaratıcılık",translation_en:"creativity",phonetic:"kʁe.a.ti.vi.te",category:"general",gender:"f",level:"A2",emoji:"🎨"},
  {id:"a2_385",word:"curiosité",article:"une",translation_tr:"merak",translation_en:"curiosity",phonetic:"ky.ʁjɔ.zi.te",category:"general",gender:"f",level:"A2",emoji:"🤔"},
  {id:"a2_386",word:"patience",article:"une",translation_tr:"sabır",translation_en:"patience",phonetic:"pa.sjɑ̃s",category:"general",gender:"f",level:"A2",emoji:"⏳"},
  {id:"a2_387",word:"discipline",article:"une",translation_tr:"disiplin",translation_en:"discipline",phonetic:"dis.i.plin",category:"general",gender:"f",level:"A2",emoji:"📏"},
  {id:"a2_388",word:"motivation",article:"une",translation_tr:"motivasyon",translation_en:"motivation",phonetic:"mɔ.ti.va.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"🎯"},
  {id:"a2_389",word:"concentration",article:"une",translation_tr:"konsantrasyon",translation_en:"concentration",phonetic:"kɔ̃.sɑ̃.tʁa.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"🎯"},
  {id:"a2_390",word:"mémoire",article:"une",translation_tr:"hafıza / bellek",translation_en:"memory",phonetic:"me.mwaʁ",category:"general",gender:"f",level:"A2",emoji:"🧠"},
  {id:"a2_391",word:"sens",article:"un",translation_tr:"anlam / duygu",translation_en:"meaning/sense",phonetic:"sɑ̃s",category:"general",gender:"m",level:"A2",emoji:"💡"},
  {id:"a2_392",word:"valeur",article:"une",translation_tr:"değer",translation_en:"value",phonetic:"va.lœʁ",category:"general",gender:"f",level:"A2",emoji:"💎"},
  {id:"a2_393",word:"principe",article:"un",translation_tr:"ilke / prensip",translation_en:"principle",phonetic:"pʁɛ̃.sip",category:"general",gender:"m",level:"A2",emoji:"⚖️"},
  {id:"a2_394",word:"attitude",article:"une",translation_tr:"tutum / davranış",translation_en:"attitude",phonetic:"a.ti.tyd",category:"general",gender:"f",level:"A2",emoji:"🧍"},
  {id:"a2_395",word:"comportement",article:"un",translation_tr:"davranış",translation_en:"behaviour",phonetic:"kɔ̃.pɔʁt.mɑ̃",category:"general",gender:"m",level:"A2",emoji:"🧍"},
  {id:"a2_396",word:"personnalité",article:"une",translation_tr:"kişilik",translation_en:"personality",phonetic:"pɛʁ.sɔ.na.li.te",category:"general",gender:"f",level:"A2",emoji:"🧑"},
  {id:"a2_397",word:"caractère",article:"un",translation_tr:"karakter / huy",translation_en:"character",phonetic:"ka.ʁak.tɛʁ",category:"general",gender:"m",level:"A2",emoji:"🧑"},
  {id:"a2_398",word:"humeur",article:"une",translation_tr:"ruh hali / mizaç",translation_en:"mood/humour",phonetic:"y.mœʁ",category:"general",gender:"f",level:"A2",emoji:"😊"},
  {id:"a2_399",word:"bien-être",article:"un",translation_tr:"refah / iyilik hali",translation_en:"well-being",phonetic:"bjɛ̃ ɛtʁ",category:"general",gender:"m",level:"A2",emoji:"✨"},
  {id:"a2_400",word:"quotidien",article:"un",translation_tr:"günlük yaşam",translation_en:"daily life",phonetic:"kɔ.ti.djɛ̃",category:"general",gender:"m",level:"A2",emoji:"📅"},
  {id:"a2_401",word:"calendrier",article:"un",translation_tr:"takvim",translation_en:"calendar",phonetic:"ka.lɑ̃.dʁje",category:"general",gender:"m",level:"A2",emoji:"📅"},
  {id:"a2_402",word:"planning",article:"un",translation_tr:"planlama / ajanda",translation_en:"planning",phonetic:"pla.niŋ",category:"general",gender:"m",level:"A2",emoji:"📋"},
  {id:"a2_403",word:"emploi du temps",article:"un",translation_tr:"ders / çalışma programı",translation_en:"timetable",phonetic:"ɑ̃.plwa dy tɑ̃",category:"general",gender:"m",level:"A2",emoji:"🗓️"},
  {id:"a2_404",word:"augmentation",article:"une",translation_tr:"artış",translation_en:"increase",phonetic:"oɡ.mɑ̃.ta.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"📈"},
  {id:"a2_405",word:"diminution",article:"une",translation_tr:"azalma",translation_en:"decrease",phonetic:"di.mi.ny.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"📉"},
  {id:"a2_406",word:"croissance",article:"une",translation_tr:"büyüme",translation_en:"growth",phonetic:"kʁwa.sɑ̃s",category:"general",gender:"f",level:"A2",emoji:"📈"},
  {id:"a2_407",word:"réduction",article:"une",translation_tr:"indirim / azaltma",translation_en:"reduction",phonetic:"ʁe.dyk.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"📉"},
  {id:"a2_408",word:"protection",article:"une",translation_tr:"koruma",translation_en:"protection",phonetic:"pʁɔ.tɛk.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"🛡️"},
  {id:"a2_409",word:"danger",article:"un",translation_tr:"tehlike",translation_en:"danger",phonetic:"dɑ̃.ʒe",category:"general",gender:"m",level:"A2",emoji:"⚠️"},
  {id:"a2_410",word:"efficacité",article:"une",translation_tr:"etkinlik / verimlilik",translation_en:"effectiveness",phonetic:"e.fi.ka.si.te",category:"general",gender:"f",level:"A2",emoji:"📈"},
  {id:"a2_411",word:"utilité",article:"une",translation_tr:"kullanışlılık",translation_en:"usefulness",phonetic:"y.ti.li.te",category:"general",gender:"f",level:"A2",emoji:"✅"},
  {id:"a2_412",word:"ressemblance",article:"une",translation_tr:"benzerlik",translation_en:"resemblance",phonetic:"ʁə.sɑ̃.blɑ̃s",category:"general",gender:"f",level:"A2",emoji:"🔄"},
  {id:"a2_413",word:"catégorie",article:"une",translation_tr:"kategori",translation_en:"category",phonetic:"ka.te.ɡɔ.ʁi",category:"general",gender:"f",level:"A2",emoji:"📋"},
  {id:"a2_414",word:"secteur",article:"un",translation_tr:"sektör",translation_en:"sector",phonetic:"sɛk.tœʁ",category:"general",gender:"m",level:"A2",emoji:"📊"},
  {id:"a2_415",word:"type",article:"un",translation_tr:"tür / çeşit",translation_en:"type",phonetic:"tip",category:"general",gender:"m",level:"A2",emoji:"📋"},
  {id:"a2_416",word:"paragraphe",article:"un",translation_tr:"paragraf",translation_en:"paragraph",phonetic:"pa.ʁa.ɡʁaf",category:"general",gender:"m",level:"A2",emoji:"📝"},
  {id:"a2_417",word:"phase",article:"une",translation_tr:"faz / aşama",translation_en:"phase",phonetic:"faz",category:"general",gender:"f",level:"A2",emoji:"📋"},
  {id:"a2_418",word:"ensemble",article:"un",translation_tr:"bütün / toplam",translation_en:"whole/set",phonetic:"ɑ̃.sɑ̃bl",category:"general",gender:"m",level:"A2",emoji:"🔄"},
  {id:"a2_419",word:"fonctionnement",article:"un",translation_tr:"işleyiş",translation_en:"functioning",phonetic:"fɔ̃k.sjɔn.mɑ̃",category:"general",gender:"m",level:"A2",emoji:"⚙️"},
  {id:"a2_420",word:"réseau",article:"un",translation_tr:"ağ / network",translation_en:"network",phonetic:"ʁe.zo",category:"general",gender:"m",level:"A2",emoji:"🌐"},
  {id:"a2_421",word:"lien",article:"un",translation_tr:"bağ / link",translation_en:"link/bond",phonetic:"ljɛ̃",category:"general",gender:"m",level:"A2",emoji:"🔗"},
  {id:"a2_422",word:"contact",article:"un",translation_tr:"iletişim / temas",translation_en:"contact",phonetic:"kɔ̃.takt",category:"general",gender:"m",level:"A2",emoji:"📞"},
  {id:"a2_423",word:"résidence",article:"une",translation_tr:"konut / ikamet",translation_en:"residence",phonetic:"ʁe.zi.dɑ̃s",category:"general",gender:"f",level:"A2",emoji:"🏠"},
  {id:"a2_424",word:"nationalité",article:"une",translation_tr:"uyruk / milliyet",translation_en:"nationality",phonetic:"na.sjɔ.na.li.te",category:"general",gender:"f",level:"A2",emoji:"🌍"},
  {id:"a2_425",word:"identité",article:"une",translation_tr:"kimlik",translation_en:"identity",phonetic:"i.dɑ̃.ti.te",category:"general",gender:"f",level:"A2",emoji:"🪪"},
  {id:"a2_426",word:"citoyenneté",article:"une",translation_tr:"vatandaşlık",translation_en:"citizenship",phonetic:"si.twa.jɛn.te",category:"general",gender:"f",level:"A2",emoji:"🌍"},
  {id:"a2_427",word:"population",article:"une",translation_tr:"nüfus",translation_en:"population",phonetic:"pɔ.py.la.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"👥"},
  {id:"a2_428",word:"territoire",article:"un",translation_tr:"toprak / bölge",translation_en:"territory",phonetic:"tɛ.ʁi.twaʁ",category:"general",gender:"m",level:"A2",emoji:"🗺️"},
  {id:"a2_429",word:"capital",article:"une",translation_tr:"başkent",translation_en:"capital city",phonetic:"ka.pi.tal",category:"general",gender:"f",level:"A2",emoji:"🏛️"},
  {id:"a2_430",word:"langue officielle",article:"une",translation_tr:"resmi dil",translation_en:"official language",phonetic:"lɑ̃ɡ ɔ.fi.sjɛl",category:"general",gender:"f",level:"A2",emoji:"🗣️"},
  {id:"a2_431",word:"sondage",article:"un",translation_tr:"anket",translation_en:"survey/poll",phonetic:"sɔ̃.daʒ",category:"general",gender:"m",level:"A2",emoji:"📊"},
  {id:"a2_432",word:"statistique",article:"une",translation_tr:"istatistik",translation_en:"statistic",phonetic:"sta.tis.tik",category:"general",gender:"f",level:"A2",emoji:"📊"},
  {id:"a2_433",word:"pourcentage",article:"un",translation_tr:"yüzde / oran",translation_en:"percentage",phonetic:"puʁ.sɑ̃.taʒ",category:"general",gender:"m",level:"A2",emoji:"💯"},
  {id:"a2_434",word:"chiffre",article:"un",translation_tr:"rakam / sayı",translation_en:"figure/number",phonetic:"ʃifʁ",category:"general",gender:"m",level:"A2",emoji:"🔢"},
  {id:"a2_435",word:"données",article:"des",translation_tr:"veriler",translation_en:"data",phonetic:"dɔ.ne",category:"general",gender:"f",level:"A2",emoji:"📊"},
  {id:"a2_436",word:"analyse",article:"une",translation_tr:"analiz",translation_en:"analysis",phonetic:"a.na.liz",category:"general",gender:"f",level:"A2",emoji:"🔍"},
  {id:"a2_437",word:"synthèse",article:"une",translation_tr:"sentez / özet",translation_en:"synthesis/summary",phonetic:"sɛ̃.tɛz",category:"general",gender:"f",level:"A2",emoji:"📝"},
  {id:"a2_438",word:"hypothèse",article:"une",translation_tr:"hipotez / varsayım",translation_en:"hypothesis",phonetic:"i.pɔ.tɛz",category:"general",gender:"f",level:"A2",emoji:"🤔"},
  {id:"a2_439",word:"conclusion",article:"une",translation_tr:"sonuç / netice",translation_en:"conclusion",phonetic:"kɔ̃.kly.zjɔ̃",category:"general",gender:"f",level:"A2",emoji:"🏁"},
  {id:"a2_440",word:"introduction",article:"une",translation_tr:"giriş",translation_en:"introduction",phonetic:"ɛ̃.tʁɔ.dyk.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"📖"},
  {id:"a2_441",word:"réunion",article:"une",translation_tr:"toplantı",translation_en:"meeting",phonetic:"ʁe.y.njɔ̃",category:"general",gender:"f",level:"A2",emoji:"🤝"},
  {id:"a2_442",word:"rendez-vous",article:"un",translation_tr:"randevu",translation_en:"appointment",phonetic:"ʁɑ̃.de.vu",category:"general",gender:"m",level:"A2",emoji:"📅"},
  {id:"a2_443",word:"vacances",article:"des",translation_tr:"tatil",translation_en:"holidays",phonetic:"va.kɑ̃s",category:"general",gender:"f",level:"A2",emoji:"🏖️"},
  {id:"a2_444",word:"voyage",article:"un",translation_tr:"seyahat",translation_en:"travel",phonetic:"vwa.jaʒ",category:"general",gender:"m",level:"A2",emoji:"✈️"},
  {id:"a2_445",word:"sport",article:"un",translation_tr:"spor",translation_en:"sport",phonetic:"spɔʁ",category:"general",gender:"m",level:"A2",emoji:"⚽"},
  {id:"a2_446",word:"musique",article:"une",translation_tr:"müzik",translation_en:"music",phonetic:"my.zik",category:"general",gender:"f",level:"A2",emoji:"🎵"},
  {id:"a2_447",word:"cinéma",article:"un",translation_tr:"sinema",translation_en:"cinema",phonetic:"si.ne.ma",category:"general",gender:"m",level:"A2",emoji:"🎬"},
  {id:"a2_448",word:"appartement",article:"un",translation_tr:"daire",translation_en:"apartment",phonetic:"a.paʁ.tə.mɑ̃",category:"general",gender:"m",level:"A2",emoji:"🏢"},
  {id:"a2_449",word:"cuisine",article:"une",translation_tr:"mutfak",translation_en:"kitchen",phonetic:"kɥi.zin",category:"general",gender:"f",level:"A2",emoji:"👨‍🍳"},
  {id:"a2_450",word:"chambre",article:"une",translation_tr:"yatak odası",translation_en:"bedroom",phonetic:"ʃɑ̃bʁ",category:"general",gender:"f",level:"A2",emoji:"🛏️"},
  {id:"a2_451",word:"travail",article:"un",translation_tr:"iş",translation_en:"work",phonetic:"tʁa.vaj",category:"general",gender:"m",level:"A2",emoji:"💼"},
  {id:"a2_452",word:"santé",article:"une",translation_tr:"sağlık",translation_en:"health",phonetic:"sɑ̃.te",category:"general",gender:"f",level:"A2",emoji:"❤️"},
  {id:"a2_453",word:"pluie",article:"une",translation_tr:"yağmur",translation_en:"rain",phonetic:"plɥi",category:"general",gender:"f",level:"A2",emoji:"🌧️"},
  {id:"a2_454",word:"neige",article:"une",translation_tr:"kar",translation_en:"snow",phonetic:"nɛʒ",category:"general",gender:"f",level:"A2",emoji:"❄️"},
  {id:"a2_455",word:"météo",article:"une",translation_tr:"hava durumu",translation_en:"weather",phonetic:"me.te.o",category:"general",gender:"f",level:"A2",emoji:"⛅"},
  {id:"a2_456",word:"marché",article:"un",translation_tr:"pazar / market",translation_en:"market",phonetic:"maʁ.ʃe",category:"general",gender:"m",level:"A2",emoji:"🛍️"},
  {id:"a2_457",word:"magasin",article:"un",translation_tr:"mağaza",translation_en:"shop",phonetic:"ma.ɡa.zɛ̃",category:"general",gender:"m",level:"A2",emoji:"🏪"},
  {id:"a2_458",word:"cadeau",article:"un",translation_tr:"hediye",translation_en:"gift",phonetic:"ka.do",category:"general",gender:"m",level:"A2",emoji:"🎁"},
  {id:"a2_459",word:"peinture",article:"une",translation_tr:"resim / boya",translation_en:"painting",phonetic:"pɛ̃.tyʁ",category:"general",gender:"f",level:"A2",emoji:"🖼️"},
  {id:"a2_460",word:"dessin",article:"un",translation_tr:"çizim",translation_en:"drawing",phonetic:"dɛ.sɛ̃",category:"general",gender:"m",level:"A2",emoji:"🎨"},
  {id:"a2_461",word:"photographie",article:"une",translation_tr:"fotoğraf",translation_en:"photography",phonetic:"fɔ.tɔ.ɡʁa.fi",category:"general",gender:"f",level:"A2",emoji:"📸"},
  {id:"a2_462",word:"promenade",article:"une",translation_tr:"yürüyüş",translation_en:"walk",phonetic:"pʁɔm.nad",category:"general",gender:"f",level:"A2",emoji:"🚶"},
  {id:"a2_463",word:"concert",article:"un",translation_tr:"konser",translation_en:"concert",phonetic:"kɔ̃.sɛʁ",category:"general",gender:"m",level:"A2",emoji:"🎸"},
  {id:"a2_464",word:"spectacle",article:"un",translation_tr:"gösteri",translation_en:"show",phonetic:"spɛk.takl",category:"general",gender:"m",level:"A2",emoji:"🎭"},
  {id:"a2_465",word:"jardinage",article:"un",translation_tr:"bahçecilik",translation_en:"gardening",phonetic:"ʒaʁ.di.naʒ",category:"general",gender:"m",level:"A2",emoji:"🌱"},
  {id:"a2_466",word:"lecture",article:"une",translation_tr:"okuma",translation_en:"reading",phonetic:"lɛk.tyʁ",category:"general",gender:"f",level:"A2",emoji:"📖"},
  {id:"a2_467",word:"danse",article:"une",translation_tr:"dans",translation_en:"dance",phonetic:"dɑ̃s",category:"general",gender:"f",level:"A2",emoji:"💃"},
  {id:"a2_468",word:"jeu",article:"un",translation_tr:"oyun",translation_en:"game",phonetic:"ʒø",category:"general",gender:"m",level:"A2",emoji:"🎮"},
  {id:"a2_469",word:"film",article:"un",translation_tr:"film",translation_en:"film",phonetic:"film",category:"general",gender:"m",level:"A2",emoji:"🎬"},
  {id:"a2_470",word:"chanson",article:"une",translation_tr:"şarkı",translation_en:"song",phonetic:"ʃɑ̃.sɔ̃",category:"general",gender:"f",level:"A2",emoji:"🎵"},
  {id:"a2_471",word:"roman",article:"un",translation_tr:"roman",translation_en:"novel",phonetic:"ʁɔ.mɑ̃",category:"general",gender:"m",level:"A2",emoji:"📖"},
  {id:"a2_472",word:"recette",article:"une",translation_tr:"tarif",translation_en:"recipe",phonetic:"ʁə.sɛt",category:"general",gender:"f",level:"A2",emoji:"🍽️"},
  {id:"a2_473",word:"ingrédient",article:"un",translation_tr:"malzeme / içerik",translation_en:"ingredient",phonetic:"ɛ̃.ɡʁe.djɑ̃",category:"general",gender:"m",level:"A2",emoji:"🧂"},
  {id:"a2_474",word:"plat",article:"un",translation_tr:"yemek / tabak",translation_en:"dish",phonetic:"pla",category:"general",gender:"m",level:"A2",emoji:"🍽️"},
  {id:"a2_475",word:"entrée",article:"une",translation_tr:"başlangıç yemeği / giriş",translation_en:"starter/entrance",phonetic:"ɑ̃.tʁe",category:"general",gender:"f",level:"A2",emoji:"🥗"},
  {id:"a2_476",word:"dessert",article:"un",translation_tr:"tatlı",translation_en:"dessert",phonetic:"de.sɛʁ",category:"general",gender:"m",level:"A2",emoji:"🍰"},
  {id:"a2_477",word:"boisson",article:"une",translation_tr:"içecek",translation_en:"drink/beverage",phonetic:"bwa.sɔ̃",category:"general",gender:"f",level:"A2",emoji:"🥤"},
  {id:"a2_478",word:"apéritif",article:"un",translation_tr:"aperatif",translation_en:"aperitif",phonetic:"a.pe.ʁi.tif",category:"general",gender:"m",level:"A2",emoji:"🍷"},
  {id:"a2_479",word:"champagne",article:"un",translation_tr:"şampanya",translation_en:"champagne",phonetic:"ʃɑ̃.paɲ",category:"general",gender:"m",level:"A2",emoji:"🍾"},
  {id:"a2_480",word:"terrasse de café",article:"une",translation_tr:"kafe terasası",translation_en:"café terrace",phonetic:"tɛ.ʁas də ka.fe",category:"general",gender:"f",level:"A2",emoji:"☕"},
  {id:"a2_481",word:"quartier",article:"un",translation_tr:"mahalle / semt",translation_en:"neighbourhood",phonetic:"kaʁ.tje",category:"general",gender:"m",level:"A2",emoji:"🏘️"},
  {id:"a2_482",word:"banlieue",article:"une",translation_tr:"banliyö / varoş",translation_en:"suburb",phonetic:"bɑ̃.ljø",category:"general",gender:"f",level:"A2",emoji:"🏘️"},
  {id:"a2_483",word:"centre commercial",article:"un",translation_tr:"alışveriş merkezi",translation_en:"shopping centre",phonetic:"sɑ̃tʁ kɔ.mɛʁ.sjal",category:"general",gender:"m",level:"A2",emoji:"🏬"},
  {id:"a2_484",word:"pharmacien",article:"un",translation_tr:"eczacı",translation_en:"pharmacist",phonetic:"faʁ.ma.sjɛ̃",category:"general",gender:"m",level:"A2",emoji:"💊"},
  {id:"a2_485",word:"coiffeur",article:"un",translation_tr:"kuaför / berber",translation_en:"hairdresser",phonetic:"kwa.fœʁ",category:"general",gender:"m",level:"A2",emoji:"✂️"},
  {id:"a2_486",word:"plombier",article:"un",translation_tr:"tesisatçı",translation_en:"plumber",phonetic:"plɔ̃.bje",category:"general",gender:"m",level:"A2",emoji:"🔧"},
  {id:"a2_487",word:"électricien",article:"un",translation_tr:"elektrikçi",translation_en:"electrician",phonetic:"e.lɛk.tʁi.sjɛ̃",category:"general",gender:"m",level:"A2",emoji:"⚡"},
  {id:"a2_488",word:"mécanicien",article:"un",translation_tr:"tamirci / makinist",translation_en:"mechanic",phonetic:"me.ka.ni.sjɛ̃",category:"general",gender:"m",level:"A2",emoji:"🔧"},
  {id:"a2_489",word:"chauffeur",article:"un",translation_tr:"şoför",translation_en:"driver",phonetic:"ʃo.fœʁ",category:"general",gender:"m",level:"A2",emoji:"🚗"},
  {id:"a2_490",word:"livreur",article:"un",translation_tr:"kurye / dağıtımcı",translation_en:"delivery person",phonetic:"li.vʁœʁ",category:"general",gender:"m",level:"A2",emoji:"📦"},
  {id:"a2_491",word:"trajet",article:"un",translation_tr:"yolculuk / güzergah",translation_en:"journey/route",phonetic:"tʁa.ʒɛ",category:"general",gender:"m",level:"A2",emoji:"🚗"},
  {id:"a2_492",word:"embouteillage",article:"un",translation_tr:"trafik sıkışıklığı",translation_en:"traffic jam",phonetic:"ɑ̃.bu.tɛ.jaʒ",category:"general",gender:"m",level:"A2",emoji:"🚗"},
  {id:"a2_493",word:"transports en commun",article:"des",translation_tr:"toplu taşıma",translation_en:"public transport",phonetic:"tʁɑ̃s.pɔʁ ɑ̃ kɔ.mœ̃",category:"general",gender:"m",level:"A2",emoji:"🚌"},
  {id:"a2_494",word:"abonnement de transport",article:"un",translation_tr:"ulaşım aboneliği",translation_en:"transport pass",phonetic:"a.bɔn.mɑ̃ də tʁɑ̃s.pɔʁ",category:"general",gender:"m",level:"A2",emoji:"🎫"},
  {id:"a2_495",word:"péage",article:"un",translation_tr:"otoyol gişesi / geçiş ücreti",translation_en:"toll",phonetic:"pe.aʒ",category:"general",gender:"m",level:"A2",emoji:"🛣️"},
  {id:"a2_496",word:"amende",article:"une",translation_tr:"para cezası",translation_en:"fine/penalty",phonetic:"a.mɑ̃d",category:"general",gender:"f",level:"A2",emoji:"💰"},
  {id:"a2_497",word:"assurance auto",article:"une",translation_tr:"araç sigortası",translation_en:"car insurance",phonetic:"a.sy.ʁɑ̃s o.to",category:"general",gender:"f",level:"A2",emoji:"🚗"},
  {id:"a2_498",word:"contrôle technique",article:"un",translation_tr:"muayene / teknik kontrol",translation_en:"MOT/vehicle inspection",phonetic:"kɔ̃.tʁol tɛk.nik",category:"general",gender:"m",level:"A2",emoji:"🔧"},
  {id:"a2_499",word:"déclaration",article:"une",translation_tr:"beyan / bildiri",translation_en:"declaration",phonetic:"de.kla.ʁa.sjɔ̃",category:"general",gender:"f",level:"A2",emoji:"📋"},
  {id:"a2_500",word:"demande d'emploi",article:"une",translation_tr:"iş başvurusu",translation_en:"job application",phonetic:"də.mɑ̃d dɑ̃.plwa",category:"general",gender:"f",level:"A2",emoji:"📝"},
];
